Translated backups.md into German
ScootKit/scnx-docs pull request #2
Opened 2023-08-30 20:55 UTC by hfgd123

## Type of PR

- [ X ] Translation update / creation
- [ ] Original file creation
- [ ] Original file update

## Checks

If you have changed an original file, please confirm:

- [ ] Yes, I have copied the updated section to all translations of this file manually.

## Notes

- Did not translate specific error messages in the Troubleshooting part as I don't have the exact wording in the German version.
- Did not translate "THIS FEATURE MIGHT NOT BE ABLE TO EVERYONE" as I don't know what that means

2023-08-30 21:32 UTC, SCDerox requested changes
Thanks for your contributions. I've adjusted a few things, please review them.

 I belive that none of the error messages are localised into German atm.

2023-08-30 21:32 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/backups.md
> +Da Backups vertrauliche Nutzerinformationen und Nachrichten beinhalten werden sie verschlüsselt gespeichert und nur während sie aktiv verwendet werden (z.B. während der Wiederherstellung) entschlüsse
```suggestion
Da Backups vertrauliche Nutzerinformationen und Nachrichten beinhalten, werden sie verschlüsselt gespeichert und nur während sie aktiv verwendet werden (z.B. während der Wiederherstellung) entschlüsselt. Trotzdem weisen wir dich darauf hin, möglichst keine Nachrichten, die private Daten enthalten (wie Kreditkartendaten, Sozialversicherungsnummern oder ähnliches), in Kanäle, die in Backups enthalten sind, zu senden.
```
Please respect the German construct of "Relativsatz"

2023-08-30 21:32 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/backups.md
> +| Mitglieder          | Backups werden beinhalten welcher Nutzer welche Rolle zum Zeitpunkt der Backup-Erstellung hatte.<br/> **THIS FEATURE MIGHT NOT BE ABLE TO EVERYONE**                        |
```suggestion
| Mitglieder          | Backups werden beinhalten welcher Nutzer welche Rolle zum Zeitpunkt der Backup-Erstellung hatte.<br/> **DIESE FUNKTION IST EVENTUELL NICHT FÜR ALLE VERFÜGBAR**                        |
```

2023-08-30 21:32 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/backups.md
> +Ein Backup zu erstellen kann bis zu 15 Minuten dauern. Dies ist abhängig von der Anzahl der zu speichernden Nachrichten.
```suggestion
Ein Backup zu Erstellen kann bis zu 15 Minuten dauern. Dies ist abhängig von der Anzahl der zu speichernden Nachrichten.
```

2023-08-30 21:32 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/backups.md
> +* Backup wiederherstellen: Erm,öglicht dir das Backup auf diesem oder einem anderen Server wiederherzustellen. Im Abschnitt [Backups wiederherstellen](#restore) kannst du mehr darüber erfahren.
```suggestion
* Backup wiederherstellen: Ermöglicht dir das Backup auf diesem oder einem anderen Server wiederherzustellen. Im Abschnitt [Backups wiederherstellen](#restore) kannst du mehr darüber erfahren.
```

2023-08-30 21:32 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/backups.md
> +Um ein Backup auf deinem Server wiederherzustellen, öffne das [Backup-Dashboard](https://scnx.app/de/glink?page=backups) deines Servers und klicke auf das Backup, das du wiederherstellen möchtest. Al
```suggestion
Um ein Backup auf deinem Server wiederherzustellen, öffne das [Backup-Dashboard](https://scnx.app/de/glink?page=backups) deines Servers und klicke auf das Backup, das du wiederherstellen möchtest. Als nächstes klicke auf "Backup wiederherstellen". Dir wird ein Befehl angezeigt werden. Kopiere ihn mit dem "Befehl kopieren" Knopf und füge ihn in deinem Server ein. Stelle sicher, dass du den Befehl mit dem (verifizierten) SCNX-Bot ausführst.
```

2023-08-30 21:32 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/backups.md
> +Bestätige als Nächstes deine Anfrage mit dem Button unter der Antwort in Discord.
```suggestion
Bestätige als Nächstes deine Anfrage mit dem Knopf unter der Antwort in Discord.
```

2023-08-30 21:32 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/backups.md
> +Die Server-Sperre ist ein Sicherheitsmechanismus für dein Backup: Wenn sie deaktiviert ist, kann jeder mit dem Backup-Code (der Befehl der im Dashboard angezeigt wird) das Backup auf jedem Server wie
```suggestion
Die Server-Sperre ist ein Sicherheitsmechanismus für dein Backup: Wenn sie deaktiviert ist, kann jeder mit dem Backup-Code (der Befehl der im Dashboard angezeigt wird) das Backup auf jedem Server wiederherstellen. Zum Glück ist die Sperre standardmäßig aktiviert. Um sie zu deaktivieren, öffne das [Backup-Dashboard](https://scnx.app/de/glink?page=backups), wähle dein Backup und klicke auf "Server-Sperre deaktivieren".
```

2023-08-30 21:32 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/backups.md
> +    <li>Stelle sicher, dasss du [diese Funktion](#automatic] wirklich aktiviert hast und alle Änderungen gespeichert hast.</li>
```suggestion
    <li>Stelle sicher, dasss du [diese Funktion](#automatic) wirklich aktiviert hast und alle Änderungen gespeichert hast.</li>
```

2023-08-30 21:35 UTC, hfgd123 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/backups.md
> +Bestätige als Nächstes deine Anfrage mit dem Button unter der Antwort in Discord.
For virtual buttons "Knopf" somehow sounds weird... But I guess it is correct language-wise

2023-08-30 21:42 UTC, SCDerox approved these changes
lgtm

2023-08-30 21:42 UTC, merged

2023-08-31 13:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/backups.md
> +Bestätige als Nächstes deine Anfrage mit dem Button unter der Antwort in Discord.
I find "Schaltfläche" even more weird then "Knopf", so what should we use?

2023-08-31 13:22 UTC, hfgd123 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/backups.md
> +Bestätige als Nächstes deine Anfrage mit dem Button unter der Antwort in Discord.
Idk. German doesn't really have a good word considering context and targeted audience here

2023-08-31 13:23 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/backups.md
> +Bestätige als Nächstes deine Anfrage mit dem Button unter der Antwort in Discord.
I agree, that's why I choose "Knopf", as this is the most intuitive translation of "Button" and describes the function of a button most