Translate & update channel-stats.md
ScootKit/scnx-docs pull request #20
Opened 2023-09-09 21:44 UTC by Fridolin012

## Type of PR

- [X] Translation update / creation
- [ ] Original file creation
- [ ] Original file content (not typo) update
- [X] Original file typo update

## Checks

If you have changed the content (/ meaning) of an original file, please confirm:

- [ ] Yes, I have copied the updated section to all translations of this file manually.

## Notes

Please enter additional information here.

2023-09-10 09:28 UTC, SCDerox requested changes
Thanks so much for your contribution - I've found a few issues, please review my comments.

2023-09-10 09:28 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/channel-stats.md
> +Erstelle Sprachkanäle auf deinem Server, welche automatisch aktuelle Statistiken anzeigen - wie die Anzahl der Mitglieder
```suggestion
Erstelle Sprachkanäle auf deinem Server, welche automatisch aktuelle Statistiken anzeigen, wie z.B. die Anzahl der Mitglieder 
```
In german, the use of "wie", associated with "-" as an expression of a exemplary value, sounds weird

2023-09-10 09:28 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/channel-stats.md
> +Hier ist ein Beispiel, wie 3 Sprachkanäle einige Statistiken über einen Server zeigen:
```suggestion
Hier ist ein Beispiel von drei Sprachkanäle, die einige Statistiken über einen Server zeigen:
```

2023-09-10 09:28 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/channel-stats.md
> +3. Öffne die [Channel-Statistiken-Konfiguration](https://scnx.app/de/glink?page=bot/configuration?file=channel-stats%7Cchannels).
```suggestion
3. Öffne die [Kanal-Statistiken-Konfiguration](https://scnx.app/de/glink?page=bot/configuration?file=channel-stats%7Cchannels).
```

2023-09-10 09:28 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/channel-stats.md
> +# Channel-Statistiken
```suggestion
# Kanal-Statistiken
```

2023-09-10 09:28 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/channel-stats.md
> +    Wenn du den Namen des Kanals verändern willst, musst du das Feld "Kanalname" in der <a href="https://scnx.app/glink?page=bot/configuration?file=channel-stats%7Cchannel">Modul-Konfiguration</a> de
```suggestion
    Wenn du den Namen des Kanals verändern willst, musst du das Feld "Kanalname" in der <a href="https://scnx.app/de/glink?page=bot/configuration?file=channel-stats%7Cchannel">Modul-Konfiguration</a> des Kanals aktualisieren.
```

2023-09-10 09:28 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/channel-stats.md
> +        <li>Es dauert eventuell länger als das für diesen Kanal festgelegte Aktualisierungs-Intervall aufgrund Limitierungen von Discord. Bitte warte bis zu drei Stunden.</li>
```suggestion
        <li>Es dauert eventuell, aufgrund von Limitierungen von Discord, länger als das für diesen Kanal festgelegte Interval. Bitte warte bis zu drei Stunden.</li>
```
This is way more readable I think

2023-09-10 09:28 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/channel-stats.md
> +        <li>Aktualisiere deinen Client, wenn eine Änderung nicht sichtbar ist.</li>
```suggestion
        <li>Aktualisiere deinen Discord-Client, wenn eine Änderung nicht sichtbar ist.</li>
```

2023-09-10 09:28 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/channel-stats.md
> +    Der Name des Channels wird nicht aktualisiert, wenn der neue dem altem gleicht.
```suggestion
    Der Name des Channels wird nicht aktualisiert, wenn der neue dem Altem gleicht.
```

2023-09-10 09:45 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/channel-stats.md
> +        <li>Es dauert eventuell länger als das für diesen Kanal festgelegte Aktualisierungs-Intervall aufgrund Limitierungen von Discord. Bitte warte bis zu drei Stunden.</li>
```suggestion
        <li>Es dauert eventuell, aufgrund von Limitierungen von Discord, länger als das für diesen Kanal festgelegte Intervall. Bitte warte bis zu drei Stunden.</li>
```

I think “interval” is spelled with 2 “l”.

2023-09-10 09:45 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/channel-stats.md
> +Hier ist ein Beispiel, wie 3 Sprachkanäle einige Statistiken über einen Server zeigen:
```suggestion
Hier ist ein Beispiel von drei Sprachkanälen, die einige Statistiken über einen Server zeigen:
```

I think "voice channels" has to be plural

2023-09-10 09:50 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/channel-stats.md
> +        <li>Es dauert eventuell länger als das für diesen Kanal festgelegte Aktualisierungs-Intervall aufgrund Limitierungen von Discord. Bitte warte bis zu drei Stunden.</li>
This is correct, I've updated my comment

2023-09-10 09:51 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/channel-stats.md
> +Hier ist ein Beispiel, wie 3 Sprachkanäle einige Statistiken über einen Server zeigen:
this is correct, I've updated my comment

2023-09-10 14:59 UTC, SCDerox approved these changes
lgtm

2023-09-10 14:59 UTC, merged

2023-09-16 14:52 UTC, SCDerox commented
Thanks for your contribution - you have received a payout as part of our [Open Source Developer Program](https://faq.scnx.app/open-source-developer-pool/). You can find details in your SCNX organisation payout history. To pay out the received amount, please follow instructions in your dashboard. If you have any questions, please contact ScootKit staff on [scnx.app/help](https://scnx.app/help).
Cheers ✌️

2023-11-05 11:22 UTC, Fridolin012 commented
Kommentar

2023-11-05 11:24 UTC, SCDerox commented
Thanks for getting back to me. It seems like you've already received a bounty for this contribution.

2023-11-05 11:26 UTC, Fridolin012 commented
Oh, I overlooked that.