Create analytics.md
ScootKit/scnx-docs pull request #21
Opened 2023-09-09 22:29 UTC by patricksynced

## Type of PR

- [ X ] Translation update / creation
- [ ] Original file creation
- [ ] Original file content (not typo) update
- [ ] Original file typo update

## Checks

If you have changed the content (/ meaning) of an original file, please confirm:

- [ ] Yes, I have copied the updated section to all translations of this file manually.

## Notes

Please enter additional information here.

2023-09-09 22:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ScootKit/scnx-docs?pullRequest=21) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ScootKit/scnx-docs?pullRequest=21) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ScootKit/scnx-docs?pullRequest=21) it.</sub>

2023-09-10 05:52 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +für weitere Informationen folgendes durch [FAQ-Artikel](https://faq.scnx.app/de/data-collection-with-analytics/).
```suggestion
Du fragst dich, welche Daten wir über deinen Server speichern und wie wir sie verwenden? Bitte lese 
unseren [FAQ-Artikel](https://faq.scnx.app/datenerhebung-bei-statistiken/), um mehr zu erfahren.
```

2023-09-10 06:58 UTC, Fridolin012 reviewed
I suggested some changes for analytics.md

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +In deinem [Analyse-Dashboard](https://scnx.app/de/glink?page=analytics) kannst du die folgenden Daten basierend eines Zeitrahmens sehen, den Du oben in deinem Dashboard auswählen kannst:
```suggestion
Im [Statistiken-Dashboard](https://scnx.app/de/glink?page=analytics) kannst du die folgenden Daten basierend auf einem Zeitraum sehen, den Du oben in deinem Dashboard auswählen kannst:
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +„Analyse aktivieren“.
```suggestion
Um Statistiken zu aktivieren, besuche bitte die [Statistiken-Seite](https://scnx.app/de/glink?page=analytics) deines Servers auf SCNX und klicke auf
„Statistiken aktivieren“.
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +## Analyse aktivieren {#enable}
```suggestion
## Statistiken aktivieren {#enable}
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +[Benutzer können sich abmelden](#user-opt-out) und es werden niemals Inhalte von Nachrichten (oder Anhängen) gespeichert.
```suggestion
**tl;dr**: Wir speichern Daten über Nachrichten nur für 30 Tage und dannach nur noch die Anzahl.
[Benutzer können sich abmelden](#user-opt-out) und es werden niemals Inhalte von Nachrichten (oder Anhängen) gespeichert.
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +# Serveranalyse
```suggestion
# Serverstatistiken
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* Nachrichten und Befehle: Du siehst ein Diagramm, das zeigt, wie viele Nachrichten und Befehle an jedem Tag im Zeitrahmen gesendet wurden.
```suggestion
* Nachrichten und Befehle: Du siehst ein Diagramm, das zeigt, wie viele Nachrichten und Befehle an jedem Tag im Zeitraum gesendet wurden.
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* 10 am häufigsten verwendete Kanäle: Dies ist eine Grafik, die zeigt, wie viel Prozent der Nachrichten über welchen Kanal gesendet wurden.
```suggestion
* 10 meist genutzte Kanäle: Dies ist eine Grafik, die zeigt, wie viel Prozent der Nachrichten über welchen Kanal gesendet wurden.
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* Aktivste Benutzer: Das sind die 15. aktivsten Nutzer (die den [Datenschutzmodus] (#user-opt-out) nicht aktiviert haben).
```suggestion
* Aktivste Benutzer: Das sind die 15. aktivsten Nutzer (die den [Datenschutzmodus](#user-opt-out) nicht aktiviert haben).
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* Mitgliederaktivität (immer letzten 30 Tage): Hier wird die Anzahl der Bots, Benutzer und aktive Mitglieder an jedem Tag im Zeitrahmen angezeigt.
```suggestion
* Nutzerverlauf (immer letzte 30 Tage): Hier wird die Anzahl der Bots, Benutzer und aktive Mitglieder an jedem Tag des Zeitraums angezeigt.
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* Aktivste Stunden am Tag: Diese Grafik zeigt, wie viele Nachrichten durchschnittlich zu welcher Zeit auf Ihrem Server gesendet wurden.
```suggestion
* Aktivste Stunden: Diese Grafik zeigt, wie viele Nachrichten durchschnittlich zu welcher Zeit auf deinem Server gesendet wurden.
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* Zusammenfassung: In diesem Abschnitt erhalten Sie einen schnellen Überblick über Ihren Server. Es umfasst folgende Daten:
```suggestion
* Auf einen Blick: In diesem Abschnitt erhältst du einen schnellen Überblick über deinen Server. Folgende Daten werden angezeigt:
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* Anzahl der Bots auf Ihrem Server
```suggestion
* Anzahl der im Zeitraum gesendeten Nachrichten
* Anzahl der im Zeitraum verwendeten Befehle
* Durchschnittliche Nachrichten pro Tag
* Anzahl der aktiven Mitglieder auf deinen Server (ausgenommen Benutzer, die den [Datenschutzmodus] nicht aktiviert haben (#user-opt-out))
* Anzahl der Benutzer auf deinem Server
* Anzahl der Bots auf deinem Server
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* „/stats user“: Zeigt eine Statistikübersicht aller Benutzer auf deinem Server an. Dazu gehören die 10 aktivsten Kanäle (und die Anzahl der darin gesendeten Nachrichten) sowie ein Abschnitt „Zusamme
```suggestion
* `/stats user`: Zeigt eine Statistikübersicht eines Benutzer auf deinem Server an. Dazu gehören die 10 aktivsten Kanäle (und die Anzahl der darin gesendeten Nachrichten) sowie ein Abschnitt „Auf einen Blick“, indem du die Gesamtzahl der Nachrichten und Befehle der letzten 30 Tage findest.
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +Tage. Benutzer, die den [Datenschutzmodus] (#user-opt-out) aktiviert haben, können diesen Befehl nicht verwenden (/ zeigt Daten darüber an).
```suggestion
Benutzer, die den [Datenschutzmodus](#user-opt-out) aktiviert haben, können diesen Befehl nicht verwenden (/ zeigt Daten darüber an).
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Bitte stell sicher, dass der (verifizierte) SCNX-Bot berechtigt ist, den Kanal anzuzeigen, über den die Nachricht gesendet wurden.
```suggestion
        <li>Bitte stelle sicher, dass der (verifizierte) SCNX-Bot berechtigt ist, den Kanal anzuzeigen, in den die Nachricht gesendet wurden.
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +            das Ergebnis im Dashboard generiert wurde ( dies wird oben auf der Seite angezeigt und sollte wie folgt aussehen: „Diese Zusammenfassung wurde
```suggestion
            das Ergebnis im Dashboard generiert wurde (dies wird oben auf der Seite angezeigt und sollte wie folgt aussehen: „Diese Zusammenfassung wurde
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Versuche, das Analyse-Dashboard in ein paar Minuten zu aktualisieren.</li>
```suggestion
        <li>Versuche, das Statistiken-Dashboard in ein paar Minuten zu aktualisieren.</li>
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Benutzer, für die der <a href="#user-opt-out">Datenschutzmodus</a> aktiviert ist, werden nicht im Dashboard angezeigt.
```suggestion
        <li>Benutzer, die den <a href="#user-opt-out">Datenschutzmodus</a> aktiviert haben, werden nicht im Dashboard angezeigt.
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Versuche, das Analyse-Dashboard in ein paar Minuten zu aktualisieren.</li>
```suggestion
        <li>Versuche, das Statistiken-Dashboard in ein paar Minuten zu aktualisieren.</li>
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        ^^" Warnung in deinem Dashboard
```suggestion
    <summary>Ich sehe die Meldung „Es gibt nicht viele Nachrichten im ausgewählten Zeitraum, daher sehen deine Diagramme möglicherweise etwas seltsam aus. ^^"  im Dashboard
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Stell sicher, dass Du einen ausreichenden Zeitrahmen ausgewählt hast (z. B. „Letzte 30 Tage“ statt „Letzten 24 Stunden“).</li>
```suggestion
        <li>Stelle sicher, dass Statistiken länger als 48 Stunden aktiviert sind.</li>
        <li>Aktualisiere dein Dashboard.</li>
        <li>Stelle sicher, dass Du einen ausreichenden Zeitraum ausgewählt hast (z. B. „Letzte 30 Tage“ statt „Letzte 24 Stunden“).</li>
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Bitte stell sicher, dass der (verifizierte) SCNX-Bot berechtigt ist, auf den Kanal zuzugreifen und den Nachrichtenverlauf sehen kann, über den die Nachrichten gesendet wurden.
```suggestion
        <li>Stelle sicher, dass im ausgewählten Zeitraum mehr als 100 Nachrichten gesendet wurden.</li>
        <li>Bitte stelle sicher, dass der (verifizierte) SCNX-Bot auf den Kanal zugreifen kann und den Nachrichtenverlauf sehen kann, über den die Nachrichten gesendet wurden.
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Stell sicher, dass SCNX mindestens einen Kanal auf deinem Server sehen und zugreifen kann.</li>
```suggestion
    <summary>Anstatt deine Mitgliederaktivität zu sehen, zeigt dir das Dashboard diese Warnung an: „Um Daten über deine Mitglieder anzuzeigen,
        musst du Statistiken seit mindestens 48 Stunden aktiviert haben.“
    </summary>
    <ul>
        <li>Stelle sicher, dass Statistiken länger als 48 Stunden aktiviert sind.</li>
        <li>Aktualisiere das Dashboard.</li>
        <li>Stelle sicher, dass SCNX mindestens einen Kanal auf deinem Server sehen kann.</li>
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +Alle infos findest Du unter [FAQ-Artikel](https://faq.scnx.app/de/data-collection-with-analytics/).
```suggestion
Alle infos findest du in unserem [FAQ-Artikel](https://faq.scnx.app/de/data-collection-with-analytics/).
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +gesendet hast oder Du befürchtest, dass personenbezogene Daten über Dich oder deine Nuztzer gespeichert werden, kannst du auf SCNX den „Datenschutzmodus“ aktivieren.
```suggestion
Wenn du (oder ein Benutzer deines Servers) nicht möchte, dass der Serverbesitzer und die Administratoren sehen können, wie viele Nachrichten du
gesendet hast oder du befürchtest, dass personenbezogene Daten über Dich oder deine Nutzer gespeichert werden, kannst du auf SCNX den „Datenschutzmodus“ aktivieren.
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Benutzer, für die der <a href="#user-opt-out">Datenschutzmodus</a> aktiviert ist, werden nicht im Dashboard angezeigt.
```suggestion
        <li>Benutzer, die den <a href="#user-opt-out">Datenschutzmodus</a> aktiviert haben, werden nicht im Dashboard angezeigt.
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +wird sich auf Folgendes auswirken:
```suggestion
Verwende den Befehl `/privacy enable` auf deinem Server. Diese globale Aktion (das bedeutet, dass SCNX auf keinem Server Daten über dich speichert)
wird sich auf folgendes auswirken:
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* Alle Daten über von Dir gesendete Nachrichten werden anonymisiert (= Deine Discord-Benutzer-ID wird aus der Datenbank entfernt)
```suggestion
* Alle Daten über von dir gesendete Nachrichten werden anonymisiert (= Deine Discord-Benutzer-ID wird aus der Datenbank entfernt)
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +- das bedeutet, dass wir nicht wissen, dass *Du* eine Nachricht gesendet hast, sondern nur, dass eine Nachricht gesendet wurde.
```suggestion
 - das bedeutet, dass wir nicht wissen, dass *du* eine Nachricht gesendet hast, sondern nur, dass eine Nachricht gesendet wurde.
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +bedeutet, dass wir nicht wissen, dass *Du* eine Nachricht gesendet hast, sondern nur, dass eine Nachricht gesendet wurde.
```suggestion
* Alle zukünftig von dir gesendeten Nachrichten werden anonymisiert gespeichert (= nicht mit deiner Discord-Benutzer-ID verknüpft) – dies
bedeutet, dass wir nicht wissen, dass *du* eine Nachricht gesendet hast, sondern nur, dass eine Nachricht gesendet wurde.
```

2023-09-10 06:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +Die von dir gesendete wurden (das ist nicht mehr möglich), d. h., dass nur neue Nachrichten in Befehlen und im Dashboard angezeigt werden.
```suggestion
Der Datenschutzmodus kann mit (Opt-Back) mit „/privacy enable“ deaktiviert werden. Bitte beachte, dass dadurch frühere Nachrichten, die von dir gesendet wurden, nicht erneut verknüpft werden 
(das ist nicht mehr möglich), d. h., dass nur neue Nachrichten in Befehlen und im Dashboard angezeigt werden.
```

2023-09-10 09:47 UTC, SCDerox submitted a review, later dismissed
Thank you for your contribution - I've found a few issues, please review them

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +:::tip Der Datenschutz liegt uns am Herzen
```suggestion
:::tip Datenschutz liegt uns am Herzen
```
In this case, this is a header of callout-box

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +# Automatisch löschen
```suggestion
# Automatisches Löschen
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +Diese müssen dann Manuell gelöscht werden.
```suggestion
```

This is not part of the original documentation document and not relevant for this module as this is designed to delete new messages? In addition, this is the introductory sentence and we'll go into this later in the document.

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +  * Füge optional eine Verzögerung vor dem Löschen der Nachricht hinzu
```suggestion
* Lösche Nachrichten in Kanälen nach einer bestimmten Zeit automatisch
  * Optional kannst du immer eine bestimmte Anzahl an Nachrichten in einem Kanal behalten
  * Angepinnte Nachrichten werden nicht gelöscht
* Automatische Löschung von Nachrichten aus Sprachkanälen, nachdem jedes Mitglied den Kanal verlassen hat
  * Füge optional eine Verzögerung vor dem Löschen der Nachrichten hinzu
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +## Setup {#setup}
```suggestion
## Einrichtung {#setup}
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +* Stell sicher, dass Dein Bot über die Berechtigungen „Nachrichten verwalten“, „Kanal anzeigen“ und „Nachrichtenverlauf anzeigen“ für den von Dir verwendeten Kanal verfügt
```suggestion
* Stell sicher, dass dein Bot über die Berechtigungen „Nachrichten verwalten“, „Kanal anzeigen“ und „Nachrichtenverlauf anzeigen“ für den von Dir verwendeten Kanal verfügt
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +  und du die Funktion Aktiviert hast.
```suggestion
```
The is part of a relative sentence to the channel instead of an additional condition in the original file

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +  die [Text-Channels](https://scnx.app/de/glink?page=bot/configuration?file=auto-delete%7Cchannels) Konfigurationsdatei und
```suggestion
  die [Text-Kanäle](https://scnx.app/de/glink?page=bot/configuration?file=auto-delete%7Cchannels) Konfigurationsdatei und
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +  4. Lade Deinen Bot neu, um die Änderungen zu übernehmen.
```suggestion
  4. Lade deinen Bot neu, um die Änderungen zu übernehmen.
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +  die [Voice-Channels](https://scnx.app/de/glink?page=bot/configuration?file=auto-delete%7Cvoice-channels) Konfigurationsdatei und
```suggestion
  die [Sprach-Kanäle](https://scnx.app/de/glink?page=bot/configuration?file=auto-delete%7Cvoice-channels) Konfigurationsdatei und
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +  3. Konfiguriere das Element wie [hier] beschrieben (#config-voice-channels).
```suggestion
  3. Konfiguriere das Element wie [hier](#config-voice-channels) beschrieben.
```
In this case, this is a link and as such direct href value is required after the label. This is in contrast to element ids, these have `{` instead of `(` and do not have a label wrapped in `[`

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +  4. Lade Deinen Bot neu, um die Änderungen zu übernehmen.
```suggestion
  4. Lade deinen Bot neu, um die Änderungen zu übernehmen.
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +Nach einrichten der Konfiguration arbeitet der Bot automatisch im Hintergrund, ohne dass eine Benutzeraktion erforderlich ist. Um Nachrichten
```suggestion
Nach Einrichten der Konfiguration arbeitet der Bot automatisch im Hintergrund, ohne dass Benutzeraktionen erforderlich ist. Um Nachrichten
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +vor dem löschen zu bewahren Pinge sie einfach an.
```suggestion
vor dem Löschen zu bewahren, pinne sie einfach an.
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +Dein [Dashboard](https://scnx.app/de/glink?page=bot/configuration?file=auto-delete%7Cchannels).
```suggestion
sie in deinem [Dashboard](https://scnx.app/de/glink?page=bot/configuration?file=auto-delete%7Cchannels).
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +| Kanal | Dies ist der Kanal, auf den dieser spezifische Befehlssatz angewendet werden soll. In diesem Kanal wird die automatische Löschung durchgeführt. |
```suggestion
| Kanal | Dies ist der Kanal, auf den diese Konfigurationswerte angewendet werden sollen. In diesem Kanal wird die automatische Löschung durchgeführt. |
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +| Zeitüberschreitung | Dies ist die Zeitspanne (in Minuten), nach der an diesen Kanal gesendete Nachrichten automatisch gelöscht werden sollen. Um langsamen Geräten (und langsamen Lesern) gerecht zu
```suggestion
| Timeout | Dies ist die Zeitspanne (in Minuten), nach der an diesen Kanal gesendete Nachrichten automatisch gelöscht werden sollen. Um langsamen Geräten (und langsamen Lesern) gerecht zu werden, empfehlen wir, die Zeit auf über zwei Minuten einzustellen. |
```
This value is called timeout in the dashboard

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +| Beim Start bereinigen | Wenn diese Option aktiviert ist, löscht Ihr Bot automatisch jede Nachricht im Kanal (für den diese Konfigurationsoptionen gelten) beim Neustart Ihres Bots. Wenn deaktiviert,
```suggestion
| Kanal beim Start leeren | Wenn diese Option aktiviert ist, löscht dein Bot automatisch jede Nachricht im Kanal (für den diese Konfigurationsoptionen gelten) beim Neustart deines Bots. Wenn deaktiviert, werden keine vorhandenen Nachrichten gelöscht. Aufgrund einer Einschränkung seitens Discord kann der Bot nur bis zu 100 Nachrichten auf einmal löschen und keine Nachrichten löschen, die älter als 14 Tage sind. |
```
Please review automatic translations before positing them.

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +| Die maximale Zeit die Du einstellen kannst ist also - 18720 Minuten, das sind 13 Tage |
```suggestion
```
This is not part of the original document and wrongly formatted markdown

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +| Anzahl der aufzubewahrenden Nachrichten | Wenn diese Option aktiviert ist, ist diese Anzahl an Nachrichten immer von der automatischen Löschung ausgenommen. Die neuesten Nachrichten bleiben immer e
```suggestion
| Anzahl von zu behaltenden Nachrichten | Wenn diese Option aktiviert ist, wird diese Anzahl an Nachrichten immer von der automatischen Löschung ausgenommen. Die neuesten Nachrichten bleiben immer erhalten, d. h. sobald mehr als x Nachrichten in diesen Kanal gesendet werden, löscht der Bot die älteste. Diese Zahl muss unter 50 liegen. |
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +sobald alle Benutzer den Sprachkanal verlassen haben.
```suggestion
Mit dieser Konfigurationsdatei kannst du einstellen, von welchen Kanälen Nachrichten automatisch gelöscht werden sollen, sobald alle Benutzer den Sprachkanal verlassen haben.
```
Please review correct syntax before publishing.

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +Öffne Dein [Dashboard](https://scnx.app/de/glink?page=bot/configuration?file=auto-delete%7Cvoice-channels).
```suggestion
Du kannst diese Datei in deinem [Dashboard](https://scnx.app/de/glink?page=bot/configuration?file=auto-delete%7Cvoice-channels) öffnen.
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +| Kanal | Dies ist der Kanal, auf den dieser spezifische Befehlssatz angewendet werden soll. Die automatische Löschung wird in diesem Kanal durchgeführt, sobald alle Mitglieder den Kanal verlassen ha
```suggestion
| Kanal | Dies ist der Kanal, auf den diese Konfigurationswerte angewendet werden sollen. Die automatische Löschung wird in diesem Kanal durchgeführt, sobald alle Mitglieder den Kanal verlassen haben. |
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +| Zeitüberschreitung | Dies ist die Verzögerung (in Minuten) zwischen dem letzten Verlassen des Kanals durch den Benutzer und der Durchführung des Löschvorgangs. Setzen Sie diesen Wert auf Null, um d
```suggestion
| Timeout | Dies ist die Verzögerung (in Minuten) zwischen dem letzten Verlassen des Kanals durch den Benutzer und der Durchführung des Löschvorgangs. Setzen Sie diesen Wert auf Null, um sofort bei Verlassen die Löschung durchzuführen. |
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +| Beim Start bereinigen | Wenn diese Option aktiviert ist, löscht Ihr Bot beim Neustart Ihres Bots jede Nachricht, wenn kein Mitglied im Sprachkanal vorhanden ist. Wenn deaktiviert, werden keine vorh
```suggestion
| Kanal beim Start leeren | Wenn diese Option aktiviert ist, löscht dein Bot beim Neustart deines Bots jede Nachricht, wenn kein Mitglied im Sprachkanal ist. Wenn deaktiviert, werden keine vorhandenen Nachrichten gelöscht. |
```

2023-09-10 09:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +* Bitte stell sicher, dass die Nachricht, die Du löschen möchten, nicht angepinnt ist.
```suggestion
* Bitte stell sicher, dass die Nachricht, die du löschen möchtest, nicht angepinnt ist.
```

2023-09-10 11:54 UTC, patricksynced reviewed
Habe ich gefixt und die Dateien Aktualisiert, sollten noch Fehler vorhanden sein. Bitte bescheid sagen !
Have Fixed and Refresh, find Faile new or againe pls report !

2023-09-10 12:07 UTC, patricksynced reviewed
Have fixed

2023-09-10 12:25 UTC, patricksynced reviewed
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +Diese müssen dann Manuell gelöscht werden.
fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +  * Füge optional eine Verzögerung vor dem Löschen der Nachricht hinzu
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +## Setup {#setup}
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +* Bitte stell sicher, dass die Nachricht, die Du löschen möchten, nicht angepinnt ist.
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +| Beim Start bereinigen | Wenn diese Option aktiviert ist, löscht Ihr Bot beim Neustart Ihres Bots jede Nachricht, wenn kein Mitglied im Sprachkanal vorhanden ist. Wenn deaktiviert, werden keine vorh
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +| Zeitüberschreitung | Dies ist die Verzögerung (in Minuten) zwischen dem letzten Verlassen des Kanals durch den Benutzer und der Durchführung des Löschvorgangs. Setzen Sie diesen Wert auf Null, um d
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +  und du die Funktion Aktiviert hast.
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +* Stell sicher, dass Dein Bot über die Berechtigungen „Nachrichten verwalten“, „Kanal anzeigen“ und „Nachrichtenverlauf anzeigen“ für den von Dir verwendeten Kanal verfügt
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +:::tip Der Datenschutz liegt uns am Herzen
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +# Serveranalyse
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +für weitere Informationen folgendes durch [FAQ-Artikel](https://faq.scnx.app/de/data-collection-with-analytics/).
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +[Benutzer können sich abmelden](#user-opt-out) und es werden niemals Inhalte von Nachrichten (oder Anhängen) gespeichert.
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +## Analyse aktivieren {#enable}
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +„Analyse aktivieren“.
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +In deinem [Analyse-Dashboard](https://scnx.app/de/glink?page=analytics) kannst du die folgenden Daten basierend eines Zeitrahmens sehen, den Du oben in deinem Dashboard auswählen kannst:
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* Nachrichten und Befehle: Du siehst ein Diagramm, das zeigt, wie viele Nachrichten und Befehle an jedem Tag im Zeitrahmen gesendet wurden.
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* 10 am häufigsten verwendete Kanäle: Dies ist eine Grafik, die zeigt, wie viel Prozent der Nachrichten über welchen Kanal gesendet wurden.
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* Aktivste Benutzer: Das sind die 15. aktivsten Nutzer (die den [Datenschutzmodus] (#user-opt-out) nicht aktiviert haben).
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* Mitgliederaktivität (immer letzten 30 Tage): Hier wird die Anzahl der Bots, Benutzer und aktive Mitglieder an jedem Tag im Zeitrahmen angezeigt.
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* Aktivste Stunden am Tag: Diese Grafik zeigt, wie viele Nachrichten durchschnittlich zu welcher Zeit auf Ihrem Server gesendet wurden.
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* Zusammenfassung: In diesem Abschnitt erhalten Sie einen schnellen Überblick über Ihren Server. Es umfasst folgende Daten:
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* Anzahl der Bots auf Ihrem Server
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* „/stats user“: Zeigt eine Statistikübersicht aller Benutzer auf deinem Server an. Dazu gehören die 10 aktivsten Kanäle (und die Anzahl der darin gesendeten Nachrichten) sowie ein Abschnitt „Zusamme
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +Tage. Benutzer, die den [Datenschutzmodus] (#user-opt-out) aktiviert haben, können diesen Befehl nicht verwenden (/ zeigt Daten darüber an).
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Bitte stell sicher, dass der (verifizierte) SCNX-Bot berechtigt ist, den Kanal anzuzeigen, über den die Nachricht gesendet wurden.
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +            das Ergebnis im Dashboard generiert wurde ( dies wird oben auf der Seite angezeigt und sollte wie folgt aussehen: „Diese Zusammenfassung wurde
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Versuche, das Analyse-Dashboard in ein paar Minuten zu aktualisieren.</li>
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Benutzer, für die der <a href="#user-opt-out">Datenschutzmodus</a> aktiviert ist, werden nicht im Dashboard angezeigt.
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Versuche, das Analyse-Dashboard in ein paar Minuten zu aktualisieren.</li>
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        ^^" Warnung in deinem Dashboard
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Benutzer, für die der <a href="#user-opt-out">Datenschutzmodus</a> aktiviert ist, werden nicht im Dashboard angezeigt.
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Stell sicher, dass Du einen ausreichenden Zeitrahmen ausgewählt hast (z. B. „Letzte 30 Tage“ statt „Letzten 24 Stunden“).</li>
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Bitte stell sicher, dass der (verifizierte) SCNX-Bot berechtigt ist, auf den Kanal zuzugreifen und den Nachrichtenverlauf sehen kann, über den die Nachrichten gesendet wurden.
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Stell sicher, dass SCNX mindestens einen Kanal auf deinem Server sehen und zugreifen kann.</li>
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +Alle infos findest Du unter [FAQ-Artikel](https://faq.scnx.app/de/data-collection-with-analytics/).
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +gesendet hast oder Du befürchtest, dass personenbezogene Daten über Dich oder deine Nuztzer gespeichert werden, kannst du auf SCNX den „Datenschutzmodus“ aktivieren.
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +wird sich auf Folgendes auswirken:
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* Alle Daten über von Dir gesendete Nachrichten werden anonymisiert (= Deine Discord-Benutzer-ID wird aus der Datenbank entfernt)
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +- das bedeutet, dass wir nicht wissen, dass *Du* eine Nachricht gesendet hast, sondern nur, dass eine Nachricht gesendet wurde.
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +bedeutet, dass wir nicht wissen, dass *Du* eine Nachricht gesendet hast, sondern nur, dass eine Nachricht gesendet wurde.
Fixed

2023-09-10 12:25 UTC, patricksynced commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +Die von dir gesendete wurden (das ist nicht mehr möglich), d. h., dass nur neue Nachrichten in Befehlen und im Dashboard angezeigt werden.
Fixed

2023-09-10 16:11 UTC, SCDerox reviewed
these some issues I found

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +
```suggestion
dich auch an unsere Mitarbeiter (https://scnx.app/de/help) wenden, um das Geld schneller zurückzubekommen (bitte beachte, dass dies nur möglich ist),
wenn dein Guthaben bei uns noch nicht verwenden worden ist).

```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +   * [Revolut](https://help.revolut.com/de-LU/help/receiving-zahlungen/sending-money-to-an-external-bank-account/how-to-schedule-recurring-zahlungen/business /)
```suggestion
   * [Revolut](https://help.revolut.com/de-LU/help/receiving-zahlungen/sending-money-to-an-external-bank-account/how-to-schedule-recurring-zahlungen/business/)
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +Bitte [kontaktieren unsere Mitarbeiter](https://scnx.app/de/help), wenn Du der Meinung bist, dass keiner dieser Gründe zutrifft.
```suggestion
Bitte [kontaktieren unser Team](https://scnx.app/de/help), wenn du der Meinung bist, dass keiner dieser Gründe zutrifft.
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +### Erforderliche Bereiche für Discord {#discord-access}
```suggestion
### Erforderliche Zugriffsrechte auf deinen Discord-Account {#discord-access}
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +Um SCNX nutzen zu können, musst Du einen bestimmten Zugriff auf Dein Discord-Konto autorisieren.
```suggestion
Um SCNX nutzen zu können, musst du einen bestimmten Zugriff auf Dein Discord-Konto autorisieren. 
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +Unser Zugriff ist streng eingeschränkt, wir verstehen jedoch, dass Du möglicherweise Bedenken hast, personenbezogene Daten an Dritte weiterzugeben.
```suggestion
Unser Zugriff ist streng eingeschränkt, wir verstehen jedoch, dass du möglicherweise Bedenken hast, personenbezogene Daten an Dritte weiterzugeben. 
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +Hier findest Du eine Erklärung, warum wir welchen Umfang benötigen.
```suggestion
Hier findest du eine Erklärung, warum wir welchen Zugriff benötigen.
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +:::tipp
```suggestion
:::tip
```
This is not translatable

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +| Geltungsbereich | Erklärung |
```suggestion
| Zugriffsrecht | Erklärung |
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +| Greifen auf Deinen Benutzernamen, Deinen Avatar und Dein Banner zu | Wir benötigen diese Informationen, um Dich zu identifizieren und das Dashboard auszuführen. Wir zeigen beispielsweise Dein Profi
```suggestion
| Zugriff auf deinen Benutzernamen, Avatar und Banner | Wir benötigen diese Informationen, um dich zu identifizieren und das Dashboard anzubieten. Wir zeigen beispielsweise dein Profilbild im Dashboard an. |
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +| Zugriff auf E-Mail-Adresse | Dies ist erforderlich, um Dir Rechnungen und rechtliche Informationen (z. B. Richtlinienänderungen) zu senden. Wir sind kein bestimmter Big Bot mit blauem Profilbild un
```suggestion
| Auf deine E-Mail-Adresse zugreifen| Dies ist erforderlich, um dir Rechnungen und rechtliche Informationen (z. B. Richtlinienänderungen) zu senden. Wir sind kein bestimmter großer Bot mit blauem Profilbild und werden dir niemals Marketing-E-Mails senden. |
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +| Wusstest Du, auf welchen Servern Du dich befindedst | Im Dashboard zeigen wir alle Server an, auf die Du Zugriff hast. Damit dies funktioniert, müssen wir wissen, auf welchen Servern Du sich derzei
```suggestion
| Wissen, auf welchen Servern du bist | Im Dashboard zeigen wir alle Server an, auf die du Zugriff hast. Damit dies funktioniert, müssen wir wissen, auf welchen Servern du dich derzeit befindest. |
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +Verwalte deine Partnerschaften mit anderen Servern ganz einfach.
```suggestion
Erstelle eine Liste mit allen Partnern deines Servers - nach Kategorie sortiert.
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +* Erstelle stets eine aktuelle Einbettungsliste von all deinen aktuellen Partner´n.
```suggestion
* Erstelle stets eine aktuelle Embed-Liste von all deinen aktuellen Partnern.
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +* Rollen von Partnern automatisch zuweisen und entfernen.
```suggestion
* Weiße und entferne automatisch Rollen von Partnern.
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +* Sende deinen Partner´n automatisch eine Benachrichtigungen über Statusänderungen.
```suggestion
* Sende deinen Partnern automatisch eine Benachrichtigungen über Änderungen ihres Partner-Statuses.
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +Hier ist ein Beispiel einer Partnerliste (Du kannst das Erscheinungsbild anpassen):
```suggestion
Hier ist ein Beispiel einer Partnerliste (du kannst das Erscheinungsbild anpassen):
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +* Anschließend konfigurierst Due die Partnerliste:
```suggestion
* Konfiguriere anschließlich die Partnerliste:
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +    1. Erstell einen Kanal, in den der Bot die Partnerliste senden soll. Dieser Kanal muss leer sein, und der Bot muss über die Berechtigungen
```suggestion
    1. Erstelle einen Kanal, in den der Bot die Partnerliste senden soll. Dieser Kanal muss leer sein, und der Bot muss über die Berechtigungen
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +       und [Modul konfigurieren](#configuration).
```suggestion
       und [konfiguriere das Modul](#configuration).
```

2023-09-10 16:11 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +    4. Lade die Konfiguration Deines Bots neu, um die Änderungen zu übernehmen – der Bot sendet automatisch eine Partnerliste.
```suggestion
    4. Lade die Konfiguration deines Bots neu, um die Änderungen zu übernehmen – der Bot sendet automatisch eine Partnerliste.
```

2023-09-10 16:35 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +Bitte [kontaktieren unsere Mitarbeiter](https://scnx.app/de/help), wenn Du der Meinung bist, dass keiner dieser Gründe zutrifft.
I think it's "kontaktiere"

2023-09-12 17:17 UTC, patricksynced reviewed
fixed

2023-09-12 17:21 UTC, patricksynced reviewed
fixed

2023-09-12 19:47 UTC, patricksynced reviewed
fixed

2023-09-12 20:18 UTC, Fridolin012 reviewed
I suggested some changes for partner-list.md

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +    2. „Kanal anzeigen“, „Nachrichtenverlauf anzeigen“ und „Nachricht senden“ verfügen.
```suggestion
    1. Erstelle einen Kanal, in den der Bot die Partner-Liste senden soll. Dieser Kanal muss leer sein, und der Bot muss über die Berechtigungen „Kanal anzeigen“, „Nachrichtenverlauf anzeigen“ und „Nachrichten senden“ verfügen.
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +| `/partner add name:<Text> category:<Category> owner:<Member> invite-url:<Text>` | Erstellt einen neuen Partner. Du kannst einen beliebigen Text als Namen des Partners eingeben und eine beliebige UR
```suggestion
| `/partner add name:<Text> category:<Kategorie> owner:<Mitglied> invite-url:<Text>` | Erstellt einen neuen Partner. Du kannst einen beliebigen Text als Namen des Partners eingeben, eine beliebige URL als Einladungs-URL verlinken und eine Kategorie aus den [konfigurierten Kategorien] auswählen (#configuration). Wenn die Option aktiviert ist, wird eine Nachricht an den Partner gesendet. |
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +| `/partner edit id:<PartnerID> [name:<Text>] [category:<Category>] [owner:<Member>] [invite-url:<Text>] [staff:<Member>]` | Bearbeitet einen vorhandenen Partner. Du kannst den Namen, die Einladungs-
```suggestion
| `/partner edit id:<PartnerID> [name:<Text>] [category:<Kategorie>] [owner:<Mitglied>] [invite-url:<Text>] [staff:<Mitglied>]` | Bearbeitet einen vorhandenen Partner. Du kannst den Namen, die Einladungs-URL, den Besitzer, die Kategorie und das zugewiesenen Teammitglied aktualisieren – nur die von dir angegebenen Optionen werden aktualisiert. Du kannst entweder eine ID eines bestehenden Partners eingeben oder die automatische Vervollständigung nutzen, um den richtigen Partner auszuwählen. |
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +deinem [Dashboard](https://scnx.app/de/glink?page=bot/configuration?file=partner-list%7Cconfig).
```suggestion
Öffne die Konfigurationsdatei in
deinem [Dashboard](https://scnx.app/de/glink?page=bot/configuration?file=partner-list%7Cconfig).
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +| Partner-Liste-Einbetten | Dies ist die Konfiguration der Partner-Liste. |
```suggestion
| Partner-Liste einbetten | Dies ist die Konfiguration der Partner-Liste. |
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +| Partner-Liste-Embed: Titel | Titel der Partner-List-Embed. |
```suggestion
| Partner-Liste-Embed: Titel | Titel des Partner-Listen-Embeds. |
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +| Partner-Liste-Embed: Beschreibung | Beschreibung der Partner-List-Embed. |
```suggestion
| Partner-Liste-Embed: Beschreibung | Beschreibung des Partner-Listen-Embeds. |
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +        <li>Stell sicher, dass du in der Konfiguration einen <a href="./../../additional-features#embed-colors">richtigen Farbwert</a> angegeben hast.</li>
```suggestion
        <li>Stelle sicher, dass der gewünschte Kanal leer ist.</li>
        <li>Stelle sicher, dass der Bot über die Berechtigungen „Kanal anzeigen“, „Nachrichten senden“ und „Nachrichtenverlauf anzeigen“ für den Kanal verfügt.</li>
        <li>Stelle sicher, dass keiner deiner Kategoriefelder leer ist.</li>
        <li>Stelle sicher, dass du in der Konfiguration einen <a href="./../../additional-features#embed-colors">richtigen Farbwert</a> angegeben hast.</li>
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +        <li>Starte Deinen Bot neu.</li>
```suggestion
        <li>Starte deinen Bot neu.</li>
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +* Konfiguriere anschließlich die Partnerliste:
```suggestion
* Konfiguriere anschließend die Partner-Liste:
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +    4. Lade die Konfiguration deines Bots neu, um die Änderungen zu übernehmen – der Bot sendet automatisch eine Partnerliste.
```suggestion
    4. Lade die Konfiguration deines Bots neu, um die Änderungen zu übernehmen – der Bot sendet automatisch eine Partner-Liste.
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +| Partner-Entfernung-DM | <i>Nur sichtbar, wenn „Partnerbenachrichtigungen senden“ aktiviert ist.</i><br/>Diese Nachricht wird an Partner gesendet, wenn dieser entfernt wird. |
```suggestion
| Partner-Entfernung-PN | <i>Nur sichtbar, wenn „Partner-Benachrichtigung senden“ aktiviert ist.</i><br/>Diese Nachricht wird an Partner gesendet, wenn dieser entfernt wird. |
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +| Partner-Willkommen-DM | <i>Nur sichtbar, wenn „Partnerbenachrichtigungen senden“ aktiviert ist.</i><br/>Diese Nachricht wird an Partner gesendet, wenn dieser hinzugefügt wird. |
```suggestion
| Partner-Willkommens-PN | <i>Nur sichtbar, wenn „Partner-Benachrichtigung senden“ aktiviert ist.</i><br/>Diese Nachricht wird an Partner gesendet, wenn dieser hinzugefügt wird. |
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +| Partner-Benachrichtigungen senden | Wenn diese Option aktiviert ist, wird den Partnern eine Nachricht gesendet, wenn sie hinzugefügt oder entfernt werden. |
```suggestion
| Partner-Benachrichtigung senden | Wenn diese Option aktiviert ist, wird den Partnern eine Nachricht gesendet, wenn sie hinzugefügt oder entfernt werden. |
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +| Partner-Liste-Embed: Farbe | Dies ist die Farbe der Partner-List-Embed. Es muss eine [HEX-Farbe oder ein unterstützter Farbwert] sein (./../../additional-features#embed-colors). |
```suggestion
| Partner-Liste-Embed: Farbe | Dies ist die Farbe der Partner-Listen-Embeds. Es muss eine [HEX-Farbe oder ein unterstützter Farbwert] sein (./../../additional-features#embed-colors). |
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +| Partner-Liste-Embed: Partner-String | Dies ist das Format eines Partners, der in der Partner-Liste-Embed angezeigt wird. Verfügbare Parameter findest du im [Dashboard](https://scnx.app/de/glink?pag
```suggestion
| Partner-Liste-Embed: Partner-String | Dies ist das Format eines Partners, der in dem Partner-Listen-Embed angezeigt wird. Verfügbare Parameter findest du im [Dashboard](https://scnx.app/de/glink?page=bot/configuration?file=partner-list%7Cconfig). |
```

2023-09-12 20:18 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +| Partner-Liste-Einbetten | Dies ist die Konfiguration der Partner-Liste. |
```suggestion
| Partner-Liste-Embed | Dies ist die Konfiguration der Partner-Liste. |
```

2023-10-08 11:19 UTC, patricksynced reviewed
fixed

2023-10-08 11:28 UTC, patricksynced reviewed
fixed

2023-10-08 11:59 UTC, Fridolin012 requested changes

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +Kontaktiere bitte einen [unser Team](https://scnx.app/de/help).
```suggestion
kontaktiere bitte [unser Team](https://scnx.app/de/help).
```

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +   Fenster. Wähle als Nächstes dein Zahlungsintervall und deinen Zahlungsplan aus. Wenn du nach einer Zahlungsmethode gefragt wirst, wähle bitte „Wiederkehrend Banküberweisung“ aus
```suggestion
1. Aktiviere zunächst das Abonnement auf SCNX. Öffne dazu
      die [Zahlungsseite](https://scnx.app/de/glink?page=pricing?showUpgradeModal=true) deines Servers und öffne das Upgrade
   Fenster. Wähle als Nächstes dein Zahlungsintervall und deinen Zahlungsplan aus. Wenn du nach einer Zahlungsmethode gefragt wirst, wähle bitte „Wiederkehrende Banküberweisung“ aus
```

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +   * [Revolut](https://help.revolut.com/de-LU/help/receiving-zahlungen/sending-money-to-an-external-bank-account/how-to-schedule-recurring-zahlungen/business/)
Externe Links können nicht mitübersetzt werden - bitte ändere sie zurück.

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +3. Stell sicher, dass alle Details mit denen, in deinem Dashboard angezeigten Details übereinstimmen, und bestätige deine wiederkehrende Überweisung von deiner
```suggestion
3. Stell sicher, dass alle Details mit denen, in deinem Dashboard angezeigten Details übereinstimmen, und bestätige deine wiederkehrende Überweisung bei deiner
```

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +auf diesem Konto wird deiner Rechnungen gutgeschrieben – die Angabe der Transaktionsreferenz ist nicht erforderlich (wird jedoch empfohlen bei Einmalkäufen empfohlen), da wir anhand der IBAN, auf der
```suggestion
Wenn du per Banküberweisung bezahlst, wird dir eine individuelle IBAN auf einem virtuellen Bankkonto zugewiesen. Jede Zahlung, die auf diesem Konto eintrifft, wird deinen Rechnungen gutgeschrieben – die Angabe der Transaktionsreferenz ist nicht erforderlich (wird jedoch empfohlen bei Einmalkäufen empfohlen), da wir anhand der IBAN, auf der das Geld eingegangen ist, eine Zahlung problemlos deinem Konto zuordnen können.
```

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +Durch einen Unfall zu viel Geld verdrahtet? Keine Sorge: Dein Geld wird automatisch für zukünftige Zahlungen verwendet.
```suggestion
Durch einen Unfall zu viel Geld verschickt? Keine Sorge: Dein Geld wird automatisch für zukünftige Zahlungen verwendet.
```

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +von (falls dies nicht möglich ist, wird sich Stripe mit dir in Verbindung setzen und nach den Bankdaten fragen). Du kannst
```suggestion
 (falls dies nicht möglich ist, wird sich Stripe mit dir in Verbindung setzen und nach den Bankdaten fragen). Du kannst
```

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +wenn dein Banküberweisungssaldo nicht abgeglichen ist).
Hier fehlen Teile der Dokumentation.

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +| Wir greifen auf deinen Benutzernamen, deinen Avatar und dein Banner zu | Wir benötigen diese Informationen, um dich zu identifizieren und diese Informationen im auszuführen. Wir zeigen beispielswei
```suggestion
| Wir greifen auf deinen Benutzernamen, deinen Avatar und dein Banner zu | Wir benötigen diese Informationen, um dich zu identifizieren und diese Informationen im Dashboard auszuführen. Wir zeigen beispielsweise dein Profilbild im Dashboard an |
```

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +| Wusstest du, auf welchen Servern du dich befindedst | Im Dashboard zeigen wir alle Server an, auf die du Zugriff hast. Damit dies funktioniert, müssen wir wissen, auf welchen Servern du dich derzei
```suggestion
| Wissen, auf welchen Servern du dich befindest | Im Dashboard zeigen wir alle Server an, auf die du Zugriff hast. Damit dies funktioniert, müssen wir wissen, auf welchen Servern du dich derzeit befindest. |
```

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +Schau dir die Mitgliederaktivität an und erhalte eine Prognosen für die Zukunft 🔮
```suggestion
Schau dir die Mitgliederaktivität an und erhalte Prognosen für die Zukunft 🔮
```

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* Anzahl der aktiven Mitglieder auf deinen Server (ausgenommen Benutzer, die den [Datenschutzmodus] nicht aktiviert haben (#user-opt-out))
```suggestion
* Anzahl der aktiven Mitglieder auf deinen Server (ausgenommen Benutzer, die den [Datenschutzmodus] aktiviert haben (#user-opt-out))
```

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +*Bitte beachte, dass einige dieser Teile je nach Zeitrahmen möglicherweise nicht verfügbar sind.*
```suggestion
*Bitte beachte, dass einige dieser Teile je nach Zeitraum möglicherweise nicht verfügbar sind.*
```

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +letzten 30 Tagen und einen Abschnitt mit einer „Zusammenfassung“, in der Sie die Gesamtzahl der Nachrichten und Befehle in den letzten 30 Tagen finden.
```suggestion
letzten 30 Tagen und einen Abschnitt mit einer „Zusammenfassung“, in der du die Gesamtzahl der Nachrichten und Befehle in den letzten 30 Tagen findest.
```

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +         <li>Bitte stelle sicher, dass der (verifizierte) SCNX-Bot berechtigt ist, den Kanal anzuzeigen, in den die Nachricht gesendet wurden.
```suggestion
         <li>Bitte stelle sicher, dass der (verifizierte) SCNX-Bot berechtigt ist, den Kanal zu sehen, in den die Nachricht gesendet wurden.
```

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +        <li>Stell sicher, dass der Benutzer eine Nachricht an einen Kanal gesendet hat, auf den der (verifizierte) SCNX-Bot zugriff hat.</li>
```suggestion
        <li>Stelle sicher, dass der Benutzer eine Nachricht in einen Kanal gesendet hat, auf den der (verifizierte) SCNX-Bot Zugriff hat.</li>
```

2023-10-08 11:59 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +            generiert um 11:30:28 Uhr").
```suggestion
             das Ergebnis im Dashboard generiert wurde (dies wird oben auf der Seite angezeigt und sollte wie folgt aussehen: „Diese Zusammenfassung wurde frisch für dich
            um 11:30:28 Uhr generiert").
```

2023-10-09 14:50 UTC, Fridolin012 requested changes

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +     <summary>Ich sehe die Meldung „Es gibt nicht viele Nachrichten im ausgewählten Zeitraum, daher sehen deine Diagramme möglicherweise etwas seltsam aus. ^^"  im Dashboard
```suggestion
     <summary>Ich sehe die Meldung „Es existieren nur wenige Nachrichten im gewählten Zeitraum, deswegen können einige Diagramme merkwürdig aussehen ^^"  im Dashboard
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> + - das bedeutet, dass wir nicht wissen, dass *du* eine Nachricht gesendet hast, sondern nur, dass eine Nachricht gesendet wurde.
```suggestion
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +Der Datenschutzmodus kann mit (Opt-Back) mit „/privacy enable“ deaktiviert werden. Bitte beachte, dass dadurch frühere Nachrichten, die von dir gesendet wurden, nicht erneut verknüpft werden
```suggestion
Der Datenschutzmodus kann mit (Opt-Back) mit `/privacy disable` deaktiviert werden. Bitte beachte, dass dadurch frühere Nachrichten, die von dir gesendet wurden, nicht erneut verknüpft werden 
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +* Stell sicher, dass dein Bot über die Berechtigungen „Nachrichten verwalten“, „Kanal anzeigen“ und „Nachrichtenverlauf anzeigen“ für den von dir verwendeten Kanal verfügt
```suggestion
* Stelle sicher, dass dein Bot über die Berechtigungen „Nachrichten verwalten“, „Kanal anzeigen“ und „Nachrichtenverlauf anzeigen“ für den von dir verwendeten Kanal verfügt
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +  1. Klick auf „Neues Konfigurationselement hinzufügen“.
```suggestion
  1. Klicke auf „Neues Konfigurationselement hinzufügen“.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +* Um das automatische Löschen von Nachrichten in Sprachkanälen einzurichten, nachdem jeder Benutzer den Kanal verlassen hat, öffnen
```suggestion
* Um das automatische Löschen von Nachrichten in Sprachkanälen einzurichten, nachdem jeder Benutzer den Kanal verlassen hat, öffne
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +  1. Klick auf „Neues Konfigurationselement hinzufügen“.
```suggestion
  1. Klicke auf „Neues Konfigurationselement hinzufügen“.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +vor dem Löschen zu bewahren, pinne sie einfach an.
```suggestion
vor dem Löschen zu schützen, pinne sie einfach an.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +Mit dieser Konfigurationsdatei kannst du festlegen, von welchen Kanälen Nachrichten automatisch gelöscht werden sollen. Öffnen
```suggestion
Mit dieser Konfigurationsdatei kannst du festlegen, von welchen Kanälen Nachrichten automatisch gelöscht werden sollen. Öffne
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +| Timeout | Dies ist die Zeitspanne (in Minuten), nach der an diesen Kanal gesendete Nachrichten automatisch gelöscht werden sollen. Um langsamen Geräten (und langsamen Lesern) gerecht zu werden, emp
```suggestion
| Timeout | Dies ist die Zeitspanne (in Minuten), nach der in diesen Kanal gesendete Nachrichten automatisch gelöscht werden sollen. Um langsamen Geräten (und langsamen Lesern) gerecht zu werden, empfehlen wir, die Zeit auf über zwei Minuten einzustellen. |
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +| Anzahl von zu behaltenden Nachrichten | Wenn diese Option aktiviert ist, wird diese Anzahl an Nachrichten immer von der automatischen Löschung ausgenommen. Die neuesten Nachrichten bleiben immer er
```suggestion
| Anzahl von zu behaltenden Nachrichten | Wenn diese Option aktiviert ist, wird diese Anzahl an Nachrichten immer von der automatischen Löschung ausgenommen. Die neuesten Nachrichten bleiben immer erhalten, d. h. sobald mehr als x Nachrichten in diesen Kanal gesendet werden, löscht der Bot die ältesten. Diese Zahl muss unter 50 liegen. |
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +* Dein Bot benötigt folgende Rechte auf deinem Kanal: „Kanal anzeigen“, „Nachrichten verwalten“, „Nachrichtenverlauf anzeigen“, auf dem die Automatische Löschung durchgeführt werden soll.
```suggestion
* Dein Bot benötigt folgende Rechte auf den Kanal, in dem die automatische Löschung durchgeführt werden soll: „Kanal anzeigen“, „Nachrichten verwalten“, „Nachrichtenverlauf anzeigen“.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /auto-delete.md
> +* Bitte stell sicher, dass die Nachricht, die du löschen möchtes, nicht angepinnt ist.
```suggestion
* Bitte stelle sicher, dass die Anzahl der zu behaltenden Nachrichten unter 50 liegt.
* Bitte stelle sicher, dass neue Nachrichten in den Kanal gesendet wurden, wenn du „Kanal beim Start leeren“ nicht aktiviert hast.
* Bitte stelle sicher, dass die Nachricht, die du löschen möchtest, nicht angepinnt ist.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +# Erweiterte Protokollierung
```suggestion
# Fortgeschrittenes Logging
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +Lass deinen Bot alle Änderungen an deinem Sever und deinen Kanälen Protokollieren.
```suggestion
Lass deinen Bot alle Änderungen an deinem Sever und deinen Kanälen protokollieren.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +Mit dem erweiterten Protokollierungsmodul kannst du dies ganz einfach tun
```suggestion
Mit dem Fortgeschrittenes Logging-Modul kannst du folgendes ganz einfach tun:
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +* Protokolliere Mitgliederaktualisierungen (wie Spitznamen- oder Rollenänderungen und mehr) in jedem gewünschten Kanal.
```suggestion
* Protokolliere Mitgliederaktualisierungen (wie Nicknamen- oder Rollenänderungen und mehr) in jedem gewünschten Kanal.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +* Protokolliere Voice-Channel-Updates (z. B. Mitglieder, die dem Kanal beitreten oder ihn verlassen) in jedem gewünschten Kanal.
```suggestion
* Protokolliere Sprachkanalaktualisierungen (z. B. Mitglieder, die dem Kanal beitreten oder ihn verlassen) in jedem gewünschten Kanal.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +* Protokolliere Emoji-Änderungen (wie das Hochladen, Bearbeiten oder Löschen von Emojis und Aufklebern) in jedem gewünschten Kanal.
```suggestion
* Protokolliere Emoji-Änderungen (wie das Hochladen, Bearbeiten oder Löschen von Emojis und Stickern) in jedem gewünschten Kanal.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +1. Erstelle einen Kanal, in dem der Bot Änderungen protokollieren soll. Stell sicher, dass der Bot über die Berechtigungen „Nachrichten senden“ und „Kanal anzeigen“ verfügt.
```suggestion
1. Erstelle einen Kanal, in dem der Bot Änderungen protokollieren soll. Stelle sicher, dass der Bot über die Berechtigungen „Nachrichten senden“ und „Kanal anzeigen“ verfügt.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +2. Stell sicher, dass dein Bot über die erforderlichen Berechtigungen auf deinem Server verfügt („Überwachungsprotokoll anzeigen“). Wenn Du Nachrichtenaktualisierungen protokollieren möchten, benötig
```suggestion
2. Stell sicher, dass dein Bot über die erforderlichen Berechtigungen auf deinem Server verfügt („Audit-Log einsehen“). Wenn du Nachrichtenaktualisierungen protokollieren möchten, benötigt der Bot die Berechtigungen „Kanal anzeigen“ und „Nachrichtenverlauf anzeigen“ auf jedem Kanal, von dem der Bot Änderungen dokumentieren soll.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +3. Öffne die [Erweiterte Protokollierungskonfiguration](https://scnx.app/de/glink?page=bot/configuration?file=logging%7Cconfig)
```suggestion
3. Öffne die [Fortgeschrittene Loggingskonfiguration](https://scnx.app/de/glink?page=bot/configuration?file=logging%7Cconfig)
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +   und [Modul konfigurieren](#configuration).
```suggestion
   und [konfiguriere das Modul](#configuration).
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +Es sind keine weiteren Maßnahmen erforderlich.
```suggestion
Es sind keine weiteren Aktionen erforderlich.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +(oder mithilfe der Funktion [Als Bot anmelden](./../../login-as-bot)-Bearbeiten und Fälschen ) können. Dies ist mit dem Discord-Audit-Log nicht möglich.
```suggestion
(oder mithilfe der Funktion [Als Bot anmelden](./../../login-as-bot) bearbeiten und fälschen ) können. Dies ist mit dem Discord-Audit-Log nicht möglich. 
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +Wenn du also sicherstellen möchten, dass eine Aktion korrekt ist, überprüfe bitte das Discord-Audit-Protokoll.
```suggestion
Wenn du also sicherstellen möchten, dass eine Aktion korrekt ist, überprüfe bitte den Discord-Audit-Log.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +Öffne dein Dashboard [Dashboard](https://scnx.app/de/glink?page=bot/configuration?file=logging%7Cconfig).
```suggestion
Öffne sie in deinem [Dashboard](https://scnx.app/de/glink?page=bot/configuration?file=logging%7Cconfig).
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +| Gilden-Updates | Wenn diese Option aktiviert ist, protokolliert der Bot Änderungen auf Ihrem Server (z. B. Servereinstellungen und mehr). |
Please do not use a translator, but rather the terms from the SCNX dashboard.

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +| Bots ignorieren | <i>Diese Funktion ist immer für Server ohne <a href="./../../../scnx/guilds/plans">PRO-Plan</a> aktiviert.</i><br/ >Wenn deaktiviert, dokumentiert der Bot von ihm selbst oder ande
Please do not use a translator, but rather the terms from the SCNX dashboard.

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +Wenn Änderungen nicht protokolliert werden, stell bitte folgendes sicher
```suggestion
Wenn Änderungen nicht protokolliert werden, stelle bitte folgendes sicher:
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +* Der Bot hat die Berechtigung, diese Änderungen anzuzeigen. Dies bedeutet normalerweise, dass der Bot die Berechtigungen „Audit-prokollo anzeigen“ benötigt, bei
```suggestion
* Der Bot hat die Berechtigung, diese Änderungen zu sehen. Dies bedeutet normalerweise, dass der Bot die Berechtigungen „Audit-Log anzeigen“ benötigt, bei
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +* Der Bot kann keine Änderungen an gesendeten Nachrichten protokollieren, während er offline war.
```suggestion
* Der Bot kann keine Änderungen an gesendeten Nachrichten protokollieren, während er offline ist.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +* Die [Konfiguration](#Konfiguration) für diese bestimmte Änderung ist aktiviert und der richtige Kanal ist ausgewählt.
```suggestion
* Die [Konfiguration](#configuration) für diese bestimmte Änderung ist aktiviert und der richtige Kanal ist ausgewählt.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +* Weise und entferne automatisch Rollen von Partnern.
```suggestion
* Weise zu und entferne automatisch Rollen von Partnern.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +* Sende deinen Partnern automatisch eine Benachrichtigungen über Änderungen ihres Partner-Status.
```suggestion
* Sende deinen Partnern automatisch Benachrichtigungen über Änderungen ihres Partner-Status.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +    4. Lade die Konfiguration deines Bots neu, um die Änderungen zu übernehmen – der Bot sendet automatisch eine Partner-Liste.
```suggestion
    2. Öffne die [Modul-Konfiguration](https://scnx.app/de/glink?page=bot/configuration?file=partner-list%7Cconfig)
       und [konfiguriere das Modul](#configuration).
    3. Lade die Konfiguration deines Bots neu, um die Änderungen zu übernehmen – der Bot sendet automatisch eine Partner-Liste.
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +Mit dieser Konfigurationsdatei kannst du Benachrichtigungen für Partner einrichten, die Einbettung der Partner-Liste bearbeiten und vieles mehr.
```suggestion
Mit dieser Konfigurationsdatei kannst du Benachrichtigungen für Partner einrichten, das Embed der Partner-Liste bearbeiten und vieles mehr. 
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +| Partner-Entfernung-PN | <i>Nur sichtbar, wenn „Partner-Benachrichtigung senden“ aktiviert ist.</i><br/>Diese Nachricht wird an Partner gesendet, wenn dieser entfernt wird. |
```suggestion
| Partner-Willkommens-PN | <i>Nur sichtbar, wenn „Partner-Benachrichtigung senden“ aktiviert ist.</i><br/>Diese Nachricht wird an den Partner gesendet, wenn dieser hinzugefügt wird. |
| Partner-Entfernung-PN | <i>Nur sichtbar, wenn „Partner-Benachrichtigung senden“ aktiviert ist.</i><br/>Diese Nachricht wird an den Partner gesendet, wenn dieser entfernt wird. |
```

2023-10-09 14:50 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /partner-list.md
> +Über jeden über [commands](#commands) angelegten Partner werden folgende Daten gespeichert:
```suggestion
Über jeden über [Befehle](#commands) angelegten Partner werden folgende Daten gespeichert:
```

2023-10-09 15:33 UTC, DEVTomatoCake reviewed
idk bin faul

2023-10-09 15:33 UTC, DEVTomatoCake commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +deiner [Zahlungsseite](https://scnx.app/de/user/zahlungen) erwerben und gegen AI-Credits einlösen, deinen
```suggestion
deiner [Zahlungsseite](https://scnx.app/de/user/payments) erwerben und gegen KI Guthaben einlösen, deinen
```

2023-10-09 15:33 UTC, DEVTomatoCake commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +Um dein Abonnement zu verwalten, besuche die [Zahlungsseite](https://scnx.app/de/user/zahlungen) in deinem Dashboard. Dort kannst du
```suggestion
Um dein Abonnement zu verwalten, besuche die [Zahlungsseite](https://scnx.app/de/user/payments) in deinem Dashboard. Dort kannst du 
```

2023-10-09 15:33 UTC, DEVTomatoCake commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +Um deine Rechnungsadresse festzulegen, gehe zur [Zahlungsseite](https://scnx.app/de/user/zahlungen) in deinem Dashboard. Dort findest du einen Abschnitt „Rechnungsdaten“.
```suggestion
Um deine Rechnungsadresse festzulegen, gehe zur [Zahlungsseite](https://scnx.app/de/user/payments) in deinem Dashboard. Dort findest du einen Abschnitt „Rechnungsdaten“. 
```

2023-10-09 15:33 UTC, DEVTomatoCake commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +Bitte lese dir diesen [FAQ-Artikel](https://faq.scnx.app/de/sepa-lastschrift/) durch, um Informationen zum SEPA-Lastschriftverfahren einzusehen.
```suggestion
Bitte lies dir diesen [FAQ-Artikel](https://faq.scnx.app/de/sepa-lastschrift/) durch, um Informationen zum SEPA-Lastschriftverfahren einzusehen.
```

2023-10-09 15:33 UTC, DEVTomatoCake commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +* Unsere Zahlung hat Deine Transaktion als risikoreich eingestuft und abgelehnt
```suggestion
* Unsere Zahlung hat deine Transaktion als risikoreich eingestuft und abgelehnt
```

2023-10-09 15:33 UTC, DEVTomatoCake commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* 10 meist genutzte Kanäle: Dies ist eine Grafik, die zeigt, wie viel Prozent der Nachrichten über welchen Kanal gesendet wurden.
```suggestion
* Zehn am meisten genutzte Kanäle: Dies ist eine Grafik, die zeigt, wie viel Prozent der Nachrichten in welchem Kanal gesendet wurden.
```

2023-10-09 15:33 UTC, DEVTomatoCake commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +Benutzer, die den [Datenschutzmodus](#user-opt-out) aktiviert haben, können diesen Befehl nicht verwenden (/ zeigt Daten darüber an).
```suggestion
Benutzer, die den [Datenschutzmodus](#user-opt-out) aktiviert haben, können diesen Befehl nicht verwenden.
```
oder besser anhand von original nochmal neu übersetzen

2023-10-09 15:33 UTC, DEVTomatoCake commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /analytics.md
> +* `/stats user`: Zeigt eine Statistikübersicht eines Benutzers auf deinem Server an. Dazu gehören die 10 aktivsten Kanäle (und die Anzahl der darin gesendeten Nachrichten) sowie ein Abschnitt „Auf ei
```suggestion
* `/stats user`: Zeigt eine Statistikübersicht eines Benutzers auf deinem Server an. Dazu gehören die zehn aktivsten Kanäle (und die Anzahl der darin gesendeten Nachrichten) sowie ein Abschnitt „Auf einen Blick“, indem du die Gesamtzahl der Nachrichten und Befehle der letzten 30 Tage findest.
```

2023-10-17 18:34 UTC, patricksynced reviewed
fixed

2023-10-27 16:16 UTC, Fridolin012 approved these changes

2023-10-27 17:45 UTC, merged

2023-10-27 17:46 UTC, SCDerox commented
Merge requested by @Fridolin012 to reduce production translation block issues