Grammar fixes
ScootKit/scnx-docs pull request #22
Opened 2023-09-16 06:20 UTC by DEVTomatoCake

## Type of PR

- [x] Translation update / creation
- [ ] Original file creation
- [ ] Original file content (not typo) update
- [x] Original file typo update

## Checks

If you have changed the content (/ meaning) of an original file, please confirm:

- [ ] Yes, I have copied the updated section to all translations of this file manually.

## Notes

- I've removed in `docs/custom-bot/modules/administration/partner-list.md` and `docs/custom-bot/modules/administration/auto-delete.md` and `---` on the top to be consistent with the other filled out module files. If those are supposed to stay there, please add them in the other module files too.
- Markdown in <summary>'s doesn't work, there are some places in which it's used.

2023-09-16 06:38 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/intro.md
> +  speichern und teilen. Wird von deinem Bot z. B. verwendet, um Logs oder Ticket-Transcripte zu speichern.
```suggestion
  speichern und teilen. Wird von deinem Bot z. B. verwendet, um Logs oder Ticket-Transkripte zu speichern.
```

2023-09-16 06:38 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/trusted-admins.md
> +| **Analytics**: Anzeigen und Verwenden von Analysen                     | Dieser Nutzer kann deine Server Statistiken anzeigen und verwenden.
```suggestion
| **Statistiken**: Anzeigen und Verwenden von Analysen                     | Dieser Nutzer kann deine Server Statistiken anzeigen und verwenden.                                                                                                                             |
```

2023-09-16 06:38 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/trusted-admins.md
> +| **Integrations**: Integrationen ansehen & bearbeiten                   | Dieser Nutzer kann alle Funktionen jeglicher Integrationen anschauen und editieren, aber keine neuen Integrationen hinzufüge
```suggestion
| **Integrationen**: Integrationen ansehen & bearbeiten                   | Dieser Nutzer kann alle Funktionen jeglicher Integrationen anschauen und editieren, aber keine neuen Integrationen hinzufügen.                                                                                |
```

2023-09-16 06:51 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/setup.md
> +den "Mit Discord anmelden" Knopf. Wenn du dich Fragst warum wir Zugriff auf bestimmte Bereiche deiner Informationen brauchen
```suggestion
den "Mit Discord anmelden" Knopf. Wenn du dich fragst, warum wir Zugriff auf bestimmte Bereiche deiner Informationen brauchen
```

2023-09-16 06:51 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/setup.md
>  und dir ["Trusted Admin"-Rechte](scnx/guilds/trusted-admins). Wenn du einen Server erst vor kurzem erstellt hast und er dir nicht angezeigt wird,
```suggestion
und dir ["Trusted Admin"-Rechte](scnx/guilds/trusted-admins) zu geben. Wenn du einen Server erst vor kurzem erstellt hast und er dir nicht angezeigt wird,
```

2023-09-16 06:51 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/setup.md
> +Du kannst jetzt damit anfangen [deinen eigenen Bot](custom-bot) oder [einen Modmail-Bot](modmail) zu erstellen oder einfach alle Features auszuprobieren, die dich interessieren -
```suggestion
Du kannst jetzt damit anfangen [deinen eigenen Bot](custom-bot) oder [einen Modmail-Bot](modmail) zu erstellen oder einfach alle Funktionen auszuprobieren, die dich interessieren -
```

2023-09-16 06:51 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/setup.md
>  Unsere [Dokumentation](/) und unsere [Teammitglieder](https://scnx.app/help) auf dem [Discord](https://sc-net.work/dc) werden dir bei allem weiterhelfen.
```suggestion
Unsere [Dokumentation](/) und unsere [Teammitglieder](https://scnx.app/help) auf dem [Discord-Server](https://sc-net.work/dc) werden dir bei allem weiterhelfen.
```

2023-09-16 17:05 UTC, Fridolin012 requested changes

2023-09-16 17:05 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/plans.md
> +Ja, öffne einfach die <a href="https://scnx.app/de/glink?page=pricing?showUpgradeModal=1">Zahlungsseite</a> deines Servers und öffne den Upgrade-Dialog durch Klicken auf "Verlängern". Dort gib einfac
```suggestion
Ja, öffne einfach die <a href="https://scnx.app/de/glink?page=pricing?showUpgradeModal=1">Zahlungsseite</a> deines Servers und öffne den Upgrade-Dialog durch Klicken auf "Verlängern". Gib dort einfach als Zahlungsintervall das Intervall an, das du für dein Abo verwenden willst - deine übrige Laufzeit wird automatisch an dein Abo angerechnet.
```

2023-09-16 17:27 UTC, DEVTomatoCake commented on docs/custom-bot/modules/administration/auto-delete.md
> +  the [Voice channels](https://scnx.app/glink?page=bot/configuration?file=auto-delete%7Cvoice-channels) configuration
Seems like a dashboard issue.

2023-09-16 19:07 UTC, SCDerox commented on docs/custom-bot/modules/administration/auto-delete.md
> +  the [Voice channels](https://scnx.app/glink?page=bot/configuration?file=auto-delete%7Cvoice-channels) configuration
In the dashboard this is called Voice-Channels in accordance with our current rules for localisations (/ glossary) and I'm not quite sure if we should change it (it looks better this way, at least for me)…

2023-09-17 05:18 UTC, DEVTomatoCake commented on docs/custom-bot/modules/administration/auto-delete.md
> +  the [Voice channels](https://scnx.app/glink?page=bot/configuration?file=auto-delete%7Cvoice-channels) configuration
But is "looks better" the correct way? Hyphens are rare in English, and most importantly, Discord calls voice channels everything but with a hyphen: "Voice Channels", "Voice channels" or "voice channels".

They sometimes don't know what to use, but they don't use it with hyphens at all:
![image](https://github.com/ScootKit/scnx-docs/assets/60300461/bfea6761-0096-45e4-8eee-aa2abd3195fa)

- https://support.discord.com/hc/en-us/articles/11635925354775-Audio-Bitrate-FAQ
- https://support.discord.com/hc/en-us/articles/4412085582359-Text-Channels-Text-Chat-In-Voice-Channels 
- https://support.discord.com/hc/en-us/articles/360045138571-Beginner-s-Guide-to-Discord 
- https://support.discord.com/hc/en-us/articles/1500007645701-Voice-Regions-on-Discord-FAQ 
- https://support.discord.com/hc/en-us/articles/206143877-How-do-I-set-up-a-Role-Exclusive-channel- 
- https://support.discord.com/hc/en-us/articles/360041721052-Video-Calls 
- https://support.discord.com/hc/de/articles/213530048-Erstellen-Verbesserter-Community-Server

2023-09-17 09:52 UTC, SCDerox commented on docs/custom-bot/modules/administration/auto-delete.md
> +  the [Voice channels](https://scnx.app/glink?page=bot/configuration?file=auto-delete%7Cvoice-channels) configuration
Thanks for that, I'm aware (and was aware) of Discord's usage and the correct way of writing Voice Channels. Still, I like it more the current way, but we plan to move to the correct way (/ your suggested way) in the future.

2023-09-17 12:06 UTC, SCDerox approved these changes

2023-09-17 12:07 UTC, Fridolin012 approved these changes

2023-09-17 12:08 UTC, merged

2023-11-02 21:26 UTC, DEVTomatoCake commented
Kommentar 1

2023-11-04 11:18 UTC, SCDerox commented
Thanks for your contribution - you have received a payout as part of our Open Source Developer Program. You can find details in your SCNX organisation payout history. To pay out the received amount, please follow instructions in your dashboard. If you have any questions, please contact ScootKit staff on scnx.app/help.
Cheers ✌️