Translate suggestions.md
ScootKit/scnx-docs pull request #24
Opened 2023-10-07 20:18 UTC by Fridolin012

## Type of PR

- [X] Translation update / creation
- [ ] Original file creation
- [ ] Original file content (not typo) update
- [X] Original file typo update

## Checks

If you have changed the content (/ meaning) of an original file, please confirm:

- [ ] Yes, I have copied the updated section to all translations of this file manually.

## Notes

Please enter additional information here.

2023-10-07 20:32 UTC, SCDerox requested changes

2023-10-07 20:32 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/suggestions.md
> +* Lasse Nutzer für Vorschläge abstimmen, indem sie Reaktionen nutzen
```suggestion
* Lasse Nutzer über mit Reaktionen Vorschläge abstimmen
```

2023-10-07 20:32 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/suggestions.md
> +2. Stelle sicher, dass [Berechtigungen](./../../slash-commands) auf `/manage-suggestions` richtig konfiguriert sind, um zu verhindern,
```suggestion
2. Stelle sicher, dass [Berechtigungen](./../../slash-commands) für `/manage-suggestions` richtig konfiguriert sind, um zu verhindern, 
```

2023-10-07 20:32 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/suggestions.md
> +  wird den Vorschlags-Ersteller, wenn konfiguriert, über PNs informieren.
```suggestion
* Admins können Vorschläge mit `/manage-suggestions` annnehmen oder ablehnen und optional auch einen Kommentar zu ihrer Entscheidung angeben. Drüber 
  wird der Vorschlag-Ersteller, wenn konfiguriert, über PNs informiert.
```

2023-10-07 20:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/suggestions.md
> +* Lasse Nutzer für Vorschläge abstimmen, indem sie Reaktionen nutzen
That makes no sense

2023-10-07 20:40 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/suggestions.md
> +* Lasse Nutzer für Vorschläge abstimmen, indem sie Reaktionen nutzen
i'm sorry my brain is faster than I can type (definitely that and not my lack of sleep)

2023-10-08 10:39 UTC, SCDerox approved these changes

2023-10-08 10:39 UTC, merged

2023-10-12 16:54 UTC, SCDerox commented
Thanks for your contribution - you have received a payout as part of our [Open Source Developer Program](https://faq.scnx.app/open-source-developer-pool/). You can find details in your SCNX organisation payout history. To pay out the received amount, please follow instructions in your dashboard. If you have any questions, please contact ScootKit staff on [scnx.app/help](https://scnx.app/help).
Cheers ✌️