Translate team list
ScootKit/scnx-docs pull request #25
Opened 2023-10-12 17:52 UTC by DEVTomatoCake

## Type of PR

- [x] Translation update / creation
- [ ] Original file creation
- [ ] Original file content (not typo) update
- [x] Original file typo update

## Checks

- [x] Yes, I have copied the updated section to all translations of this file manually.

2023-10-12 17:57 UTC, SCDerox requested changes

2023-10-12 17:57 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-list.md
> +2. Öffne die [Modulkonfiguration](https://scnx.app/glink?page=bot/configuration?file=team-list%7Cconfig) und [konfiguriere das Modul](#configuration).
```suggestion
2. Öffne die [Modulkonfiguration](https://scnx.app/de/glink?page=bot/configuration?file=team-list%7Cconfig) und [konfiguriere das Modul](#configuration).
```

2023-10-12 17:57 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-list.md
> +| Kanal                          | Dies ist der Kanal, in den die Teamliste gesendet wird. Wenn der Bot bereits eine Nachricht davor gesendet hat, wird die vorhandene Nachricht zur Teamliste bearbeit
```suggestion
| Kanal                          | Dies ist der Kanal, in den die Teamliste gesendet wird. Wenn der Bot zuvor bereits eine Nachricht gesendet hat, wird die vorhandene Nachricht zur Teamliste bearbeitet. Wir empfehlen einen leeren Kanal.                                                                                                                                                                                                                                                                                                                                                                           |
```

2023-10-12 17:57 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-list.md
> +		<li>Stelle sicher, dass du mindestens 15 Minuten lang gewartet hast, da das das Intervall ist, in dem sich das Embed aktualisiert.</li>
```suggestion
		<li>Stelle sicher, dass du mindestens 15 Minuten lang gewartet hast, da dies das Intervall ist, in dem sich das Embed aktualisiert.</li>
```

2023-10-12 17:57 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-list.md
> +Öffne sie in deinem [Dashboard](https://scnx.app/glink?page=bot/configuration?file=team-list%7Cconfig).
```suggestion
Öffne sie in deinem [Dashboard](https://scnx.app/de/glink?page=bot/configuration?file=team-list%7Cconfig).
```

2023-10-12 17:57 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-list.md
> +| Embed                            | Dies sind Einstellungen, die das Aussehen deines Embeds auf Discord beeinflussen.<br/>`title`: Dies ist der Titel des Embeds, welcher als erstes im Embed angezeig
```suggestion
| Embed                            | Dies sind Einstellungen, die das Aussehen deines Embeds auf Discord beeinflussen.<br/>`title`: Dies ist der Titel des Embeds, welcher als erstes im Embed angezeigt wird.<br/>`description` (optional): Dies ist der Text, der unter dem Titel im Embed angezeigt wird.<br/>`color`: Dies ist die Farbe des Embeds (verwende eine [HEX-Farbe oder einen unterstützten Farbwert](./../../additional-features#embed-colors))<br/>`thumbnail-url` / `img-url` (optional): URLs zum Anzeigen von Bildern im Embed. Du kannst den [Dateien-Speicher](https://scnx.app/de/user/files) zum Hochladen von einem Bild verwenden und die Bild-URL kopieren.|
```

2023-10-12 18:03 UTC, Fridolin012 requested changes

2023-10-12 18:05 UTC, Fridolin012 approved these changes

2023-10-12 18:05 UTC, merged

2023-11-02 21:26 UTC, DEVTomatoCake commented
Kommentar 2

2023-11-04 11:10 UTC, SCDerox commented
Thanks for getting back to us and sorry for the delay!

Thanks for your contribution - you have received a payout as part of our [Open Source Developer Program](https://faq.scnx.app/open-source-developer-pool/). You can find details in your SCNX organisation payout history. To pay out the received amount, please follow instructions in your dashboard. If you have any questions, please contact ScootKit staff on [scnx.app/help](https://scnx.app/help).
Cheers ✌️