Small translation fixes
ScootKit/scnx-docs pull request #28
Opened 2023-10-28 06:46 UTC by Fridolin012

## Type of PR

- [X] Translation update / creation
- [ ] Original file creation
- [ ] Original file content (not typo) update
- [X] Original file typo update

## Checks

If you have changed the content (/ meaning) of an original file, please confirm:

- [ ] Yes, I have copied the updated section to all translations of this file manually.

## Notes

Please enter additional information here.

2023-10-28 18:02 UTC, SCDerox requested changes
Two small things

2023-10-28 18:02 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/account-and-billing/faq.md
> +Durch einen Unfall zu viel Geld verschickt? Keine Sorge: Dein Geld wird automatisch für zukünftige Zahlungen verwendet (falls dies nicht möglich ist, wird sich Stripe mit dir in Verbindung setzen und
```suggestion
Aus Versehen zu viel Geld verschickt? Keine Sorge: Dein Geld wird automatisch für zukünftige Zahlungen verwendet (falls dies nicht möglich ist, wird sich Stripe mit dir in Verbindung setzen und nach den Bankdaten fragen). Andernfalls kannst
```

2023-10-28 18:02 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds /custom-bot/modules/administration /logging.md
> +Mit dem Fortgeschrittenes Logging-Modul kannst du folgendes ganz einfach tun:
```suggestion
Mit dem fortgeschrittenen Logging-Modul kannst du folgendes ganz einfach tun:
```
Name of the module

2023-10-29 19:32 UTC, SCDerox approved these changes

2023-10-29 19:32 UTC, merged

2023-11-05 11:12 UTC, Fridolin012 commented
Hello there