Document rps
ScootKit/scnx-docs pull request #38
Opened 2023-12-01 17:38 UTC by DEVTomatoCake

## Type of PR

- [ ] Translation update / creation
- [x] Original file creation
- [ ] Original file content (not typo) update
- [ ] Original file typo update

## Notes

Tables might need fixing due to the `fix-tables` script continuing to respond with "No markdown table formatting has been applied."

And fixed the element ID of throUbleshooting because they somehow were back in a file.

2023-12-01 17:45 UTC, Fridolin012 requested changes

2023-12-01 17:45 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/scnx/guilds/backups.md
> +## Behebung häufiger Fehler {#throubleshooting}
```suggestion
## Fehlerbehebung {#throubleshooting}
```

2023-12-04 10:18 UTC, SCDerox requested changes

2023-12-04 10:18 UTC, SCDerox commented on docs/custom-bot/modules/fun/rock-paper-scissors.md
> +If the user option of the command is left empty or a bot is provided, the game starts automatically in the current channel.
```suggestion
If the user option of the command is left empty or a bot is provided, the game starts automatically in the current channel.
```
```suggestion
If the user option of the command is left empty or a bot is provided, the game starts automatically in the current channel playing against CustomBot's AI.
```
Make it clearer who the opponent will be

2023-12-09 21:40 UTC, SCDerox approved these changes
Sorry for the delay, I had covid again causing delays in selected work tasks (aka anything i didn't want to) - everything looks great, will merge in just a sec

2023-12-09 21:40 UTC, merged

2023-12-13 09:52 UTC, SCDerox commented
Thanks for your contribution - you have received a payout as part of our Open Source Developer Program. You can find details in your SCNX organisation payout history. To pay out the received amount, please follow instructions in your dashboard. If you have any questions, please contact ScootKit staff on scnx.app/help.
Cheers ✌️