giveaways.md
ScootKit/scnx-docs pull request #43
Opened 2024-01-27 13:41 UTC by hoernchen-from-hotel

## Type of PR

- [ X ] Translation update / creation
- [ ] Original file creation
- [ ] Original file content (not typo) update
- [ ] Original file typo update

## Checks

If you have changed the content (/ meaning) of an original file, please confirm:

- [ ] Yes, I have copied the updated section to all translations of this file manually.

## Notes

Please enter additional information here.

2024-01-27 13:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ScootKit/scnx-docs?pullRequest=43) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ScootKit/scnx-docs?pullRequest=43) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ScootKit/scnx-docs?pullRequest=43) it.</sub>

2024-01-28 17:55 UTC, Fridolin012 requested changes

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +Gewinnspiele einfach in deinem Server erstellen.
```suggestion
Erstelle Gewinnspiele auf deinem Server einfach.
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +## Features {#features}
```suggestion
## Funktionen {#features}
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +* Gebe zusätzliche Gewinnchancen zu Mitgliedern mit bestimmten Rollen.
```suggestion
* Gebe zusätzliche Gewinnchancen an Mitglieder mit bestimmten Rollen.
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +* Lasse Mitglieder die Vorraussetzungen der Gewinnnspiele auslassen.
```suggestion
* Lasse Mitglieder mit bestimmten Rollen die Vorraussetzungen der Gewinnnspiele überspringen.
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +  dort werden Nachrichten von Mitgliedern nicht gezählt).
```suggestion
* Lasse Mitglieder eine bestimmte Anzahl neuer Nachrichten senden, um am Gewinnspiel teilzunehmen zu können (du kannst auch Kanäle erlauben / blockieren, 
dort werden Nachrichten von Mitgliedern dann nicht gezählt).
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +* Fordere deine Mitglieder auf, eine bestimmte Rolle zu besitzen, bevor sie teilnehmen können.
```suggestion
* Lasse nur Mitglieder mit einer bestimmten Rolle teilnehmen.
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +## Setup {#setup}
```suggestion
## Einrichtung {#setup}
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +* Bitte [stelle die Berechtigungen](./../../slash-commands) für den Command `/gmanage` ein, um unerlaubte Nutzung zu vermeiden.
```suggestion
* Bitte [stelle die Berechtigungen](./../../slash-commands) für den Befehl `/gmanage` ein, um unerlaubte Nutzung zu vermeiden.
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +* Stelle sicher, dasss dein Bot die Berechtigungen `Kanäle ansehen`, `Kanäle verwalten`, `Links einbetten` und `Nachrichten senden` in den Kanälen, wo dein Gewinnspiel veranstalten werden soll, hat.
```suggestion
* Stelle sicher, dass dein Bot die Berechtigungen `Kanäle ansehen`, `Kanäle verwalten`, `Links einbetten` und `Nachrichten senden` in den Kanälen, wo Gewinnspiele veranstaltet werden sollen, besitzt.
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +* Gewinnspiele können nicht in Ankündigungs Kanälen gestartet werden.
```suggestion
* Gewinnspiele können nicht in Ankündigungs-Kanälen gestartet werden.
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +Als ein Gewinnspiel-manager kannst du:
```suggestion
Als ein Gewinnspiel-Manager kannst du:
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +Deine Mitglieder können mit dem Command [`/gmessages`](#commands) ihren Fortschritt der benötigten Nachrichten für ein Giveaway sehen.
```suggestion
Deine Mitglieder können mit dem Befehl [`/gmessages`](#commands) ihren Fortschritt der benötigten Nachrichten für ein Gewinnspiel sehen.
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +Gewinnspiel-voraussetzungen (wie Rollen oder Nachrichten) werden zum Zeitpunkt des Beitritts ausgewertet und dem Nutzer angezeigt
```suggestion
Gewinnspiel-Voraussetzungen (wie Rollen oder Nachrichten) werden zum Zeitpunkt des Beitritts ausgewertet und dem Nutzer angezeigt.
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +erneut bewertet, was bedeutet, dass Benutzer, die beispielsweise ihre Rolle nach der Teilnahme am Gewinnspiel verloren haben, nicht gewinnen können.
```suggestion
Bei der Auslosung der Gewinner werden Anforderungen immer
erneut überprüft, was bedeutet, dass Nutzer, die beispielsweise ihre Rolle nach dem Beitritt am Gewinnspiel verloren haben, nicht gewinnen können.
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +## Commands {#commands}
```suggestion
## Befehle {#commands}
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| Command                                                                                                                                                                                | Description
```suggestion
| Befehl                                                                                                                                                                                | Beschreibung                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| `/gmessages`                                                                                                                                                                           | Mit diesem C
```suggestion
| `/gmessages`                                                                                                                                                                           | Mit diesem Befehl können Nutzer ihren Nachrichten-Fortschritt für die Voraussetzungen eines Gewinnspiels sehen.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| `/gmange start channel:<Channel> price:<Text> duration:<TimeDuration> winner-count:<Number> [required-messages:<Number>] [required-role:<Role>] [sponsor:<Text>] [sponsorlink:<Text>]` | Starte ein n
```suggestion
| `/gmanage start channel:<Kanal> price:<Text> duration:<Dauer> winner-count:<Nummer> [required-messages:<Nummer>] [required-role:<Rolle>] [sponsor:<Text>] [sponsorlink:<Text>]` | Starte ein neues Gewinnspiel.<br/>Bitte stelle sicher, dass der gewählte Kanal [richtig eingestellt ist](#setup). Den Preis kannst du selbst bestimmen, stelle aber bitte sicher, dass er nicht gegen Gesetze oder Vorschriften verstößt. Als nächstes gibst du die Anzahl an zufällig ausgewählten Gewinnern an. Wir empfehlen, mehrere Gewinnspiele für mehrere Preise zu starten.<br/>Als nächstes gibst du die Dauer des Gewinnspiels ein. Nachdem dieses Datum vorüber ist, wird das Gewinnspiel automatisch beendet und ein Gewinner wird zufällig und automatisch ausgelost. Du kannst die Dauer im [Datum Format]-(./../../additional-features#durations) einstellen.<br/>Du kannst auch optionale Voraussetzung erstellen:<ul><li>Mit `required-messages` kannst du deine Mitglieder auffordern, eine bestimmte Anzahl von Nachrichten zu haben, um an dem Gewinnspiel teilzunehmen.</li><li>Fordere deine Mitglieder auf, eine Rolle zu besitzen, indem du `required-role` nutzt - Mitglieder ohne diese Rolle können nicht an dem Gewinnspiel teilnehmen.</li><li>Nutze `sponsor` und `sponsor-link` um einen (optionalen) Sponsor zu erwähnen - du kannst jederzeit in deiner <a href="#configuration">Konfiguration</a> einstellen, wie deine Gewinnspiel-Nachricht aussehen soll.</li></ul> |
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| `/gmanage end msg-id:<GiveawayMessageID>`                                                                                                                                               |Beendet ein
```suggestion
| `/gmanage end msg-id:<GewinnspielNachrichtenID>`                                                                                                                                               |Beendet ein Gewinnspiel vorzeitig, die Gewinner des Gewinnspiel werden direkt nach der Ausführung des Befehls zufällig ausgewählt.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| `/gmanage reroll msg-id:<GiveawayMessageID> [winner-count:<Number>]`                                                                                                                   | Wählt eine b
```suggestion
| `/gmanage reroll msg-id:<GewinnspielNachrichtID> [winner-count:<Nummer>]`                                                                                                                   | Wählt eine bestimmte Anzahl von Nutzern aus, die nach dem Ende des Gewinnspiels neu ausgelost werden. Bitte beachte, dass nach dem neu auslosen eines Gewinnspiels der davor gewonnene Nutzer noch einmal ausgelost werden kann.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +### Modul Konfiguration {#configuration-config}
```suggestion
### Modul-Konfiguration {#configuration-config}
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +:::
```suggestion
:::Achtung:
Nutzer für Einladungen zu belohnen, indem du mehrere Teilnahmen erlaubst, verstößt gegen 
[Discords Entwickler-Nutzungsbedingungen](https://discord.com/developers/docs/policies-and-agreements/developer-policy) und
unsere [Nutzungsbedingungen](https://scootk.it/scnx-tos); Verstöße werden direkt zu unserem Team weitergeleitet und dein Server oder auch dein Account wird von SCNX gesperrt. Melde Missbrauch hier: [abuse@scnx.xyz](mailto:abuse@scnx.xyz).
:::
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +In dieser Konfigurations Datei kannst du die Funktionalität von diesem Modul einstellen. Öffne es in deinem [dashboard](https://scnx.app/glink?page=bot/configuration?file=giveaways%7Cconfigs%2Fconfig
```suggestion
In dieser Konfigurationsdatei kannst du die Funktionalität von diesem Modul einstellen. Öffne sie in deinem [Dashboard](https://scnx.app/de/glink?page=bot/configuration?file=giveaways%7Cconfigs%2Fconfig).
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| Field                             | Description
```suggestion
| Feld                             | Beschreibung                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| Sende eine DM an den/ die Gewinner         | Falls Nutzer bei einem Gewinnspiel gewinnen, werden sie zusätzlich zu dem Ping in dem Gewinnspiel-channel eine DM erhalten.. Du kannst die Nachricht in
Please use the names from the SCNX Dashboard.

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +### Modul Nachrichten {#configuration-strings}
```suggestion
### Modul-Nachrichten {#configuration-strings}
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +Öffne dies in deinem [dashboard](https://scnx.app/glink?page=bot/configuration?file=giveaways%7Cconfigs%2Fstrings).
```suggestion
In dieser Konfigurationsdatei kannst du einstellen, wie Nachrichten in diesem Modul aussehen sollen.
Öffne sie in deinem [Dashboard](https://scnx.app/de/glink?page=bot/configuration?file=giveaways%7Cconfigs%2Fstrings).
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| Gewinner DM-nachricht                        | *Dies wird nur funktionieren, wenn du "Send DM-Message to winner" in deiner [modul Konfiguration](#configuration-config) aktiviert hast.* <br/>Diese N
Please use the names from the SCNX Dashboard.

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +## Problemlösungen {#troubleshooting}
```suggestion
## Fehlerbehebung {#troubleshooting}
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +  <summary>Die Gewinnspiel-vorrausetzungen werden nicht richtig berechnet</summary>
```suggestion
  <summary>Die Gewinnspiel-Vorrausetzungen werden nicht richtig berechnet</summary>
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +    <li>Stelle sicher dass du den <a href="#configuration-config">Zähl Modus</a> richtig eingestellt hast.</li>
```suggestion
    <li>Stelle sicher, dass du den <a href="#configuration-config">Nachrichten-Zähl-Modus</a> richtig eingestellt hast.</li>
```

2024-01-28 17:55 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +    <li>Wenn du "whitelist" als Zähl modus eingestellt hast: Stelle sicher, dass der Kanal,in dem die Nachrichten gezählt werden sollen auf der <a href="#configuration-config">whitelist</a> ist.</li>
```suggestion
    <li>Wenn du "blacklist" als Nachrichten-Zähl-Modus eingestellt hast: Stelle sicher, dass der Kanal, indem du Nachrichten zählen lassen möchtest, <a href="#configuration-config">nicht blockiert</a> ist.</li>
    <li>Wenn du "whitelist" als Nachrichten-Zähl-Modus eingestellt hast: Stelle sicher, dass der Kanal, indem die Nachrichten gezählt werden sollen, <a href="#configuration-config">erlaubt</a> ist.</li>
```

2024-01-28 18:05 UTC, Fridolin012 requested changes

2024-01-28 18:05 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +  Server unseren Service in einer nicht konformen Weise nutzt, melde es bitte an<a href="mailto:abuse@scnx.xyz">abuse@scnx.xyz</a> und wir werden entsprechende Maßnahmen ergreifen.
```suggestion
  <summary>Wie bestimmt mein Bot den Gewinner? / Kann ich ein Zertifikat erhalten? / Kann ein Gewinnspiel manipuliert sein?</summary>

Wenn ein Gewinnspiel endet (oder eine Neuauslosung wurde angewandt wurde), wird dein bot als erstes die Vorrausetzungen prüfen (und damit die zusätzlichen Teilnahmebedingungen neu berechnen), um sicherzustellen, dass jeder Nutzer immer noch teilnimmt.
Jeder berechtigte Nutzer wird in eine digitale Kiste gepackt. Nutzer mit <a href="#configuration-config">Zusätzlichen Teilnahmen</a> werden in diese Kiste mehrmals gepackt, abhänging von den zusätzlichen Teilnahmen die sie durch ihre Rolle(n) erhalten.
Als nächstes zieht der Bot einen Nutzer aus der Kiste. Wenn dieser Benutzer bei dieser Ziehung bereits gewonnen hat, zieht der Bot erneut, bis die Anzahl der Gewinner korrekt ist.<br/><br/>
Da Serveradministratoren Gewinnchancen, Anforderungen und mehr manipulieren können, sind wir nicht in der Lage, ein Zertifikat oder eine ähnliche Dokumentation zu erstellen. Der Organisator des Gewinnspiels ist verpflichtet, die örtlichen Gesetze und Vorschriften einzuhalten, einschließlich unserer eigenen <a href="https://scootk.it/scnx-tos">Nutzungsbedingungen</a>. Wenn du der Meinung bist, dass ein 
Server unseren Service in einer nicht konformen Weise nutzt, melde es bitte an<a href="mailto:abuse@scnx.xyz">abuse@scnx.xyz</a> und wir werden entsprechende Maßnahmen ergreifen.
```

2024-01-28 18:05 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +* Metadaten über die Teilnahme (Datum der Erstellung und letzten Aktualisierung)
```suggestion
* Eine eindeutige Zahl, die die Teilnahmen identifiziert
* Die ID der Gewinnspiel-Nachricht
* Die ID des Kanals, in dem das Gewinnspiel gestartet wurde, abhängig von dem [`channel`](#commands) Befehl-Parameter
* Die Zeit, wann das Gewinnspiel enden wird  / geendet hat, abhängig von dem [`zeit`](#commands) Befehl-Parameter
* Ob das Gewinnspiel schon geendet hat
* Den Preis des Gewinnspiels, abhängig von dem [`Preis`](#commands) Befehl-Parameter
* Die Vorrausetzungen des Gewinnspiels (wie Rollen oder die Anzahl von Nachrichten, falls angeschaltet), basierend auf deinen [Befehl-Parametern](#commands)
* Wenn das Teilnehmen bei dem Gewinnspiel eine bestimmte Anzahl an Nachrichten voraussetzt:
  * Die Anzahl von Nachrichten von allen Nutzern nach dem Start des Gewinnspiels
* Daten über jede berechtigte Teilnahme an dem Gewinnspiel: 
  * ID von den Nutzern, die an dem Gewinnspiel teilgenommen haben
  * Die Anzahl von Teilnahmen die Nutzer insgesamt teilgenommen haben, abhängig von deiner [Konfiguration](#configuration)
  * Ob der Nutzer teilgenommen hat, indem er die Vorrausetzungen übersprungen hat, abhängig von deiner [Konfiguration](#configuration)
* Die ID des Sponsors vom Gewinnspiel (falls nicht der Ersteller des Gewinnspiels) 
* Der Sponsor-Link, abhängig von deiner konfigurierten [`sponsor-url`](#commands) 
* Die Anzahl von Gewinnern, abhängig von dem [`winner-count`](#commands) Befehl-Parameter
* Metadaten über die Teilnahme (Datum der Erstellung und letzten Aktualisierung)
```

2024-01-28 18:05 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +Es gibt keine Möglichkeit, ein Gewinnspiel aus der Datenbank zu entfernen (Du kannst die Gewinnspiel-Nachricht trotzdem jederzeit löschen). Um alle Gewinnspiele zu löschen, [lösche die modul datenban
```suggestion
Es gibt keine Möglichkeit, ein Gewinnspiel aus der Datenbank zu entfernen (du kannst die Gewinnspiel-Nachricht trotzdem jederzeit löschen). Um alle Gewinnspiele zu löschen, [lösche die Modul-Datenbank](./../../additional-features#reset-module-database).
```

2024-01-28 18:19 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +Gewinnspiele einfach in deinem Server erstellen.
Besser: Erstelle einfach Gewinnspiele auf deinem Server.

2024-01-28 18:34 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +Gewinnspiele einfach in deinem Server erstellen.
Okay, i edited my suggestion.

2024-01-28 18:52 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +:::
better: gegen **DIE** Entwickler-Nutzungsbedingungen von Discord und...

2024-01-28 18:52 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| Sende eine DM an den/ die Gewinner         | Falls Nutzer bei einem Gewinnspiel gewinnen, werden sie zusätzlich zu dem Ping in dem Gewinnspiel-channel eine DM erhalten.. Du kannst die Nachricht in
Where exactly?

2024-01-28 18:52 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| Gewinner DM-nachricht                        | *Dies wird nur funktionieren, wenn du "Send DM-Message to winner" in deiner [modul Konfiguration](#configuration-config) aktiviert hast.* <br/>Diese N
please give me the names orsuggest a change ^^

2024-01-28 18:52 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +:::
eventually "Discords Entwickler-Nutzungsbedingungen" is a bit too complex, is it the original name from discord?

2024-01-28 19:29 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +:::
https://github.com/ScootKit/scnx-docs/pull/43/files is ok^^

2024-01-28 19:31 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| Sende eine DM an den/ die Gewinner         | Falls Nutzer bei einem Gewinnspiel gewinnen, werden sie zusätzlich zu dem Ping in dem Gewinnspiel-channel eine DM erhalten.. Du kannst die Nachricht in
For example, "Gewinnspiel Rollen ohne Vorraussetzungen" is called "Gewinnspiel-Voraussetzungen-Ignorierung-Rollen": https://scnx.app/glink?page=bot/configuration?query=gewinns&file=giveaways|configs/config

2024-01-28 19:31 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| Gewinner DM-nachricht                        | *Dies wird nur funktionieren, wenn du "Send DM-Message to winner" in deiner [modul Konfiguration](#configuration-config) aktiviert hast.* <br/>Diese N
Look here: https://github.com/ScootKit/scnx-docs/pull/43/files#r1468924471

2024-01-30 16:13 UTC, Fridolin012 requested changes

2024-01-30 16:13 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| Zusätzliche Teilnahmen                  | Für jede konfigurierte Rolle hier (die ein Nutzer hat) wird zusätzliche Teilnahmen erhalten. Normalerweise haben Mitglieder 1 Teilnahme. Für jede konfiguri
```suggestion
| Zusätzliche Teilnahmen                  | Für jede hier konfigurierte Rolle (die ein Nutzer hat), werden zusätzliche Teilnahmen vergeben. Normalerweise haben Mitglieder 1 Teilnahme. Für jede konfigurierte Rolle hier erhalten diese zusätzliche Teilnahmen, abhängig von dieser Konfiguration.<br/><ul><li>Erstes Feld: Rollen ID</li><li>Anzahl von *zusätzlichen** Teilnahmen, die Mitglieder mit einer bestimmten Rolle erhalten.</li></ul>                                                                                                                                                                      |
```

2024-01-30 16:13 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| Gewinnspiel-nachricht                         | Diese Nachricht wird gesendet, wenn ein [Gewinnspiel ohne Vorrausetzungen gestartet wurde](#usage). Ein Knopf wird unter der Gewinnspiel-nachricht an
```suggestion
| Gewinnspiel-Nachricht                         | Diese Nachricht wird gesendet, wenn ein [Gewinnspiel ohne Vorausetzungen gestartet wurde](#usage). Ein Knopf wird unter der Gewinnspiel-Nachricht angezeigt, womit Nutzer dem Gewinnspiel beitreten können.<br/>Du kannst alle verfügbaren Parameter im Dashboard finden.                                                          |
```

2024-01-30 16:13 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| Gewinnspiel-nachricht mit Vorrausetzungen       | Diese Nachricht wird gesendet, wenn ein [Gewinnspiel mit Vorrausetzungen gestartet wurde](#usage) (wie eine benötigte Rolle oder eine bestimmmte An
```suggestion
| Gewinnspiel-Nachricht mit Vorausetzungen       | Diese Nachricht wird gesendet, wenn ein [Gewinnspiel mit Vorausetzungen gestartet wurde](#usage) (wie eine benötigte Rolle oder eine bestimmte Anzahl an Nachrichten). Ein Knopf wird unter der Gewinnspiel-Nachricht angezeigt, womit Nutzer dem Gewinnspiel beitreten können<br/>Du kannst alle verfügbaren Parameter im Dashboard finden.                             |
```

2024-01-30 16:13 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| Gewinnspiel-Vorrausetzungen-Nicht-Erfüllt-Nachricht            | Diese Nachricht wird gesendet, wenn ein Nutzer versucht einem Gewinnspiel beizutreten, aber noch nicht die Vorrausetzungen erfüllt (
```suggestion
| Gewinnspiel-Voraussetzungen-Nicht-Erfüllt-Nachricht            | Diese Nachricht wird gesendet, wenn ein Nutzer versucht einem Gewinnspiel beizutreten, aber noch nicht die Voraussetzungen erfüllt (wie eine benötigte Rolle oder eine bestimmte Anzahl an Nachrichten), um teilzunehmen.<br/>Du kannst alle verfügbaren Parameter im Dashboard finden.
```

2024-01-30 16:13 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| Gewinnspiel-nachricht nach Beendung des Gewinnspiels | Die Original-nachricht des Gewinnspiels wird nach Ende des Gewinnspiels bearbeitet.<br/>Du kannst alle verfügbaren Parameter im Dashboard find
```suggestion
| Gewinnspiel-Nachricht nach Beendung des Gewinnspiels | Die Original-Nachricht des Gewinnspiels wird nach Ende des Gewinnspiels bearbeitet.<br/>Du kannst alle verfügbaren Parameter im Dashboard finden.   
```

2024-01-30 16:13 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| Gewinn-nachricht                                | Diese Nachricht wird nach Ende des Gewinnspiels gesendet, es enthält die Anzahl an Gewinnern.<br/>Du kannst alle verfügbaren Parameter im Dashboard
```suggestion
| Gewinn-Nachricht                                | Diese Nachricht wird nach Ende des Gewinnspiels gesendet, sie enthält die Gewinner.<br/>Du kannst alle verfügbaren Parameter im Dashboard finden.
```

2024-01-30 16:13 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community /giveaways.md
> +| Bereits teilgenommen-Nachricht                   | Diese Nachricht wird angezeigt, wenn ein Nutzer an einem Gewinnspiel teilnehmen will, aber bereits teilgenommen hat. Ein Knopf, um das Gewinnspiel
```suggestion
| Bereits teilgenommen-Nachricht                   | Diese Nachricht wird angezeigt, wenn ein Nutzer an einem Gewinnspiel teilnehmen will, aber bereits teilgenommen hat. Ein Knopf, um das Gewinnspiel zu verlassen wird angehangen.<br/>Du kannst alle verfügbaren Parameter im Dashboard finden.                                                                           |
```

2024-01-30 16:19 UTC, Fridolin012 approved these changes

2024-01-30 16:20 UTC, merged