tickets.md
ScootKit/scnx-docs pull request #44
Opened 2024-01-31 19:36 UTC by hoernchen-from-hotel

## Type of PR

- [  X ] Translation update / creation
- [ ] Original file creation
- [ ] Original file content (not typo) update
- [ ] Original file typo update

## Checks

If you have changed the content (/ meaning) of an original file, please confirm:

- [ ] Yes, I have copied the updated section to all translations of this file manually.

## Notes

Please enter additional information here.

2024-03-20 19:20 UTC, SCDerox requested changes
Thank you for your understanding.
The sheer amount of grammatical mistakes and typos made this contribution very difficult to review. Please make sure to double-check submissions in the future: Some parts of your contribution sound like you've never spoken German in your life. I know that translating documentation is challenging for beginners, but advanced language skills, such as proper positioning of commas and natural sounding sentences, are required. In this PR, I have marked every single issue I found. This is not something we can be doing every time (it takes multiple hours to do this) - future contributions from you might get declined if we find the overall quality insufficient. Double-check your work, use tools like LanguageTool to check for mistakes, and try translating more freely.

2024-03-20 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* Der Ticket-Log Kanal ist richtig eingestellt und der Bot hat die Berechtigung um dort Nachrichten zu senden.
```suggestion
* der Ticket-Log Kanal richtig eingestellt ist und der Bot hat die Berechtigung zum Senden von Nachrichten hat.
```
Der Satz beginnt in Zeile 57

2024-03-20 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* Der Ticketerstellungs-Kanal ist Leer.
```suggestion
* der Inhalt des Ticketerstellungs- und Ticketschließungs-Knopfes korrekt ist.
* der Ticketerstellungs-Kanal ist leer ist.
```

2024-03-20 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +| Ticketschließungs-Button                  | Dies wird der Inhalt des Knopfes unter der Ticketschließungs-Nachricht sein, der das Ticket schließt.
```suggestion
| Ticketerstellungs-Knopf                 | Dies wird der Inhalt des Knopfes unter der Ticketerstellungs-Nachricht sein.                                                                                   |
| Ticketschließungs-Knopf                  | Dies wird der Inhalt des Knopfes unter der Ticketschließungs-Nachricht sein, der das Ticket schließt.                                                                                     |
```

2024-03-20 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +Die folgenden Daten werden über jedes neuen Ticket gespeichert, das durch das Klicken des Knopfes erstellt wurde:
```suggestion
Die folgenden Daten werden über jedes neue Ticket gespeichert, das durch das Klicken des Knopfes erstellt wird:
```

2024-03-20 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* Die ID des Kanals indem die Nachricht gesendet wurde.
```suggestion
* Die Discord-ID des Nutzers, der das Ticket erstellt hat.
* Die Discord-ID des Kanals, in welchem die Nachricht gesendet wurde.
```
indem wäre hier falsch, wenn dann "in dem" weil nicht modal

2024-03-20 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* Wenn das Ticket bereits geschlossen wurde: Die URL des Ticket-Transcripts.
```suggestion
* Wenn das Ticket bereits geschlossen wurde: Die URL des Ticket-Protkolls.
```

2024-03-20 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* Jeder zusätzlicher Nutzer der zum Ticket hinzugrfügt wurde (momentan nicht unterstützt).
```suggestion
* Jeder zusätzlicher Nutzer, der zum Ticket hinzugefügt wurde (momentan nicht unterstützt).
```

2024-03-20 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* Metadata über den Eintrag (wann erstellt und zuletzt geupdated).
```suggestion
* Metadata über den Eintrag (wann er erstellt und zuletzt geändert wurde).
```

2024-03-20 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +Die folgenden Datne werden über die Ticketerstellungs-Nachricht (mit denen Nutzer Tickets öffnen können):
```suggestion
Die folgenden Daten werden über die Ticketerstellungs-Nachricht (mit denen Nutzer Tickets öffnen können) gespeichert:
```

2024-03-20 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* Die ID des Kanals indem die Nachricht gesendet wurde.
```suggestion
* Die ID des Kanals, in welchem die Nachricht gesendet wurde.
```

2024-03-20 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* Metadata über den Eintrag (wann erstellt und zuletzt geupdated).
```suggestion
* Metadata über den Eintrag (wann er erstellt und zuletzt geändert wurde).
* ```

2024-03-20 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +, der auf [PrivateBin](https://github.com/PrivateBin/PrivateBin) läuft. Das bedeutet Scootkit kann keine Ticket-Transcripts entschlüsseln. Ticket-Transcripts werden in deinem Browser entschlüsselt na
```suggestion
Ticket-Protokolle werden verschlüsselt und dann auf [ScootKit Paste](https://paste.scootkit.net) hochgeladen, einem Dienst, der auf [PrivateBin](https://github.com/PrivateBin/PrivateBin) basiert. Das bedeutet, dass Scootkit Ticket-Protokolle nicht entschlüsseln kann. Ticket-Protokolle werden in deinem Browser entschlüsselt, wenn du auf die URL klickst hast. Dies passiert zur zur Sicherheit deiner Nutzer. Ticket-Protkolle werden nach einem Jahr automatisch gelöscht.
```

2024-03-20 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +Du kannst kein Ticket von der Datenbank löschen.
```suggestion
Du kannst keine Tickets aus der Datenbank löschen.
```

2024-03-20 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +Um alle Daten über die Tickets zu löschen, [lösche die Modul-Datenbank](./../../additional-features#reset-module-database).
```suggestion
Um alle Daten über Tickets zu löschen, [lösche die Modul-Datenbank](./../../additional-features#reset-module-database).
```

2024-03-20 19:34 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +  zusätzlich wird der Bot für eine kurze Zeit offline sein, in dieser Zeit wird der Bot nicht erreichbar sein.
Is it not correct? I think that’s easier to understand

2024-03-20 19:38 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +  zusätzlich wird der Bot für eine kurze Zeit offline sein, in dieser Zeit wird der Bot nicht erreichbar sein.
No, a repetition is informal in this case. The sentence can be clearly understood without repeating "Zeit" another time. Wortwiederholungen are informal and should be avoided in texts with a professional audience. In this particular case, no argument for easier understanding can be made, as a clear us of the word "welcher" creates the connection to the last used object of the previous sentence.

2024-03-21 18:17 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* Version (Nur bei Custom-Bots sichtbar): Dies ist die Anzahl an veröffentlichen code-versionen. Abhängig von deiner Version wird dein Bot eventuell keine neuen Funktionen nutzen können. Wenn deine V
like you said, its "eigener bot", not "custom bot". can you change it? (I cant or Im to dumb)

2024-03-21 18:23 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +          <li>Um Update Benachrichtigungen über Beta Veröffentlichungen auf unserem <a href="https://scootk.it/dc">Discord</a> zu erhalten, aktiviere die Beat Kanäle in #beta.</li>
me and typing...

2024-03-21 18:26 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +3. Wähle den Bot-Host aus, auf den du welchseln willst.
i checked it with lanuage tool, it also says that it is "wechseln"

2024-03-21 18:29 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +    <li>Jedem Bot werden mehr Ressourcen zugewiesen.</li>
it sounds not so perfect, if you ask me it should be "Jedem Bot , der sich auf einem Premium Bot-Hosts befindet, werden mehr Ressourcen zugewiesen."

2024-03-21 18:35 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +Die (Menschliche) Sprache wird für alle Standart-konfiguration-eingaben und Nachrichten die nicht eingestellt werden können verwendet. Es kann vorkommen, dass der Modmail Bot nicht diese, sondern die
Standardtkonfigurationwete :/
Standardtkonfigurationwerte

2024-03-21 18:35 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +Wenn du die Bot Sprache wechselst, bitte beachte dass du nicht die eingestellten Datein neu generierst - du müsstest die Datei zurücksetzen oder es selbst übersetzen.
bitt -> bitte

2024-03-21 18:38 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +            <li>Speichere die Änderungen & starte den Bot neu um die Änderungen anzunehmen.</li>
:/

2024-03-21 18:40 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +            <li>Sichere die Änderungen & lade die Konfiguration neu um die Änderungen abzunehmen. </li>
typo, i wanted do write anzunehmen

2024-03-21 19:10 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* Version (Nur bei Custom-Bots sichtbar): Dies ist die Anzahl an veröffentlichen code-versionen. Abhängig von deiner Version wird dein Bot eventuell keine neuen Funktionen nutzen können. Wenn deine V
:+1:

2024-03-21 19:12 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +            <li>Wir kündingen jedes Update auf unserem <a href="https://scootk.it/dc">Discord-Server</a> an und senden einen Link zu dem Changelog.</li>
In German, you can't use "dem Changelog" without first establishing which object you are referring to.

2024-03-21 19:17 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +    <li>Jedem Bot werden mehr Ressourcen zugewiesen.</li>
lots of words to say the same things, the original string was still wrong as it changed the meaning of the translation

2024-03-21 19:18 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +Die (Menschliche) Sprache wird für alle Standart-konfiguration-eingaben und Nachrichten die nicht eingestellt werden können verwendet. Es kann vorkommen, dass der Modmail Bot nicht diese, sondern die
:+1:

2024-03-21 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +            <li>Sichere die Änderungen & lade die Konfiguration neu um die Änderungen abzunehmen. </li>
anzunehmen is not fitting in this context.

2024-03-21 19:20 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +            <li>Speichere die Änderungen & starte den Bot neu um die Änderungen anzunehmen.</li>
(:

2024-03-21 19:23 UTC, SCDerox reviewed
GitHub didn't let me save all my comments

2024-03-30 18:48 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +Die (Menschliche) Sprache wird für alle Standart-konfiguration-eingaben und Nachrichten die nicht eingestellt werden können verwendet. Es kann vorkommen, dass der Modmail Bot nicht diese, sondern die
some things are optional to change...
and e.g. adding in links "de/" is something that i didnt know

2024-03-30 18:49 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +2. Als nächtes klicke auf "Wechseln", dann auf "Server" in der "Status"-Abteilung.
huh? i dont think so

2024-03-30 18:51 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +            <li>Speichere die Änderungen & starte den Bot neu um die Änderungen anzunehmen.</li>
optional

2024-03-30 18:57 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +Erlaube deinen Mitgliedern, dass Team zu kontaktieren!
correct but sounds weird

2024-04-27 20:26 UTC, SCDerox reviewed
missing comments

2024-04-27 20:31 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +| Nutzer PN                              | <i>Nur sichbar wenn "Nach schließen PN an Nutzer senden" aktiviert ist.</i><br/>Diese Nachricht wird der Nutzer erhalten, nachdem sein Ticket geschlossen wu
```suggestion
| Nutzer PN                              | <i>Nur sichbar wenn "Nach Schließen PN an Nutzer senden" aktiviert ist.</i><br/>Diese Nachricht wird der Nutzer per Privatnachricht erhalten, nachdem sein Ticket geschlossen wurde. Du kannst einen Link zum Ticket-Protkoll hinzufügen. |
```

2024-04-27 20:31 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +| Nach schließen PN an Nutzer senden | Falls aktiviert werden die Nutzer eine PN nach Schließung des Tickets erhalten.
```suggestion
| Nach Schließen PN an Nutzer senden | Falls aktiviert, werden die Nutzer eine PN nach Schließung des Tickets erhalten.                                                                                                                                  |                                                                                                                                 |
```

2024-04-27 20:31 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +| Log-Kanal                          | Das Transcript wird in diesen Kanal gesendet, nachdem ein Ticket geschlossen wurde.
```suggestion
| Log-Kanal                          | Das Protokoll wird in diesen Kanal gesendet, nachdem ein Ticket geschlossen wurde.                                                                                                                                   |
```

2024-04-27 20:31 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* der Bot genügend Berechtigungenhat um Kanäle zu erstellen, zu löschen und zu verwalten.
```suggestion
* der Bot genügend Berechtigungen hat, um Kanäle zu erstellen, zu löschen und zu verwalten. 
```

2024-04-27 20:31 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* deine [Kategorie Konfiguration](#configuration) ist gültig und du hast keine leeren Kategorien hinzugefügt.
```suggestion
* deine [Kategorie-Konfiguration](#configuration) ist gültig und du hast keine leeren Kategorien hinzugefügt hast. 
```

2024-04-27 20:31 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* dein Server hat maximal 500 Kanäle (Discord Limit).
```suggestion
* dein Server nicht die maximal 500 zugelassene Kanäle hat (Discord Limit).
```

2024-04-27 20:46 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* ```
```suggestion
```

2024-05-12 21:44 UTC, SCDerox requested changes
There are still some issues in your translation, including unfixed issues that you marked as resolved. Please review my comments carefully and don't close them until you have either actually fixed them or commented on them explaining why you disagree.

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* Erstelle mehrere Ticket-Themen mit unabhäniger Konfiguration.
```suggestion
* Erstelle mehrere Ticket-Themen mit unabhängiger Konfiguration.
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +:::Info
```suggestion
:::info
```
wrong formatting

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +## Features {#features}
```suggestion
## Funktionen {#features}
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* der Bot genügend Berechtigungenhat um Kanäle zu erstellen, zu löschen und zu verwalten.
THIS HAS NOT BEEN RESOLVED

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* Lasse automatisch Ticket-Transcript erstellen.
```suggestion
* Lasse automatisch Ticket-Protokoll erstellen.
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +| Log-Kanal                          | Das Transcript wird in diesen Kanal gesendet, nachdem ein Ticket geschlossen wurde.
THIS HAS NOT BEEN RESOLVED

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* deine [Kategorie Konfiguration](#configuration) ist gültig und du hast keine leeren Kategorien hinzugefügt.
THIS HAS NOT BEEN RESOLVED

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +* dein Server hat maximal 500 Kanäle (Discord Limit).
THIS HAS NOT BEEN RESOLVED

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +| Nutzer PN                              | <i>Nur sichbar wenn "Nach schließen PN an Nutzer senden" aktiviert ist.</i><br/>Diese Nachricht wird der Nutzer erhalten, nachdem sein Ticket geschlossen wu
THIS HAS NOT BEEN RESOLVED

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/support /tickets.md
> +| Nach schließen PN an Nutzer senden | Falls aktiviert werden die Nutzer eine PN nach Schließung des Tickets erhalten.
THIS HAS NOT BEEN RESOLVED

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +          <li>Um Benachrichtigungen über die Veröffentlichung von neuen Beta-Version auf unserem <href="https://scootk.it/dc">Discord</a> zu erhalten, aktiviere die Beta-Kanäle in #beta.</li>
```suggestion
          <li>Um Benachrichtigungen über die Veröffentlichung von neuen Beta-Version auf unserem <a href="https://scootk.it/dc">Discord</a> zu erhalten, aktiviere die Beta-Kanäle in #beta.</li>
```

broken html

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +Wie du sehen kannst, gibt es hier beriets einige Möglichkeiten. Hier sind die wichtigsten Informationen, die du darüber wissen musst:
```suggestion
Wie du sehen kannst, gibt es hier bereits einige Möglichkeiten. Hier sind die wichtigsten Informationen über das Panel:
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* Der Tag und das Profilbild deines Bots (nur sichbar wenn dein Bot online ist). Um das Profil deines Bots zu wechseln,
```suggestion
* Der Tag und das Profilbild deines Bots (nur sichtbar wenn dein Bot online ist). Um das Profil deines Bots zu wechseln,
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* "Konfiguration neu laden": Wenn du deine Konfiguration neu lädst, wird dein Bot alle Änderungen übernommen (auch Modul-Änderungen)
```suggestion
* "Konfiguration neuladen": Wenn du deine Konfiguration neulädst, wird dein Bot alle ausstehenden Änderungen an Konfigurationsdatein übernehmen (auch Modul-Änderungen)
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +    <TabItem value="customBot" label="Custom Bot">
```suggestion
    <TabItem value="customBot" label="Eigener Bot">
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +Diese Dokumente beinhaltet anwendbare Hilfen für den [Custom Bot](../../custom-bot/intro) und den
```suggestion
Diese Dokumente beinhaltet anwendbare Hilfen für den [Eigenen Bot](../../custom-bot/intro) und den
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +            <li>Wir veröffentlichen regelmäßig Updates für Discord-Bots - wir stellen meist mehrere Funktionen in ein Update für die öffentliche Version. Für die <a href="#beta">Öffentliche Beta</a>
```suggestion
            <li>Wir veröffentlichen regelmäßig Updates für Discord-Bots - wir fassen meist mehrere Funktionen in einem Update für die stabile Version zusammen. Für die <a href="#beta">Öffentliche Beta</a> gibt es viele Veröffentlichungen mit weniger Änderungen pro Veröffentlichung, manchmal mehrere an einem Tag.</li>
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +          <li>Manche Updates oder Fehler-behebungen werden nicht angekündigt - dein Modmail Bot wird sie einfach istallieren.</li>
```suggestion
          <li>Manche Updates oder Fehlerbehebungen werden nicht angekündigt - dein Modmail Bot wird sie einfach installieren.</li>
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +          <li>Die öffentliche Beta kann instabil sein. Das bedeutet, dass es passieren kann, dass dein Bot crashed oder neue Funktionen nicht korrekt funktionieren.</li>
```suggestion
          <li>Die öffentliche Beta kann instabil sein. Das bedeutet, dass es passieren kann, dass dein Bot abstürzt oder neue Funktionen nicht korrekt funktionieren.</li>
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* Branch (Nur bei Custom-Bots verfügbar): Der aktuelle Zweig (englisch "branch") ist eine Version deines eigenen Bots auf einer anderen Programmier-Basis. Du solltest es diesen bei "v3" (Stabie Versi
```suggestion
* Branch (Nur bei Custom-Bots verfügbar): Der aktuelle Zweig (englisch "branch") ist eine Version deines eigenen Bots auf einer anderen Programmier-Basis. Du solltest es diesen bei "v3" (Stabile Version) belassen, aber wenn du willst, kannst du auch zu dem "Beta"-Branch wechseln (das ist die Öffentliche Beta; kann aber instabil sein).
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +3. Wähle den Bot-Host aus, auf den du Welchseln willst.
```suggestion
3. Wähle den Bot-Host aus, auf den du Wechseln willst.
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +Wir haben hohe Standarts bei den Bot-Hosts und können versichern, dass alle das gleiche Erlebniss geben. Eventuell werden wir deinen Bot zwischen den Bot-Hosts verschieben, wenn du keinen bezahlten P
```suggestion
Wir haben hohe Standards bei den Bot-Hosts und können versichern, dass alle das gleiche Erlebnis bieten. Eventuell werden wir deinen Bot zwischen den Bot-Hosts verschieben, wenn du keinen bezahlten Plan hast, um Ressourcen zu sparen.
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +2. Klicke als Nächtes auf "Wechseln", dann auf "Server" in der "Status"-Abteilung.
```suggestion
2. Klicke unter "Bot-Status" bei der Sprache deines Bots auf "Wechseln".
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* damit dies funktioniert muss dein Bot auf SCNX online sein. Wenn dein Bot nicht auf SCNX online sein sollte, schaue bitte in die [Anleitung zur Fehlerbehebung](#troubleshooting).
```suggestion
* Damit dies funktioniert muss dein Bot auf SCNX online sein. Wenn dein Bot nicht auf SCNX online sein sollte, schaue bitte in die [Anleitung zur Fehlerbehebung](#troubleshooting).
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +1.Öffne das [Modmail-](https://scnx.app/de/glink?page=modmail/manage?showEditProfile=true)
```suggestion
1. Öffne das [Modmail-](https://scnx.app/de/glink?page=modmail/manage?showEditProfile=true)
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* Dafür muss dein Bot online sein. Wenn dein Bot nicht auf SCNX online ist, öffne bitte den Abschnitt „Der Bot ist nicht auf meinem Server“ im unserem [Leitfaden zur Fehlerbehebung](#troubleshooting)
```suggestion
Dafür muss dein Bot online sein. Wenn dein Bot nicht auf SCNX online ist, öffne bitte den Abschnitt „Der Bot ist nicht auf meinem Server“ im unserem [Leitfaden zur Fehlerbehebung](#troubleshooting).
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +Bot Logs zu Teilen, ist eine „Einmalige Erfassung“ davon - geteilte Logs werden nicht aktualisiert, wenn dein Bot etwas Neues dokumentiert. Die geteilten Logs werden nach 7 Tagen,  nachdem du sie get
```suggestion
Bot Logs zu Teilen, ist eine „Einmalige Erfassung“ davon - geteilte Logs werden nicht aktualisiert, wenn dein Bot etwas Neues dokumentiert. Die geteilten Logs werden nach 7 Tagen,  nachdem du sie geteilt hast, gelöscht. Logs beinhalten meinst keine privaten Informationen, aber bitte schaue trotzdem darüber, bevor du sie veröffentlichst.
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +2. Als Nächstes, klicke auf "mehr Optionen" in dem Bot-Status-Panel.
```suggestion
2. Als Nächstes, klicke auf "Mehr Optionen" in dem Bot-Status-Panel.
```

2024-05-12 21:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +2. Als Nächstes klicke auf "mehr Optionen" in deinem Bot-Status-Panel.
```suggestion
2. Als Nächstes klicke auf "Mehr Optionen" in deinem Bot-Status-Panel.
```

2024-05-19 09:16 UTC, SCDerox approved these changes
lgtm

2024-05-19 09:37 UTC, Fridolin012 submitted a review, later dismissed

2024-05-19 09:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +Diese Dokumente beinhaltet anwendbare Hilfen für den [Eigenen Bot](../../custom-bot/intro) und den
```suggestion
Diese Dokumente beinhalten anwendbare Hilfen für den [Eigenen Bot](../../custom-bot/intro) und den
```

2024-05-19 09:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* Modmail-Bot
Verlinkung fehlt

2024-05-19 09:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* Der Tag und das Profilbild deines Bots (nur sichtbar wenn dein Bot online ist). Um das Profil deines Bots zu wechseln,
```suggestion
* Der Tag und das Profilbild deines Bots (nur sichtbar, wenn dein Bot online ist). Um das Profil deines Bots zu verändern,
```

2024-05-19 09:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> + klicke auf dieses oder befolge [diesem Artikel](#change-profile).
```suggestion
 klicke auf dieses oder befolge [diesen Artikel](#change-profile).
```

2024-05-19 09:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* "Konfiguration neuladen": Wenn du deine Konfiguration neulädst, wird dein Bot alle ausstehenden Änderungen an Konfigurationsdatein übernehmen (auch Modul-Änderungen)
```suggestion
* "Konfiguration neuladen": Wenn du deine Konfiguration neulädst, wird dein Bot alle ausstehenden Änderungen an Konfigurationsdateien übernehmen (auch Modul-Änderungen)
```

2024-05-19 09:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* "Bot anhalten": Dies wird den Prozess deines Bots beenden. Es wird nicht auf Discord erreichbar sein. Es kann bis zu 5 Minuten dauern, bis der Bot in Discord als offline angezeigt wird.
```suggestion
* "Bot anhalten": Dies wird den Prozess deines Bots beenden. Er wird nicht auf Discord erreichbar sein. Es kann bis zu 5 Minuten dauern, bis der Bot in Discord als offline angezeigt wird.
```

2024-05-19 09:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* "Log" / "Fehler-Log": In diesen Log-Datein wird dein Bot dokumentieren, was er macht und wird die Gründe von Fehlern und Problemen aufschreiben. Unser Team (und technische Experten) benötigen diese
```suggestion
* "Log" / "Fehler-Log": In diesen Log-Dateien wird dein Bot dokumentieren, was er macht und wird die Gründe von Fehlern und Problemen aufschreiben. Unser Team (und technische Experten) benötigen diese Logs, um eventuelle Probleme zu analysieren und dir eine Lösung vorzuschlagen - oder, falls es Fehler im Bot selbst sind, diese zu reparieren. Eventuell wirst du gefragt, die [Logs zu teilen](#sharing-logs).
```

2024-05-19 09:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* Server: Dies ist der physische Server - auch Bot-Host genannt - auf dem dein Bot betrieben wird. Du kannst den [Bot-Host wechseln](#bot-host) wenn du möchtest.
```suggestion
* Server: Dies ist der physische Server - auch Bot-Host genannt - auf dem dein Bot betrieben wird. Du kannst den [Bot-Host wechseln](#bot-host), wenn du möchtest.
```

2024-05-19 09:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* Branch (Nur bei Custom-Bots verfügbar): Der aktuelle Zweig (englisch "branch") ist eine Version deines eigenen Bots auf einer anderen Programmier-Basis. Du solltest es diesen bei "v3" (Stabile Vers
```suggestion
* Branch (nur beim eigenen Bot verfügbar): Der aktuelle Zweig (englisch "branch") ist eine Version deines eigenen Bots auf einer anderen Programmier-Basis. Du solltest es diesen bei "v3" (Stabile Version) belassen, aber wenn du willst, kannst du auch zu dem "Beta"-Branch wechseln (das ist die öffentliche Beta; kann aber instabil sein).
```

2024-05-19 09:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* Version (Nur bei eigenen Bots sichtbar): Dies ist die aktuelle Version des Codes deines Bots. Abhängig von deiner Version wird dein Bot eventuell neuen Funktionen nicht nutzen können. Wenn deine Ve
```suggestion
* Version (nur bei eigenen Bots sichtbar): Dies ist die aktuelle Version des Codes deines Bots. Abhängig von deiner Version wird dein Bot eventuell neue Funktionen nicht nutzen können. Wenn deine Version nicht aktuell ist, wird eine Warnung angezeigt. Dein Modmail-Bot wird immer automatisch auf den neusten Stand aktualisiert. Erfahre mehr über [Updates & Versionen](#bot-updates).
```

2024-05-20 14:00 UTC, SCDerox requested changes

2024-05-20 14:00 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +# Bots von SCNX
```suggestion
# Bots auf SCNX
```

2024-05-20 14:02 UTC, hoernchen-from-hotel commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* Modmail-Bot
Wo?

2024-05-20 14:07 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/scnx/guilds /bots.md
> +* Modmail-Bot
This is intended, the original article has no link either, this can be resolved.

2024-05-20 15:19 UTC, SCDerox approved these changes
lgtm

2024-05-22 07:23 UTC, merged

2024-06-15 09:53 UTC, SCDerox commented
Thanks for your contribution - you have received a payout as part of our Open-Source Developer Program. You can find details in your SCNX organization payout history. To pay out the received amount, please follow instructions in your dashboard. If you have any questions, please contact ScootKit staff on scnx.app/help.