Create polls.md
ScootKit/scnx-docs pull request #47
Opened 2024-02-28 13:41 UTC by MKFeuer

## Type of PR

- [ X ] Translation update / creation
- [ ] Original file creation
- [ ] Original file content (not typo) update
- [ ] Original file typo update

## Checks

If you have changed the content (/ meaning) of an original file, please confirm:

- [ ] Yes, I have copied the updated section to all translations of this file manually.

## Notes

new try, because last try faild

2024-02-28 19:53 UTC, Fridolin012 requested changes

2024-02-28 20:05 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Einfaches Modul zum Erstellen neuer Umfragen auf Ihrem Server!
Ok thanks 

you write me that in dc

2024-02-28 20:05 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +## Funktionen {#funktionen}
ok i'will do it

2024-02-28 20:06 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Hier ist ein Beispiel, wenn eine Umfrage beendet, ist:
ok

2024-02-28 20:06 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +## Einrichtung {#einrichtung}
ok

2024-02-28 20:18 UTC, MKFeuer reviewed
updated all thinks

2024-03-05 20:48 UTC, Fridolin012 requested changes

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Leicht verständliche Ergebnisanzeige, welche live geupdatet wird.
```suggestion
* Leicht verständliche Ergebnisanzeige, welche live aktualisiert wird.
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Automatisch endende Umfragen, nach Ablauf einer festgelegten Zeit.
```suggestion
* Automatisch nach Ablauf einer festgelegten Zeit endende Umfragen.
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Hier ist ein Beispiel, einer beendeten Umfrage:
```suggestion
Hier ist ein Beispiel einer beendeten Umfrage:
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Um mit dem Modul Umfragen zu starten, stelle sicher, dass dein Bot in jedem Channel, in dem du Umfragen verwenden willst,
```suggestion
* Um mit dem Modul Umfragen zu starten, stelle sicher, dass dein Bot in jedem Kanal, in dem du Umfragen verwenden willst,
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Stelle sicher, dass Du [die Rechte](./../../slash-commands) für [`/poll`](#commands) korrekt eingestellt haben.
```suggestion
* Stelle sicher, dass du [die Rechte](./../../slash-commands) für [`/poll`](#commands) korrekt eingestellt hast.
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Administratoren können Umfragen mit folgenden Commands managen:
```suggestion
Administratoren können Umfragen mit folgenden Befehlen verwalten:
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* [`/poll create`](#commands) Zum Erstellen neuer Umfragen.
```suggestion
* [`/poll create`](#commands) zum Erstellen einer neuen Umfrage.
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* [`/poll end`](#commands) Zum Beenden einer Umfrage (Umfragen enden automatisch, wenn du `/poll create` den Dauerparameter gesetzt haben).
```suggestion
* [`/poll end`](#commands) zum Beenden einer Umfrage (Umfragen enden automatisch, wenn du bei `/poll create` den Zeitparameter gesetzt hast).
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Über Umfragen abstimmen, unter Verwendung des Auswahl Menüs unter der Umfrage.
```suggestion
* Mit dem Dropdown-Menü unter Umfragen abstimmen.
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Ihre Antwort einsehen, für die Du gestimmt haben, über den Knopf „Für was habe ich abgestimmt“ unter der Abstimmung.
```suggestion
* Sehen, für was sie gestimmt haben, indem sie den Knopf „Für was habe ich abgestimmt?“ unter der Abstimmung nutzen.
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Ihre Stimme entfernen, wenn Du zuerst „Für was habe ich gestimmt“ ausgewählt haben und danach auf „Meine Stimme entfernen“ unter der Rückmeldung klicken.
```suggestion
* Ihre Stimme entfernen, wenn sie zuerst „Für was habe ich abgestimmt?“ auswählen und danach auf „Meine Stimme entfernen“ unter der Antwort klicken.
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Liveergebnisse im Umfragen Embed sehen.
```suggestion
* Liveergebnisse im Umfragen-Embed sehen.
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +  Stimmen anzeigen“ unter dem Abstimmungs-Embed klicken (falls die Umfrage auf Öffentlich gestellt ist).
```suggestion
* Sich anschauen, wer für welche Option gestimmt hat, indem sie auf den Knopf „Aktuelle
  Stimmen anzeigen“ unter dem Abstimmungs-Embed klicken (falls die Umfrage auf öffentlich gestellt ist).
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Ihrem [Dashboard](https://scnx.app/de/glink?page=bot/configuration?query=poll&file=polls|configs/config).
```suggestion
In dieser Datei kannst du die Emojis neben den Abstimmungsoptionen anpassen. Öffne sie in 
deinem [Dashboard](https://scnx.app/de/glink?page=bot/configuration?query=poll&file=polls|configs/config).
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +| Emojis | In diesen Feldern kannst Du die Emojis anpassen, die neben jeder Abstimmungsoption im Dropdown-Menü und in der Einbettung angezeigt werden. Stelle sicher, dass Du Unicode-Werte für integri
```suggestion
| Emojis | In diesen Feldern kannst du die Emojis anpassen, die neben jeder Abstimmungsoption im Dropdown-Menü und im Embed angezeigt werden. Stelle sicher, dass du Unicode-Werte für integrierte Emojis oder gültige Emoji-IDs (nicht nur den Namen) für benutzerdefinierte Emojis eingibst. |
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +### Nachricht {#configuration-strings}
```suggestion
### Nachrichten {#configuration-strings}
```

2024-03-05 20:48 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +[Dashboard](https://scnx.app/de/glink?page=bot/configuration?query=poll&file=polls|configs/strings).
```suggestion
In dieser Datei kannst du anpassen, wie das Umfrage-Embed in Discord angezeigt wird. Öffne sie in deinem
[Dashboard](https://scnx.app/de/glink?page=bot/configuration?query=poll&file=polls|configs/strings).
```

2024-03-05 21:05 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Einfaches Modul zum Erstellen neuer Umfragen auf Ihrem Server!
done

2024-03-05 21:06 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Leicht verständliche Ergebnisanzeige, welche live geupdatet wird.
done

2024-03-05 21:06 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Automatisch endende Umfragen, nach Ablauf einer festgelegten Zeit.
done

2024-03-05 21:06 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Hier ist ein Beispiel, einer beendeten Umfrage:
done

2024-03-05 21:06 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Um mit dem Modul Umfragen zu starten, stelle sicher, dass dein Bot in jedem Channel, in dem du Umfragen verwenden willst,
done

2024-03-05 21:06 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Administratoren können Umfragen mit folgenden Commands managen:
done

2024-03-05 21:07 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* [`/poll end`](#commands) Zum Beenden einer Umfrage (Umfragen enden automatisch, wenn du `/poll create` den Dauerparameter gesetzt haben).
done

2024-03-05 21:07 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Über Umfragen abstimmen, unter Verwendung des Auswahl Menüs unter der Umfrage.
done

2024-03-05 21:07 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Ihre Antwort einsehen, für die Du gestimmt haben, über den Knopf „Für was habe ich abgestimmt“ unter der Abstimmung.
done

2024-03-05 21:07 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Ihre Stimme entfernen, wenn Du zuerst „Für was habe ich gestimmt“ ausgewählt haben und danach auf „Meine Stimme entfernen“ unter der Rückmeldung klicken.
done

2024-03-05 21:07 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Liveergebnisse im Umfragen Embed sehen.
done

2024-03-05 21:07 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +  Stimmen anzeigen“ unter dem Abstimmungs-Embed klicken (falls die Umfrage auf Öffentlich gestellt ist).
done

2024-03-05 21:08 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Ihrem [Dashboard](https://scnx.app/de/glink?page=bot/configuration?query=poll&file=polls|configs/config).
done

2024-03-05 21:08 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +| Emojis | In diesen Feldern kannst Du die Emojis anpassen, die neben jeder Abstimmungsoption im Dropdown-Menü und in der Einbettung angezeigt werden. Stelle sicher, dass Du Unicode-Werte für integri
done

2024-03-05 21:08 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +### Nachricht {#configuration-strings}
done

2024-03-05 21:08 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +[Dashboard](https://scnx.app/de/glink?page=bot/configuration?query=poll&file=polls|configs/strings).
done

2024-03-05 21:11 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Hier ist ein Beispiel, wenn eine Umfrage beendet, ist:
done

2024-03-07 20:36 UTC, Fridolin012 requested changes

2024-03-07 20:36 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +| `/polls create description:<Text> channel:<TextChannel> option1:<Text> option2:<Text> [option{n}:<Text>] [duration:<TimeDuration>] [public:<Boolean>]` | Erstelle im gewünschten Kanal eine neue Umfr
```suggestion
| `/polls create description:<Text> channel:<TextKanal> option1:<Text> option2:<Text> [option{n}:<Text>] [duration:<ZeitDauer>] [public:<Boolean>]` | Erstelle im gewünschten Kanal eine neue Umfrage. Gib die Umfragefrage als `description` Wert ein und füge mögliche Optionen mit dem Element `option{n}` hinzu. Optional kannst Du eine Umfrage mit der Option `public` öffentlich machen (das bedeutet, dass jeder sehen kann, wofür Benutzer gestimmt haben). Wenn diese Option aktiviert ist, wird unterhalb der Umfrage die Schaltfläche „Aktuelle Stimmen anzeigen“ hinzugefügt. Um eine Umfrage automatisch zu beenden, gibst du eine `duration` in einem [unterstützten Zeitdauerwert](./../../additional-features#durations) an. |
```

2024-03-07 20:36 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +| `/polls end msg-id:<PollMessageID>`                                                                                                                    | Beendet eine bereits bestehende Umfrage, die
```suggestion
| `/polls end msg-id:<UmfragenNachrichtID>`                                                                                                                    | Beendet sofort eine bereits bestehende Umfrage, die noch nicht beendet wurde. Die Option `msg-id` unterstützt die automatische Vervollständigung, sodass du problemlos nach der Umfragebeschreibung der Umfrage suchen kannst, die du beenden möchtest.                                                                                                                                                                                                                        |
```

2024-03-07 20:36 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +deinem [Dashboard](https://scnx.app/de/glink?page=bot/configuration?query=poll&file=polls|configs/config).
```suggestion
In dieser Datei kannst du die Emojis neben den Abstimmungsoptionen anpassen. Öffne sie in 
deinem [Dashboard](https://scnx.app/de/glink?page=bot/configuration?query=poll&file=polls|configs/config).
```

2024-03-07 20:36 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +| Emojis | In diesen Feldern kannst du die Emojis anpassen, die neben jeder Abstimmungsoption im Dropdown-Menü und im Embed angezeigt werden. Stelle sicher, dass Du Unicode-Werte für integrierte Emoj
```suggestion
| Emojis | In diesen Feldern kannst du die Emojis anpassen, die neben jeder Abstimmungsoption im Dropdown-Menü und im Embed angezeigt werden. Stelle sicher, dass du Unicode-Werte für integrierte Emojis oder gültige Emoji-IDs (nicht nur den Namen) für benutzerdefinierte Emojis eingibst. |
```

2024-03-07 20:36 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +In dieser Datei kannst du anpassen, wie das Umfrage-Embed in Discord angezeigt wird. Öffnen sie es in deinem
```suggestion
In dieser Datei kannst du anpassen, wie das Umfrage-Embed in Discord angezeigt wird. Öffne sie in deinem
```

2024-03-07 20:36 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +| Embed | Mit dieser Konfigurationsoption kannst Du anpassen, wie die Umfrageeinbettung in Discord angezeigt wird. Die folgenden Werte können angepasst werden: <ul><li><code>title</code>: Der Name de
```suggestion
| Embed | Mit dieser Konfigurationsoption kannst Du anpassen, wie das Umfrage-Embed in Discord angezeigt wird. Die folgenden Werte können angepasst werden: <ul><li><code>title</code>: Der Name des Embeds.</li><li><code>color</code>: Die Farbe des Embeds, muss ein <a href="../../additional-features#embed-colors">unterstützter Farbwert</a> sein.</li><li><code>options</code>: Die Überschrift des Optionsfelds im Embed.</li><li><code>liveView</code>: Die Überschrift der (Live-)Ergebnisanzeige im Embed.</li><li><code>expiresOn</code>: Die Überschrift der Anzeige der Ablaufzeit im Embed.</li><li><code>endedPollTitle</code>: Die Überschrift des Embeds, wenn die Umfrage beendet wurde.</li><li><code>endedPollColor</code>: Die Farbe des Embeds, wenn die Umfrage beendet ist. Muss ein <a href="../../additional-features#embed-colors">unterstützter Farbwert</a> sein.</li><li><code>visibility</code>: Die Überschrift des Öffentlichkeitsabschnitts des Embeds.</li></ul> |
```

2024-03-07 20:36 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Wenn Du Probleme mit dem Umfragemodul haben, stelle bitte sicher, dass
```suggestion
Wenn du Probleme mit dem Umfragemodul hast, stelle bitte sicher, dass
```

2024-03-07 20:36 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Die folgenden Daten werden über jede Abfrage gespeichert, die über [Befehle](#commands) erstellt wird :
```suggestion
Die folgenden Daten werden über jede Umfrage gespeichert, die über [Befehle](#commands) erstellt wird:
```

2024-03-07 20:36 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Die Frage nach der Umfrage (Wert im Befehl), einschließlich der Frage, ob die Umfrage öffentlich ist oder nicht (`description` value in the command), einschließlich der Frage, ob die Umfrage öffent
```suggestion
* Die Frage der Umfrage (`description`-Wert im Befehl), inkludiert, ob die Umfrage öffentlich ist oder nicht
```

2024-03-07 20:36 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Der Wert jeder Abstimmungsoption ( Werte im Befehl) (`option{n}` values in the command)
```suggestion
* Der Wert jeder Abstimmungsoption (`option{n}`-Wert im Befehl)
```

2024-03-07 20:36 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +  die Umfrage ist beendet
```suggestion
* Falls aktiviert: Genaue Uhrzeit, zu der die Umfrage abläuft (gesteuert durch den `duration`-Wert im Befehl) und ob die Umfrage beendet ist
```

2024-03-07 20:36 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Die Nummer der Option, für die Du gestimmt haben
```suggestion
* Die Nummer der Option, für die gestimmt wurde
```

2024-03-07 20:36 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Wenn die Umfrage noch nicht beendet ist, können Benutzer [Ihre Stimme entfernen](#usage). Nach Beendigung einer Umfrage ist diese Option nicht mehr verfügbar.
```suggestion
Wenn die Umfrage noch nicht beendet ist, können Benutzer [ihre Stimme entfernen](#usage). Nach Beendigung einer Umfrage ist diese Option nicht mehr verfügbar.
```

2024-03-07 20:36 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +löschen aller Umfragen, [lösche die Moduldatenbank](./../../additional-features#reset-module-database).
```suggestion
Es gibt keine Möglichkeit, Umfragen aus der Datenbank zu entfernen (du kannst die Umfrage trotzdem jederzeit löschen). Zum
Löschen aller Umfragen, [lösche die Moduldatenbank](./../../additional-features#reset-module-database).
```

2024-03-07 20:40 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +| `/polls create description:<Text> channel:<TextChannel> option1:<Text> option2:<Text> [option{n}:<Text>] [duration:<TimeDuration>] [public:<Boolean>]` | Erstelle im gewünschten Kanal eine neue Umfr
done

2024-03-07 20:42 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +| `/polls end msg-id:<PollMessageID>`                                                                                                                    | Beendet eine bereits bestehende Umfrage, die
done

2024-03-07 20:42 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +deinem [Dashboard](https://scnx.app/de/glink?page=bot/configuration?query=poll&file=polls|configs/config).
done

2024-03-07 20:42 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +| Emojis | In diesen Feldern kannst du die Emojis anpassen, die neben jeder Abstimmungsoption im Dropdown-Menü und im Embed angezeigt werden. Stelle sicher, dass Du Unicode-Werte für integrierte Emoj
done

2024-03-07 20:43 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +In dieser Datei kannst du anpassen, wie das Umfrage-Embed in Discord angezeigt wird. Öffnen sie es in deinem
done

2024-03-07 20:46 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +| Embed | Mit dieser Konfigurationsoption kannst Du anpassen, wie die Umfrageeinbettung in Discord angezeigt wird. Die folgenden Werte können angepasst werden: <ul><li><code>title</code>: Der Name de
done

2024-03-07 20:47 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Die folgenden Daten werden über jede Abfrage gespeichert, die über [Befehle](#commands) erstellt wird :
done

2024-03-07 20:48 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Die Frage nach der Umfrage (Wert im Befehl), einschließlich der Frage, ob die Umfrage öffentlich ist oder nicht (`description` value in the command), einschließlich der Frage, ob die Umfrage öffent
done

2024-03-07 20:48 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Wenn Du Probleme mit dem Umfragemodul haben, stelle bitte sicher, dass
done

2024-03-07 20:49 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Der Wert jeder Abstimmungsoption ( Werte im Befehl) (`option{n}` values in the command)
done

2024-03-07 20:49 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +  die Umfrage ist beendet
done

2024-03-07 20:50 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Die Nummer der Option, für die Du gestimmt haben
done

2024-03-07 20:50 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Wenn die Umfrage noch nicht beendet ist, können Benutzer [Ihre Stimme entfernen](#usage). Nach Beendigung einer Umfrage ist diese Option nicht mehr verfügbar.
done

2024-03-07 20:51 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +löschen aller Umfragen, [lösche die Moduldatenbank](./../../additional-features#reset-module-database).
done

2024-03-07 21:00 UTC, Fridolin012 requested changes

2024-03-07 21:00 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Der Bot über die folgenden Berechtigungen für den Kanal, in dem Du eine Umfrage starten möchten: Nachrichten lesen, Nachrichten senden, Links einbetten verfügt.
```suggestion
* der Bot über die folgenden Berechtigungen in dem Kanal, in dem du eine Umfrage starten möchtest, verfügt: Nachrichten lesen, Nachrichten senden, Links einbetten.
```

2024-03-08 09:06 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Du hast keine Umfrage in einem Ankündigungskanal gestartet hast (da Nachrichten in solchen Kanälen nicht so häufig aktualisiert werden können).
done

2024-03-08 09:06 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Ihre [Nachrichtenkonfiguration](#configuration-strings) keine leeren Felder enthält, und das [Farbwerte gültig sind](../../additional-features#embed-colors).
done

2024-03-08 09:06 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Ihre [Konfiguration](#configuration-config) nur gültige Emoji-Werte (Unicode für integrierte Emojis und Emoji-IDs für benutzerdefinierte Emojis)enthält .
done

2024-03-08 09:08 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Der Bot über die folgenden Berechtigungen für den Kanal, in dem Du eine Umfrage starten möchten: Nachrichten lesen, Nachrichten senden, Links einbetten verfügt.
done

2024-03-08 09:15 UTC, Fridolin012 requested changes
2 last things

2024-03-08 09:15 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* deine [Konfiguration](#configuration-config) nur gültige Emoji-Werte (Unicode für integrierte Emojis und Emoji-IDs für benutzerdefinierte Emojis)enthält .
```suggestion
* deine [Konfiguration](#configuration-config) nur gültige Emoji-Werte (Unicode für integrierte Emojis und Emoji-IDs für benutzerdefinierte Emojis) enthält .
```

2024-03-08 09:17 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* deine [Konfiguration](#configuration-config) nur gültige Emoji-Werte (Unicode für integrierte Emojis und Emoji-IDs für benutzerdefinierte Emojis)enthält .
done

2024-03-08 09:17 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* deine [Nachrichtenkonfiguration](#configuration-strings) keine leeren Felder enthält, und das [Farbwerte gültig sind](../../additional-features#embed-colors).
done

2024-03-08 09:18 UTC, MKFeuer commented
2 last things solved

2024-03-08 09:28 UTC, Fridolin012 submitted a review, later dismissed

2024-03-17 12:51 UTC, SCDerox requested changes

2024-03-17 12:51 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* deine [Konfiguration](#configuration-config) nur gültige Emoji-Werte (Unicode für integrierte Emojis und Emoji-IDs für benutzerdefinierte Emojis) enthält .
```suggestion
* deine [Konfiguration](#configuration-config) nur gültige Emoji-Werte (Unicode für integrierte Emojis und Emoji-IDs für benutzerdefinierte Emojis) enthält.
```

2024-03-17 12:51 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Die folgenden Daten werden über jede Umfrage gespeichert, die über [Befehle](#commands) erstellt wird :
```suggestion
Die folgenden Daten werden über jede Umfrage gespeichert, die über [Befehle](#commands) erstellt wird:
```

2024-03-17 12:51 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Metadaten über Ihren Server anzeigen (z. B. Name, Symbol, Besitzer, ...)
```suggestion
* Die eindeutige Identifikationsnummer der Umfragenachricht, die nach der Erstellung gesendet wurde
* Die eindeutige Identifikationsnummer des Kanals, in dem die Umfrage erstellt wurde
* Die Frage der Umfrage (`description`-Wert im Befehl), inkludiert, ob die Umfrage öffentlich ist oder nicht
* Der Wert jeder Abstimmungsoption (`option{n}`-Wert im Befehl)
* Falls aktiviert: Genaue Uhrzeit, zu der die Umfrage abläuft (gesteuert durch den `duration`-Wert im Befehl) und ob die Umfrage beendet ist
* Metadaten über deinen Server anzeigen (z. B. Name, Symbol, Besitzer, ...)
```

2024-03-17 12:51 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Die ID des Benutzers
```suggestion
* Die eindeutige Identifikationsnummer des Benutzers
```

2024-03-17 12:56 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Automatisch nach Ablauf einer festgelegten Zeit endende Umfragen.
done

2024-03-17 12:56 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* [`/poll create`](#commands) zum erstellen neuer Umfragen.
done

2024-03-17 12:57 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* deine [Konfiguration](#configuration-config) nur gültige Emoji-Werte (Unicode für integrierte Emojis und Emoji-IDs für benutzerdefinierte Emojis) enthält .
done

2024-03-17 12:57 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +Die folgenden Daten werden über jede Umfrage gespeichert, die über [Befehle](#commands) erstellt wird :
done

2024-03-17 12:58 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Metadaten über Ihren Server anzeigen (z. B. Name, Symbol, Besitzer, ...)
done

2024-03-17 12:58 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/community/polls.md
> +* Die ID des Benutzers
done

2024-03-17 13:07 UTC, SCDerox approved these changes
lgtm

2024-03-17 13:08 UTC, merged

2024-03-20 16:43 UTC, SCDerox commented
Thanks for your contribution - you have received a payout as part of our Open-Source Developer Program. You can find details in your SCNX organization payout history. To pay out the received amount, please follow instructions in your dashboard. If you have any questions, please contact ScootKit staff on scnx.app/help.
Cheers ✌️