Create afk-system.md
ScootKit/scnx-docs pull request #48
Opened 2024-03-17 19:54 UTC by hfgd123

## Type of PR

- [X] Translation update / creation
- [ ] Original file creation
- [ ] Original file content (not typo) update
- [ ] Original file typo update

## Checks

If you have changed the content (/ meaning) of an original file, please confirm:

- [N/A] Yes, I have copied the updated section to all translations of this file manually.

## Notes

Please enter additional information here.

2024-03-18 12:17 UTC, SCDerox requested changes

2024-03-18 12:17 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/tools/afk-system.md
> +Erlaube Nutzern einen AFK-Status zu setzen der anderen Nutzern automatisch mitgeteilt wird, wenn sie versuchen ihn/sie zu erreichen.
```suggestion
Erlaube Nutzern einen AFK-Status zu setzen, der anderen Nutzern automatisch mitgeteilt wird, wenn sie versuchen ihn/sie zu erreichen.
```

2024-03-18 12:17 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/tools/afk-system.md
> +* AFK-Sitzungen werden automatisch beendet, wenn der AFK Nutzer eine Nachricht in einen beliebigen Kanal auf deinem Server sendet (sofern sie dies nicht zu beginn der AFK-Sitzung deaktiviert haben).
```suggestion
```suggestion
* AFK-Sitzungen werden automatisch beendet, wenn der AFK Nutzer eine Nachricht in einen beliebigen Kanal auf deinem Server sendet (sofern sie dies nicht zu beginn der AFK-Sitzung deaktiviert haben).
```
* AFK-Sitzungen werden automatisch beendet, wenn der AFK Nutzer eine Nachricht in einen beliebigen Kanal auf deinem Server sendet (sofern sie dies nicht zu beginn der AFK-Sitzung deaktiviert haben).
```
```suggestion
* AFK-Sitzungen werden automatisch beendet, wenn der AFK Nutzer eine Nachricht in einen beliebigen Kanal auf deinem Server sendet (sofern sie dies nicht zu Beginn der AFK-Sitzung deaktiviert haben).
```

2024-03-18 12:17 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/tools/afk-system.md
> +* Während einer AFK-Sitzung, wird der Bot dem Namen des Nutzers ein `[AFK]` als Präfix hinzufügen.
```suggestion
* Während einer AFK-Sitzung fügt der Bot zum Namen des Nutzers ein `[AFK]` als Präfix hinzu.
```

2024-03-18 12:17 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/tools/afk-system.md
> +1. Stelle sicher, dass der Bot die Berechtigungen "Kanal anzeigen", "Nachrichtenverlauf anzeigen" und "Nachrichten senden" in jedem Kanal hat, in dem er auf Erwähnungen von Nutzern, die AFK sind reag
```suggestion
1. Stelle sicher, dass der Bot die Berechtigungen "Kanal anzeigen", "Nachrichtenverlauf anzeigen" und "Nachrichten senden" in jedem Kanal hat, in welchen er auf Erwähnungen von Nutzern, die AFK sind, reagieren soll.
```

2024-03-18 12:17 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/tools/afk-system.md
> +2. Stelle sicher, dass der Bot die Berechtigung hat die Nicknames anderer Nutzer auf deinem Server zu verwalten.
```suggestion
2. Stelle sicher, dass der Bot die Berechtigung hat, die Nicknamen anderer Nutzer auf deinem Server zu verwalten.
```

2024-03-18 12:17 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/tools/afk-system.md
> +| AFK-Sitzung automatisch beendet  | Diese Nachricht wird gesendet, wenn ein Nutzer, der aktuell AFK ist und das Automatische Ende der AFK-Sitzung nicht deaktiviert hat, eine Nachricht auf deinem Ser
```suggestion
| AFK-Sitzung automatisch beendet  | Diese Nachricht wird gesendet, wenn ein Nutzer, der aktuell AFK ist und das Automatische Ende der AFK-Sitzung nicht deaktiviert hat, eine Nachricht auf deinem Server schreibt. Dies beendet die AFK-Sitzung. |
```

2024-03-18 12:17 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/tools/afk-system.md
> +* Wenn der Bot eine AFK-Sitzung nicht automatisch beendet, stelle sicher, dass `auto-end` nicht zu Beginn der AFK-Sitzung deaktiviert wurde
```suggestion
* Wenn der Bot eine AFK-Sitzung nicht automatisch beendet, stelle sicher, dass `auto-end` nicht zu Beginn der AFK-Sitzung deaktiviert wurde.
```

2024-03-18 12:17 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/tools/afk-system.md
> +* Ihre eindeutige Discord User-ID.
```suggestion
* Ihre eindeutige Discord Nutzer-Indentifikationsnummer.
```

2024-03-18 14:42 UTC, hfgd123 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/tools/afk-system.md
> +2. Stelle sicher, dass der Bot die Berechtigung hat die Nicknames anderer Nutzer auf deinem Server zu verwalten.
Discord officially calls it "Nicknames" even in German 🤔

2024-03-18 14:44 UTC, hfgd123 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/tools/afk-system.md
> +* AFK-Sitzungen werden automatisch beendet, wenn der AFK Nutzer eine Nachricht in einen beliebigen Kanal auf deinem Server sendet (sofern sie dies nicht zu beginn der AFK-Sitzung deaktiviert haben).
I don't really understand this suggestion

2024-03-18 16:23 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/tools/afk-system.md
> +* AFK-Sitzungen werden automatisch beendet, wenn der AFK Nutzer eine Nachricht in einen beliebigen Kanal auf deinem Server sendet (sofern sie dies nicht zu beginn der AFK-Sitzung deaktiviert haben).
sry i my brain is working overtime

2024-03-18 18:59 UTC, Fridolin012 requested changes

2024-03-20 16:47 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/tools/afk-system.md
> +2. Stelle sicher, dass der Bot die Berechtigung hat die Nicknames anderer Nutzer auf deinem Server zu verwalten.
Wait actually?

2024-03-20 17:06 UTC, hfgd123 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/tools/afk-system.md
> +2. Stelle sicher, dass der Bot die Berechtigung hat die Nicknames anderer Nutzer auf deinem Server zu verwalten.
![Screenshot_20240320-180533](https://github.com/ScootKit/scnx-docs/assets/46094961/4fa359dd-1205-4b42-8406-2fe4a66d7a21)

2024-03-21 20:41 UTC, Fridolin012 approved these changes

2024-03-23 13:36 UTC, hfgd123 commented
🤔

2024-03-23 16:48 UTC, merged

2024-04-03 20:50 UTC, SCDerox commented
Thanks for your contribution - you have received a payout as part of our Open-Source Developer Program. You can find details in your SCNX organization payout history. To pay out the received amount, please follow instructions in your dashboard. If you have any questions, please contact ScootKit staff on scnx.app/help.
Cheers ✌️