Create uno.md
ScootKit/scnx-docs pull request #49
Opened 2024-03-21 14:58 UTC by MKFeuer

## Type of PR

- [ X ] Translation update / creation
- [ ] Original file creation
- [ ] Original file content (not typo) update
- [ ] Original file typo update

## Checks

If you have changed the content (/ meaning) of an original file, please confirm:

- [ ] Yes, I have copied the updated section to all translations of this file manually.

## Notes

Please enter additional information here.

2024-03-21 20:37 UTC, Fridolin012 requested changes

2024-03-21 20:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Lasst eure User gegeneinander Uno spielen!
```suggestion
Lasse deine Nutzer gegeneinander Uno spielen!
```

2024-03-21 20:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Uno ist ein klassisches Kartenspiel - jetzt auch für deinen Eigenen Bot verfügbar! Wenn du mehr über das Spiel selbst erfahren möchten, schauen dir den [Wikipedia Artikel](https://de.wikipedia.org/wi
```suggestion
Uno ist ein klassisches Kartenspiel - jetzt auch für deinen eigenen Bot verfügbar! Wenn du mehr über das Spiel selbst erfahren möchten, schau dir den [Wikipedia Artikel](https://de.wikipedia.org/wiki/Uno_(Kartenspiel)) an.
```

2024-03-21 20:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Die Einrichtung ist wirklich einfach – aktivieren sie einfach das Modul in [deinem SCNX-Dashboard](https://scnx.app/de/glink?page=bot/modules?query=uno&ref=scnx-app-docs) und schon kann es losgehen!
```suggestion
Die Einrichtung ist wirklich einfach - aktiviere einfach das Modul in [deinem SCNX-Dashboard](https://scnx.app/de/glink?page=bot/modules?query=uno&ref=scnx-app-docs) und schon kann es losgehen!
```

2024-03-21 20:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Um ein Uno-Spiel zu starten, führen sie den Slash-Befehl `/uno` aus – andere Spieler können dann über die Schaltfläche „Spiel beitreten“ beitreten. Nach 90 Sekunden oder nachdem der Benutzer, der den
```suggestion
Um ein Uno-Spiel zu starten, führe den Slash-Befehl `/uno` aus - andere Spieler können dann über den Knopf „Spiel beitreten“ beitreten. Nach 90 Sekunden oder nachdem der Benutzer, der den Befehl ausführt, auf den Knopf „Spiel sofort starten“ geklickt hat, beginnt das Spiel.
```

2024-03-21 20:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +:::
```suggestion
:::tip Spiel-Thread 
Es ist am besten, einen Thread für Spieldiskussionen zu erstellen, damit der Kanal nicht zu voll mit spielbezogenen Nachrichten wird.
:::
```

2024-03-21 20:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Inaktive Spieler werden nach 60 Sekunden, wenn sie an der Reihe sind, verwarnt und nach weiteren 60 Sekunden aus dem Spiel geworfen.
```suggestion
Inaktive Spieler werden 60 Sekunden, nachdem sie an die Reihe gekommen sind verwarnt und nach weiteren 60 Sekunden aus dem Spiel entfernt.
```

2024-03-21 20:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +In den meisten Fällen verwendet jeder Spieler eine Karte, indem er eine Karte aus seinem Kartenstapel auswählt, und dann ist der nächste Spieler an der Reihe – beachten Sie, dass die Zugreihenfolge m
```suggestion
In den meisten Fällen verwendet jeder Spieler eine Karte, indem er eine Karte aus seinem Kartenstapel auswählt, wonach der nächste Spieler an der Reihe ist - beachte, dass die Zugreihenfolge mithilfe der Sonderkarte „Umkehren“ umgekehrt werden kann.
```

2024-03-21 20:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Es gibt normale Zahlenkarten von 0-9 in den Farben Blau, Grün, Rot und Gelb sowie Sonderkarten. Zu den Sonderkarten gehört die Funktion „Farbwahl“, mit der eine gewünschte Farbe für die nächste Karte
```suggestion
Es gibt normale Zahlenkarten von 0-9 in den Farben Blau, Grün, Rot und Gelb sowie Sonderkarten. Zu den Sonderkarten gehört die „Farbwahl“, mit der eine gewünschte Farbe für die nächste Karte ausgewählt werden kann; „Reverse“, was die Spielrichtung ändert; und „Überspringen“, wodurch der nächste Spieler übersprungen wird.
```

2024-03-21 20:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +| `/uno`  | Startet ein Uno-Spiel im aktuellen Kanal. Weitere Informationen zur Funktionsweise finden sie im [Abschnitt zur Verwendung](#usage) oben.
```suggestion
| Befehl | Beschreibung                                                                                                            |
|---------|------------------------------------------------------------------------------------------------------------------------|
| `/uno`  | Startet ein Uno-Spiel im aktuellen Kanal. Weitere Informationen zur Funktionsweise findest du im [Abschnitt zur Verwendung](#usage) oben. 
```

2024-03-21 20:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +    <li>Sie können eine neue Nachricht mit Ihrem aktuellen Kartendeck erhalten, einschließlich einer Schaltfläche zum Aktualisieren, indem du auf die Schaltfläche „Deck anzeigen“ in der ursprüngliche
```suggestion
    <li>Du kannst eine neue Nachricht mit deinem aktuellen Kartendeck erhalten, einschließlich einem Knopf zum Aktualisieren, indem du auf die Schaltfläche „Deck anzeigen“ in der ursprünglichen Spielnachricht klickst.</li>
```

2024-03-21 20:37 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +    <li>Sie müssen zuerst auf Uno! klicken. Klicken Sie auf die Schaltfläche auf der ursprünglichen Spielnachricht, bevor Sie Ihre vorletzte Karte ausspielen. Dies gilt nicht für das Ausspielen der l
```suggestion
    <summary>Der Bot sagt: "⚠️️️ Du musst den Uno!-Button nutzen, bevor du die vorletzte Karte legst! " - wieso?</summary>
    <li>Du musst zuerst auf "Uno!"-Knopf der ursprünglichen Spielnachricht klicken, bevor du deine vorletzte Karte ausspielst. Das gilt nicht für das Ausspielen der letzten Karte.</li>
```

2024-03-21 21:10 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Lasst eure User gegeneinander Uno spielen!
done

2024-03-21 21:11 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Uno ist ein klassisches Kartenspiel - jetzt auch für deinen Eigenen Bot verfügbar! Wenn du mehr über das Spiel selbst erfahren möchten, schauen dir den [Wikipedia Artikel](https://de.wikipedia.org/wi
done

2024-03-21 21:11 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Die Einrichtung ist wirklich einfach – aktivieren sie einfach das Modul in [deinem SCNX-Dashboard](https://scnx.app/de/glink?page=bot/modules?query=uno&ref=scnx-app-docs) und schon kann es losgehen!
done

2024-03-21 21:13 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Um ein Uno-Spiel zu starten, führen sie den Slash-Befehl `/uno` aus – andere Spieler können dann über die Schaltfläche „Spiel beitreten“ beitreten. Nach 90 Sekunden oder nachdem der Benutzer, der den
done

2024-03-21 21:13 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +:::
done

2024-03-21 21:14 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Inaktive Spieler werden nach 60 Sekunden, wenn sie an der Reihe sind, verwarnt und nach weiteren 60 Sekunden aus dem Spiel geworfen.
done

2024-03-21 21:15 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +In den meisten Fällen verwendet jeder Spieler eine Karte, indem er eine Karte aus seinem Kartenstapel auswählt, und dann ist der nächste Spieler an der Reihe – beachten Sie, dass die Zugreihenfolge m
done

2024-03-21 21:15 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Es gibt normale Zahlenkarten von 0-9 in den Farben Blau, Grün, Rot und Gelb sowie Sonderkarten. Zu den Sonderkarten gehört die Funktion „Farbwahl“, mit der eine gewünschte Farbe für die nächste Karte
done

2024-03-21 21:16 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +| `/uno`  | Startet ein Uno-Spiel im aktuellen Kanal. Weitere Informationen zur Funktionsweise finden sie im [Abschnitt zur Verwendung](#usage) oben.
sorry hatte ich übersehen 

aber done

2024-03-21 21:17 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +    <li>Sie können eine neue Nachricht mit Ihrem aktuellen Kartendeck erhalten, einschließlich einer Schaltfläche zum Aktualisieren, indem du auf die Schaltfläche „Deck anzeigen“ in der ursprüngliche
done

2024-03-21 21:20 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +    <li>Sie müssen zuerst auf Uno! klicken. Klicken Sie auf die Schaltfläche auf der ursprünglichen Spielnachricht, bevor Sie Ihre vorletzte Karte ausspielen. Dies gilt nicht für das Ausspielen der l
done

2024-03-22 13:17 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Lasst eure User gegeneinander Uno spielen!
No?

2024-03-22 13:29 UTC, Fridolin012 requested changes

2024-03-22 13:29 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Lasse deine User gegeneinander Uno spielen!
```suggestion
Lasse deine Nutzer gegeneinander Uno spielen!
```

2024-03-22 13:29 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Uno ist ein klassisches Kartenspiel - jetzt auch für deinen eigenen Bot verfügbar! Wenn du mehr über das Spiel selbst erfahren möchten, schau dir den [Wikipedia Artikel](https://de.wikipedia.org/wiki
```suggestion
Uno ist ein klassisches Kartenspiel - jetzt auch für deinen eigenen Bot verfügbar! Wenn du mehr über das Spiel erfahren möchtest, schau dir den [Wikipedia Artikel](https://de.wikipedia.org/wiki/Uno_(Kartenspiel)) an.
```

2024-03-22 13:29 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +In den meisten Fällen verwendet jeder Spieler eine Karte, indem er eine Karte aus seinem Kartenstapel auswählt, wonach der nächste Spieler an der Reihe ist - beachten Sie, dass die Zugreihenfolge mit
```suggestion
In den meisten Fällen verwendet jeder Spieler eine Karte, indem er eine Karte aus seinem Kartenstapel auswählt, wonach der nächste Spieler an der Reihe ist - beachte, dass die Zugreihenfolge mithilfe der Sonderkarte „Umkehren“ umgekehrt werden kann.
```

2024-03-22 13:29 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +### Karten und Specialeffekte {#cards}
```suggestion
### Karten und Spezialeffekte {#cards}
```

2024-03-22 13:29 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +## Commands {#commands}
```suggestion
## Befehle {#commands}
```

2024-03-22 13:29 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +    <summary>Wie kann ich eine Karte spielen/Wo ist mein Kartendeck?</summary>
```suggestion
    <summary>Wie kann ich eine Karte spielen / Wo ist mein Kartendeck?</summary>
```

2024-03-22 13:29 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +    <li>Du kannst eine neue Nachricht mit deinem aktuellen Kartendeck erhalten, einschließlich einer Schaltfläche zum Aktualisieren, indem du auf die Schaltfläche „Deck anzeigen“ in der ursprüngliche
```suggestion
    <li>Du kannst eine neue Nachricht mit deinem aktuellen Kartendeck und einem Knopf zum Aktualisieren erhalten, indem du auf den Knopf „Eigene Karten ansehen“ in der ursprünglichen Spielnachricht klickst.</li>
```

2024-03-22 13:29 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +    <li>u musst zuerst auf "Uno!"-Knopf der ursprünglichen Spielnachricht klicken, bevor du deine vorletzte Karte ausspielst. Das gilt nicht für das Ausspielen der letzten Karte.</li>
```suggestion
    <summary>Der Bot sagt: "⚠️️️ Du musst den Uno!-Button nutzen, bevor du die vorletzte Karte legst!" - wieso?</summary>
    <li>Du musst zuerst auf den "Uno!"-Knopf der ursprünglichen Spielnachricht klicken, bevor du deine vorletzte Karte ausspielst. Das gilt nicht für das Ausspielen der letzten Karte.</li>
```

2024-03-24 17:32 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Lasst eure User gegeneinander Uno spielen!
now jet

2024-03-24 17:33 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Uno ist ein klassisches Kartenspiel - jetzt auch für deinen Eigenen Bot verfügbar! Wenn du mehr über das Spiel selbst erfahren möchten, schauen dir den [Wikipedia Artikel](https://de.wikipedia.org/wi
no isue

2024-03-24 17:34 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Die Einrichtung ist wirklich einfach – aktivieren sie einfach das Modul in [deinem SCNX-Dashboard](https://scnx.app/de/glink?page=bot/modules?query=uno&ref=scnx-app-docs) und schon kann es losgehen!
no issue

2024-03-24 17:35 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Um ein Uno-Spiel zu starten, führen sie den Slash-Befehl `/uno` aus – andere Spieler können dann über die Schaltfläche „Spiel beitreten“ beitreten. Nach 90 Sekunden oder nachdem der Benutzer, der den
no issue

2024-03-24 17:36 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +:::
no issue

2024-03-24 17:36 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Inaktive Spieler werden nach 60 Sekunden, wenn sie an der Reihe sind, verwarnt und nach weiteren 60 Sekunden aus dem Spiel geworfen.
no issue

2024-03-24 17:37 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Lasse deine User gegeneinander Uno spielen!
no issue in my code

2024-03-24 17:38 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Uno ist ein klassisches Kartenspiel - jetzt auch für deinen eigenen Bot verfügbar! Wenn du mehr über das Spiel selbst erfahren möchten, schau dir den [Wikipedia Artikel](https://de.wikipedia.org/wiki
solved

2024-03-24 17:39 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +In den meisten Fällen verwendet jeder Spieler eine Karte, indem er eine Karte aus seinem Kartenstapel auswählt, wonach der nächste Spieler an der Reihe ist - beachten Sie, dass die Zugreihenfolge mit
solved

2024-03-24 17:39 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +## Commands {#commands}
sorry i miss it

2024-03-24 17:40 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +### Karten und Specialeffekte {#cards}
correckted

2024-03-24 17:40 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +    <summary>Wie kann ich eine Karte spielen/Wo ist mein Kartendeck?</summary>
solved

2024-03-24 17:41 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +    <li>Du kannst eine neue Nachricht mit deinem aktuellen Kartendeck erhalten, einschließlich einer Schaltfläche zum Aktualisieren, indem du auf die Schaltfläche „Deck anzeigen“ in der ursprüngliche
solved

2024-03-24 17:43 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +    <li>u musst zuerst auf "Uno!"-Knopf der ursprünglichen Spielnachricht klicken, bevor du deine vorletzte Karte ausspielst. Das gilt nicht für das Ausspielen der letzten Karte.</li>
i don't know wath happend during my las correction, but i fixed it now

2024-04-14 18:58 UTC, Fridolin012 requested changes

2024-04-14 18:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Uno ist ein klassisches Kartenspiel - jetzt auch für deinen eigenen Bot verfügbar! Wenn du mehr über das Spiel erfahren möchten, schau dir den [Wikipedia Artikel](https://de.wikipedia.org/wiki/Uno_(K
```suggestion
Uno ist ein klassisches Kartenspiel - jetzt auch für deinen eigenen Bot verfügbar! Wenn du mehr über das Spiel erfahren möchtest, schau dir den [Wikipedia Artikel](https://de.wikipedia.org/wiki/Uno_(Kartenspiel)) an.
```

2024-04-14 18:58 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Um ein Uno-Spiel zu starten, führe den Slash-Befehl `/uno` aus - andere Spieler können dann über den Knopf „Spiel beitreten“ beitreten. Nach 90 Sekunden oder nachdem der Benutzer, der den Befehl ausf
```suggestion
Um ein Uno-Spiel zu starten, führe den Slash-Befehl `/uno` aus - andere Spieler können dann über den Knopf „Spiel beitreten“ beitreten. Nach 90 Sekunden oder nachdem der Benutzer, der den Befehl ausgeführt hat, auf den Knopf „Spiel sofort starten“ geklickt hat, beginnt das Spiel.
```

2024-04-14 19:00 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Uno ist ein klassisches Kartenspiel - jetzt auch für deinen eigenen Bot verfügbar! Wenn du mehr über das Spiel erfahren möchten, schau dir den [Wikipedia Artikel](https://de.wikipedia.org/wiki/Uno_(K
solved

2024-04-14 19:01 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Um ein Uno-Spiel zu starten, führe den Slash-Befehl `/uno` aus - andere Spieler können dann über den Knopf „Spiel beitreten“ beitreten. Nach 90 Sekunden oder nachdem der Benutzer, der den Befehl ausf
solved

2024-04-15 13:00 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +In den meisten Fällen verwendet jeder Spieler eine Karte, indem er eine Karte aus seinem Kartenstapel auswählt, wonach der nächste Spieler an der Reihe ist - beachte, dass die Zugreihenfolge mithilfe
done

2024-04-15 13:00 UTC, MKFeuer commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/fun/uno.md
> +Es gibt normale Zahlenkarten von 0-9 in den Farben Blau, Grün, Rot und Gelb sowie Sonderkarten. Zu den Sonderkarten gehört die „Farbwahl“, mit der eine gewünschte Farbe für die nächste Karte ausgewäh
done

2024-04-15 13:02 UTC, Fridolin012 approved these changes

2024-04-15 13:03 UTC, merged

2024-04-27 18:19 UTC, SCDerox commented
Thanks for your contribution - you have received a payout as part of our Open-Source Developer Program. You can find details in your SCNX organization payout history. To pay out the received amount, please follow instructions in your dashboard. If you have any questions, please contact ScootKit staff on scnx.app/help.