Translate team-goals
ScootKit/scnx-docs pull request #53
Opened 2024-07-15 14:49 UTC by Fridolin012

## Type of PR

- [X] Translation update / creation
- [ ] Original file creation
- [ ] Original file content (not typo) update
- [ ] Original file typo update

## Checks

If you have changed the content (/ meaning) of an original file, please confirm:

- [ ] Yes, I have copied the updated section to all translations of this file manually.

## Notes

Please enter additional information here.

2024-07-15 20:44 UTC, SCDerox requested changes

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +* Sende Nutzern jede Woche über PNs ihr Ergebnis oder in einen konfigurierten Kanal.
```suggestion
* Sende Nutzern ihr Ergebniss jede Woche per PN oder in einen konfigurierten Kanal.
```

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +* Du kannst immer den Fortschritt von dir oder einem anderem Nutzer mit [`/team-goals progress`](#commands) und die Zielhistorie mit [`/team-goals history`](#commands) einsehen.
```suggestion
* Du kannst immer den Fortschritt von dir oder einem anderem Nutzer mit [`/team-goals progress`](#commands) und den früheren Zielverlauf mit [`/team-goals history`](#commands) einsehen.
```

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +| `/team-goals history [user:<Nutzer>]`  | Zeigt die Zielhistorie (Anzahl der Nachrichten, Ziel erreicht oder nicht, Prozentsatz der erreichten Ziele) der letzten 10 Wochen des angegebenen Benutzers
```suggestion
| `/team-goals history [user:<Nutzer>]`  | Zeigt den früheren Zielverlauf (Anzahl der Nachrichten, Ziel erreicht oder nicht, Prozentsatz der erreichten Ziele) der letzten 10 Wochen des angegebenen Benutzers an (wenn leer, wird dein Verlauf angezeigt).                        |
```

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +* Eine **Auswertung** ist der Zeitpunkt, zu dem ein Nutzer ausgewertet wird. Dies geschieht einmal pro Woche. Der eigentliche         Zeitpunkt ist davon abhängig, wann das Modul zum ersten mal aktiv
```suggestion
* Eine **Auswertung** ist der Zeitpunkt, zu dem ein Nutzer ausgewertet wird. Dies geschieht einmal pro Woche. Der eigentliche Zeitpunkt ist abhängig davon, wann das Modul zum ersten mal aktiviert wurde - die erste Auswertung wird genau eine Woche
```

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +| Team-Rollen                                              | Diese Rollen werden jede Woche hinsichtlich ihres Fortschritts zum Ziel [ausgewertet](#module-terms). Nur von Nutzern mit diesen Rollen we
```suggestion
| Team-Rollen                                              | Diese Rollen werden jede Woche hinsichtlich ihres Fortschritts zum Ziel [ausgewertet](#module-terms). Es werden nur die Nachrichten von Nutzern mit dieser Rolle gezählt.                                                                       |
```

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +| Ignorierte Channel                                       | Nachrichten von Nutzern mit mindestens einer der Teammitglieder-Rollen werden in diesen Kanälen nicht zu ihrem Ziel hinzugerechnet.
```suggestion
| Ignorierte Kanäle                                       | Nachrichten von Nutzern mit mindestens einer der Teammitglieder-Rollen werden in diesen Kanälen nicht zu ihrem Ziel hinzugerechnet.                                                                                                           |
```

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +    <li>der Bot Zugriff auf jeden Kanal hat, von welchem Nachrichten gezählt werden sollen und dass der Kanal kein <a href="#configuration">ignorierter Kanal</a> ist.</li>
```suggestion
    <li>der Bot Zugriff auf jeden Kanal hat, in welchem Nachrichten gezählt werden sollen, und dass der Kanal kein <a href="#configuration">ignorierter Kanal</a> ist.</li>
```

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +    <li>der Nutzer mindestens eine der <a href="#configuration">konfigurierten Teammitglieder-Rollen</a> hat. Es werden nur Nachrichten gezählt, die gesendet wurden, während mindestens eine Teammitgl
```suggestion
    <li>der Nutzer mindestens eine der <a href="#configuration">konfigurierten Teammitglieder-Rollen</a> hat. Es werden nur Nachrichten gezählt, die von Nutzern gesendet wurden, welche während dem Senden mindestens eine Teammitglieder-Rolle besessen haben - Nachrichten, die gesendet werden, bevor ein Nutzer die Teammitglieder-Rolle hat, werden nicht gezählt.</li>
```

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +  Selbst wenn keine Auswertung gesendet wurde, kannst du immer die Zielhistorie mit dem Slash-Befehl <a href="#commands"><code>/team-goals history</code></a> einsehen.
```suggestion
  Selbst wenn keine Auswertung gesendet wurde, kannst du immer den früheren Zielverlauf mit dem Slash-Befehl <a href="#commands"><code>/team-goals history</code></a> einsehen.
```

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +  Eine solche Nutzung verstößt gegen unsere <a href="https://sc-net.work/scnx-tos">Nutzungsbedingungen</a>, da du unsere Software nutzt, um deine mit Spam zu belästigen. Du darfst das Modul nur
```suggestion
  Eine solche Nutzung verstößt gegen unsere <a href="https://sc-net.work/scnx-tos">Nutzungsbedingungen</a>, da du unsere Software nutzt, um deine Nutzer mit Spam zu belästigen. Du darfst das Modul nur
```

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +[konfigurierten Team-Rollen](#configuration) hat ("Zielhistorie-Eintrag"):
```suggestion
[konfigurierten Team-Rollen](#configuration) hat ("Zielverlauf-Eintrag"):
```

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +* Eine eindeutige Zahl zur Identifizierung des Datenbankeintrags
```suggestion
* Eine eindeutige Nummer zur Identifizierung des Datenbankeintrags
```

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +* Die Anzahl der Nachrichten, die sie im [Bewertungszeitraum](#module-terms) gesendet haben
```suggestion
* Die Anzahl der Nachrichten, die der Nutzer im [Bewertungszeitraum](#module-terms) gesendet hat
```

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +Es gibt keine Möglichkeit, den Nutzer-Eintrag oder den Zielhistorie-Eintrag aus der Datenbank zu entfernen.
```suggestion
Es gibt keine Möglichkeit, den Nutzer-Eintrag oder den Zielverlauf-Eintrag aus der Datenbank zu entfernen.
```

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +* Der Bot wird jede Woche überprüfen, ob die Teammitglieder das Nachrichtenziel erreicht haben.
```suggestion
* Der Bot überprüft jede Woche, ob die Teammitglieder das gesetze Nachrichtenziel erreicht haben.
```

2024-07-15 20:44 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +* Überprüfe mit [Befehlen](#commands) deinen aktuellen Fortschritt und Erfolge in der Vergangenheit.
```suggestion
* Mit [Befehlen](#commands) kannst du deinen aktuellen Fortschritt und deinen Zielverlauf in der Vergangenheit überprüfen.
```

2024-07-16 06:26 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +* Sende Nutzern jede Woche über PNs ihr Ergebnis oder in einen konfigurierten Kanal.
I think it's "Ergebnis".

2024-07-16 06:28 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +| Ignorierte Channel                                       | Nachrichten von Nutzern mit mindestens einer der Teammitglieder-Rollen werden in diesen Kanälen nicht zu ihrem Ziel hinzugerechnet.
I used the term from the dashboard.

2024-07-16 12:12 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +* Sende Nutzern jede Woche über PNs ihr Ergebnis oder in einen konfigurierten Kanal.
updated suggestion

2024-07-16 12:38 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +| Ignorierte Channel                                       | Nachrichten von Nutzern mit mindestens einer der Teammitglieder-Rollen werden in diesen Kanälen nicht zu ihrem Ziel hinzugerechnet.
Please follow our established process to report missing translations. It's still a wrong translation and as such needs to be translated here correctly.

2024-07-20 09:13 UTC, SCDerox requested changes

2024-07-20 09:13 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +    <li>der Bot die Berecchtigung hat, Nachrichten in den <a href="#configuration">konfigurierten Kanal</a> zu senden, wenn aktiviert.</li>
```suggestion
    <li>der Bot die Berechtigungen hat, Nachrichten in den <a href="#configuration">konfigurierten Kanal</a> zu senden, wenn aktiviert.</li>
```

2024-07-20 09:30 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +    <li>der Bot die Berecchtigung hat, Nachrichten in den <a href="#configuration">konfigurierten Kanal</a> zu senden, wenn aktiviert.</li>
It's just one permission, isn't it?

2024-07-20 09:35 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/team-goals.md
> +    <li>der Bot die Berecchtigung hat, Nachrichten in den <a href="#configuration">konfigurierten Kanal</a> zu senden, wenn aktiviert.</li>
Yes, I fixed my comment, sorry, still a typo

2024-07-20 09:51 UTC, SCDerox approved these changes

2024-07-20 09:51 UTC, merged

2024-08-06 08:21 UTC, SCDerox commented
Thanks for your contribution - you have received a payout as part of our Open-Source Developer Program. You can find details in your SCNX organization payout history. To pay out the received amount, please follow instructions in your dashboard. If you have any questions, please contact ScootKit staff on scnx.app/help.