Translate Welcomer
ScootKit/scnx-docs pull request #54
Opened 2024-10-31 13:32 UTC by Fridolin012

## Type of PR

- [X] Translation update / creation
- [ ] Original file creation
- [ ] Original file content (not typo) update
- [ ] Original file typo update

## Checks

If you have changed the content (/ meaning) of an original file, please confirm:

- [ ] Yes, I have copied the updated section to all translations of this file manually.

## Notes

Please enter additional information here.

2024-10-31 13:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ScootKit/scnx-docs?pullRequest=54) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ScootKit/scnx-docs?pullRequest=54) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ScootKit/scnx-docs?pullRequest=54) it.</sub>

2024-11-17 19:15 UTC, SCDerox requested changes
Thanks so much for your patience. Some small issues were identified, mostly countless spaces in wrong places (which were quite annoying to flag). Please review my comments and re-request a review once you've addressed all flagged issues.

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +* Lösche automatisch Willkommens-Nachrichten von Nutzern, die deinen Server innerhalb von 7 Tagen wieder verlassen haben.
```suggestion
* Lösche automatisch Willkommens-Nachrichten von Nutzern, die deinen Server innerhalb von 7 Tagen wieder verlassen.
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +1. Erstelle oder wähle einen deiner Kanäle, in welchen der Bot deine Nachricht schicken soll, wenn ein Nutzer             beitritt. Der Bot benötigt
```suggestion
1. Erstelle oder wähle einen deiner Kanäle, in welchen der Bot deine Nachricht schicken soll, wenn ein Nutzer beitritt. Der Bot benötigt 
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +   die Rechte "Kanal anzeigen" ("View channel"), "Nachrichten senden" ("Send messages") und "Nachrichtenverlauf           anzeigen" ("View message history") in diesem Kanal.
```suggestion
   die Rechte "Kanal anzeigen" ("View channel"), "Nachrichten senden" ("Send messages") und "Nachrichtenverlauf anzeigen" ("View message history") in diesem Kanal.
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +   [Kanal-Konfiguration](https://scnx.app/de/glink?page=bot/configuration?file=welcomer%7Cconfigs%2Fchannels) hinzu,      indem du als Kanal-Typ "join" nutzt und
```suggestion
   [Kanal-Konfiguration](https://scnx.app/de/glink?page=bot/configuration?file=welcomer%7Cconfigs%2Fchannels) hinzu, indem du als Kanal-Typ "join" nutzt und 
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +     Konfigurationsdatei und [konfiguriere](#configuration-random-messages) die zufälligen Nachrichten mit dem              Nachrichten-Typ
```suggestion
     Konfigurationsdatei und [konfiguriere](#configuration-random-messages) die zufälligen Nachrichten mit dem Nachrichten-Typ
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +     [Kanal-Konfiguration](https://scnx.app/de/glink?page=bot/configuration?file=welcomer%7Cconfigs%2Fchannels), um         die
```suggestion
     [Kanal-Konfiguration](https://scnx.app/de/glink?page=bot/configuration?file=welcomer%7Cconfigs%2Fchannels), um die 
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +   die Rechte "Kanal anzeigen" ("View channel"), "Nachrichten senden" ("Send messages") und "Nachrichtenverlauf           anzeigen" ("View message history") in diesem Kanal.
```suggestion
   die Rechte "Kanal anzeigen" ("View channel"), "Nachrichten senden" ("Send messages") und "Nachrichtenverlauf anzeigen" ("View message history") in diesem Kanal.
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +1. Erstelle oder wähle einen deiner Kanäle, in welchen der Bot eine Nachricht schreiben soll, wenn ein Nutzer deinen      Server boostet. Der Bot benötigt
```suggestion
1. Erstelle oder wähle einen deiner Kanäle, in welchen der Bot eine Nachricht schreiben soll, wenn ein Nutzer deinen Server boostet. Der Bot benötigt 
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +   und das Element [konfigurierst](#configuration-channels).
```suggestion
2. Füge den Kanal zur
   [Kanal-Konfiguration](https://scnx.app/de/glink?page=bot/configuration?file=welcomer%7Cconfigs%2Fchannels) hinzu, indem du 
   den Kanal-Typ "boost" oder "unboost" benutzt
   und das Element [konfigurierst](#configuration-channels).
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +     und [konfigure](#configuration-random-messages) die zufälligen Nachrichten mit dem Nachrichten-Typ "
```suggestion
     und [konfiguriere](#configuration-random-messages) die zufälligen Nachrichten mit dem Nachrichten-Typ
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +     boost" oder "unboost".
```suggestion
     "boost" oder "unboost".
```
otherwise a space will be added before lb

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +     die [Kanal-Konfiguration](https://scnx.app/de/glink?page=bot/configuration?file=welcomer%7Cconfigs%2Fchannels),        um die
```suggestion
     die [Kanal-Konfiguration](https://scnx.app/de/glink?page=bot/configuration?file=welcomer%7Cconfigs%2Fchannels), um die 
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +1. Erstelle oder wähle einen deiner Kanäle, in welchen der Bot deine Nachricht schicken soll, wenn ein Nutzer deinen      Server verlässt. Der Bot benötigt
```suggestion
1. Erstelle oder wähle einen deiner Kanäle, in welchen der Bot deine Nachricht schicken soll, wenn ein Nutzer deinen Server verlässt. Der Bot benötigt 
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +   die Rechte "Kanal anzeigen" ("View channel"), "Nachrichten senden" ("Send messages") und "Nachrichtenverlauf           anzeigen" ("View message history") auf diesen Kanal.
```suggestion
   die Rechte "Kanal anzeigen" ("View channel"), "Nachrichten senden" ("Send messages") und "Nachrichtenverlauf anzeigen" ("View message history") auf diesen Kanal.
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +   [Kanal-Konfiguration](https://scnx.app/de/glink?page=bot/configuration?file=welcomer%7Cconfigs%2Fchannels) hinzu,      indem du als Kanal-Typ "leave" nutzt und
```suggestion
   [Kanal-Konfiguration](https://scnx.app/de/glink?page=bot/configuration?file=welcomer%7Cconfigs%2Fchannels) hinzu, indem du als Kanal-Typ "leave" nutzt und 
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +Um Nutzern zu erlauben, einen Willkommen-Button zu benutzen, [aktiviere diese Funktion](#configuration-config) einfach in deiner Konfiguration.
```suggestion
Um Nutzern zu erlauben, einen Willkommens-Knopf zu benutzen, [aktiviere diese Funktion](#configuration-config) einfach in deiner Konfiguration. 
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +Willkommens-Nachrichten werden jedes mal gesendet, wenn ein neuer Nutzer deinem Server betritt. Du kannst einen Willkommen-Button hinzufügen, welcher es bestehenden Nutzern erlaubt, den neuen Nutzer
```suggestion
Willkommens-Nachrichten werden jedes mal gesendet, wenn ein neuer Nutzer deinem Server betritt. Du kannst einen Willkommens-Knopf hinzufügen, welcher es bestehenden Nutzern erlaubt, den neuen Nutzer willkommen zu heißen. Zusätzlich wird, falls [aktiviert](#configuration-config), die Nachricht gelöscht, wenn der Nutzer den Server innerhalb von 7 Tagen wieder verlässt.
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +Nach dem Einstellen werden neue Nachrichten einen (konfigurierbaren) Knopf haben. Wenn dieser Knopf von einem deiner Mitglieder gedrückt wird,
```suggestion
Nach dem Einstellen wird unter neuen Nachrichten ein (konfigurierbarer) Knopf angezeigt. Wenn dieser Knopf von einem deiner Mitglieder gedrückt wird, 
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +| Zufällige Nachrichten?                                           | Wenn diese Option aktivert ist, wird der Wert "Nachricht" *NICHT* genutzt. Stattdessen wird eine der [zufälligen Nachrichten](#con
```suggestion
| Zufällige Nachrichten?                                           | Wenn diese Option aktiviert ist, wird der Wert "Nachricht" *NICHT* genutzt. Stattdessen wird eine der [zufälligen Nachrichten](#configuration-random-messages) mit dem selben Kanal-Typ gesendet.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +| Willkommens-Knopf                                                | *Diese Option ist nur verfügbar, wenn "Kanal-Typ" auf "join" gesetzt ist*<br/>Wenn aktviert wird unter jede Nachricht ein Knopf an
```suggestion
| Willkommens-Knopf                                                | *Diese Option ist nur verfügbar, wenn "Kanal-Typ" auf "join" gesetzt ist*<br/>Wenn aktiviert wird unter jede Nachricht ein Knopf angehangen. Ein anderes Mitglied kann diesen Knopf drücken, worauf die konfigurierte Nachricht gesendet wird.                                                                                                                                                                                                                                                                                                                                                                                                                                               |
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +| Willkommens-Knopf-Inhalt                                         | *Nur sichtbar, wenn "Willkommens-Knopf" aktiviert ist.*<br/>Das ist der Inhalt des unter die Nachricht angehangenen Knopfs. Dieser
```suggestion
| Willkommens-Knopf-Inhalt                                         | *Nur sichtbar, wenn "Willkommens-Knopf" aktiviert ist.*<br/>Das ist der Inhalt des unter die Nachricht angehängten Knopfs. Dieser Wert muss kürzer als 100 Zeichen sein.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +Option nutzt. In diesem Fall wird der Bot zufällig eine der in dieser Datei konfigurierten Nachrichten mit dem selben Kanal-Typ auswählen.
```suggestion
Option nutzt. In diesem Fall wird der Bot zufällig eine der in dieser Datei konfigurierten Nachrichten des selben Kanal-Typs auswählen.
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +Diese Konfigurationsdatei nutzt "Config-Elemente". Ein Config-Element repräsentiert eine Nachricht mit einem bestimmten Typ. Wenn [ein Kanal](#configuration-channels) die "Zufällige Nachrichten?" Opt
```suggestion
Diese Konfigurationsdatei nutzt "Config-Elemente". Ein Config-Element repräsentiert eine Nachricht mit einem bestimmten Typ. Wenn [ein Kanal](#configuration-channels) die "Zufällige Nachrichten?" Option nutzt, wird eine zufällige Nachricht des selben Typs ausgewählt.
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +Dieses Modul ist bekanntermaßen schwierig zu beheben, da sein hochflexibles und anpassbares Design eine komplizierte Konfigurationsstruktur mit sich bringt.
```suggestion
Fehler in diesem Modul sind bekanntermaßen schwierig zu beheben, da es hochflexible und anpassbare ist und dies eine komplizierte Konfigurationsstruktur mit sich bringt. 
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +Wenn keinder der Schritte hierunter hilft (bitte probiere das zuerst!), kannst du jederzeit unsere
```suggestion
Wenn keiner der der Schritte hier unter hilft (bitte probiere das zuerst!), kannst du jederzeit unsere
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +freundlichen Teammitglieder über [scnx.app/help](https://scnx.app/help) kontaktieren.
```suggestion
freundlichen Teammitglieder über [scnx.app/de/help](https://scnx.app/help) kontaktieren.
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +      <li>Make sure a correct <a href="#configuration-channels">channel entry</a> is set up of the correct channel and correct event type.</li>
not translated

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +   Bitte schaue dir, wie im Fehlerbild angzeigt, <a href="https://sc-net.work/imgen">sc-net.work/imgen</a> an.
```suggestion
   Bitte schaue dir, wie im Fehlerbild angezeigt, <a href="https://scootk.it/imgen">scootk.it/imgen</a> an.
```

2024-11-17 19:15 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +Diese Daten werden genutzt, um gesendete Willkommensnachrichten wieder zu löschen, wenn ein Nutzer den Server innerhalb von sieben Tagen nach dem Beitreten wieder verlässt (falls [aktviert](#configur
```suggestion
Diese Daten werden genutzt, um gesendete Willkommensnachrichten wieder zu löschen, wenn ein Nutzer den Server innerhalb von sieben Tagen nach dem Beitreten wieder verlässt (falls [aktiviert](#configuration-config)). Es gibt keinen Weg, den Bot davon abzuhalten, diese Daten zu speichern (falls die Funktion im Nachhinein aktiviert wird),
```

2024-11-17 19:25 UTC, Fridolin012 commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +Wenn keinder der Schritte hierunter hilft (bitte probiere das zuerst!), kannst du jederzeit unsere
I think "hierunter" is one word

2024-11-17 19:25 UTC, SCDerox commented on i18n/de/docusaurus-plugin-content-docs/current/custom-bot/modules/administration/welcomer.md
> +Wenn keinder der Schritte hierunter hilft (bitte probiere das zuerst!), kannst du jederzeit unsere
You're right sry

2024-11-18 18:57 UTC, Fridolin012 commented
Please review your comment https://github.com/ScootKit/scnx-docs/pull/54/files#r1845564708 @SCDerox

2024-11-18 18:58 UTC, SCDerox commented
already edited.

2024-11-18 19:02 UTC, SCDerox approved these changes
Thanks for your contribution!

2024-11-18 19:02 UTC, merged